### ISSUE TITLE
add database icon

### ISSUE THREAD

**Issue by NylePudding** [twbs/icons#1000]
An icon for a database/data storage would be nice :)

EDIT: After having a second look through the icons, I noticed once for a server that would do the job, it would be nice to have a server icon with a little cog or something to represent a database though.

**Comment by vanillajonathan** [comment]
Icon of relevance:
https://icons.getbootstrap.com/icons/gear/

See #207 for a request for a whole set of database-related icons.

**Comment by mdo** [comment]
Duplicate of #207.
