### ISSUE TITLE
Add Home menu icon, not a house.

### ISSUE THREAD

**Issue by anjitpariyar** [twbs/icons#1003]

**Comment by mdo** [comment]
I don't understand what you'd want that's different from the house icons we have.

**Comment by anjitpariyar** [comment]
icon for the home menu (mostly used in the mobile app). not that exactly look like a house , espacially not with a  chimney.

(like this ) 
`<svg xmlns="http://www.w3.org/2000/svg" width="19.359" height="18" viewBox="0 0 19.359 18"><g id="Group_3182" data-name="Group 3182" transform="translate(-807.653 -8681.079)"><path id="Path_1066" data-name="Path 1066" d="M807.653,8690.759l9.68-9.68,9.68,9.68h-2.96v8.32h-4.16v-5.6h-4.96v5.6h-4.32v-8.32Z" fill="#232323"></path></g></svg>`
