### ISSUE TITLE
a bar-chart with font-weight 600 displays wrong.

### ISSUE THREAD

**Issue by thenewseason** [twbs/icons#1005]
- Windows 10
- Chrome

I love Bootstrap Icons and I use it very frequently. Thanks.

I found bar-chart icon's bug. 
If I set font-weight as 600, only last stick is thin.
Please see jsfiddle.

https://jsfiddle.net/L2094cxj/

Thanks~!

**Comment by mdo** [comment]
All bars look heavier to me in latest Safari. I'm not actually sure this should be possible or technically supported though... we only have one weight for all of our icons.
