### ISSUE TITLE
[icon request] empty octagon shape

### ISSUE THREAD

**Issue by tmorehouse** [twbs/icons#104]
Icon request for `octagon` and `octagon-fill` (and maybe `octagon-half` to be consistent with the other basic shape icons) :

![image](https://user-images.githubusercontent.com/2781561/72012850-124d5400-3233-11ea-8531-5adb936d542c.png)

**Comment by vanillajonathan** [comment]
There is a pentagon and a octagon. There could also be a hexagon.

**Comment by tmorehouse** [comment]
@vanillajonathan open a new icon request issue for easier tracking.

**Comment by vanillajonathan** [comment]
@tmorehouse Okay, #167
