### ISSUE TITLE
Website does not mention about Composer support.

### ISSUE THREAD

**Issue by PF94** [twbs/icons#1047]
I know i'm a bit annoying with Composer support, even now that it's done, but it appears that the website does not indicate that it's possible to use Bootstrap Icons with Composer.

![image](https://user-images.githubusercontent.com/45898787/137605518-bbc6edf0-cc92-4433-b386-3418ba513a7d.png)

**Comment by Dafnik** [comment]
From a logical point of view I would be splitting the npm section horizontally and add composer beneath it.
