### ISSUE TITLE
[icon request] airplane icons

### ISSUE THREAD

**Issue by tamb** [twbs/icons#106]
Would love an airplane with takeoff and land icon.
https://imageog.flaticon.com/icons/png/512/68/68542.png?size=1200x630f&pad=10,10,10,10&ext=png&bg=FFFFFFFF

https://image.flaticon.com/icons/svg/68/68380.svg

https://imageog.flaticon.com/icons/png/512/61/61212.png?size=1200x630f&pad=10,10,10,10&ext=png&bg=FFFFFFFF

**Comment by biutas** [comment]
Image is off, but yeah, if we have a truck, we should have a airplane too. And why not a motorcycle?

**Comment by shaunroselt** [comment]
Definitely agree. We need icons for all types of transportation.

**Comment by mdo** [comment]
These were added in v1.9.0.
