### ISSUE TITLE
General Git Icon

### ISSUE THREAD

**Issue by sillydan1** [twbs/icons#1065]
This could be for e.g. a button that brings users to a locally hosted git server or just general git history.

I assume that the official [git](https://git-scm.com) logo is copyrighted and would require some interaction with the copyright holders, but a merging branch icon would also suffice.

Currently the closest available icons I can find is either `bi-github`, `bi-share`, `bi-code`, `diagram-2` or `diagram-3`, but none of these are _excactly_ what I am looking for.

**Comment by vanillajonathan** [comment]
Icons for operations would also be good:
- Push
- Pull
- Merge
- Branch
- Commit
- Rebase

Icons for GitLab would also be good.
