### ISSUE TITLE
Add font-display: block; to font-face

### ISSUE THREAD

**Issue by edouardgat** [twbs/icons#1066]
Font face declaration should implement  `font-display: block;` to "ensure text remains visible during webfont load"

https://web.dev/font-display/#how-to-avoid-showing-invisible-text

(This issue is triggered in some Lighthouse or pagespeed benchmarks on any website using bootstrap icons font)

Thanks !

Edit: font-display: block; and not font-display: swap; as mentionned here : https://github.com/FortAwesome/Font-Awesome/issues/14387

**Comment by mdo** [comment]
#1010
