### ISSUE TITLE
1.7.0 mortorboard typo?

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/icons#1071]
It seems that the new icon `mortorboard.svg` might have a typo.

I think it should be spelled mort**a**rboard not mort**o**rboard.

A better name might be academic cap or graduate cap tho.

Google search results:
| Search query | Results
|-| ---: |
| "graduation cap" | 17 900 000
| "mortarboard" | 4 440 000
| "academic cap" | 895 000

**Comment by mdo** [comment]
c552e306a

**Comment by mdo** [comment]
Thanks!

**Comment by vanillajonathan** [comment]
Consider "graduation cap", I think it will be more familiar to more people and easier to find. It has more searches on Google.
