### ISSUE TITLE
Line icon

### ISSUE THREAD

**Issue by dmitrue** [twbs/icons#1072]
Hi there,

Can't figure out why doesn't Line icon look like in documentation. I'm using i tag inside a tag. Any help would be appreciated!
<img width="205" alt="Screen Shot 2021-11-02 at 12 43 38" src="https://user-images.githubusercontent.com/6647735/139793148-52c65e78-7c39-471f-a98c-e03267f1b74b.png">
vs
https://icons.getbootstrap.com/icons/line/

**Comment by Aporie** [comment]
Hi,

Have some similar bug with the webcam and newly added envelope + icons.
`<i class="bi bi-webcam-fill"></i>` 
![image](https://user-images.githubusercontent.com/3462591/140321439-539f4633-9d2b-4a01-9fe7-8a35d9598ce2.png)
`<i class="bi bi-envelope-plus-fill"></i> ` 
![image](https://user-images.githubusercontent.com/3462591/140321399-5317a5ba-9d7c-40a4-bd56-eee47b6cfe3f.png)

VS

https://icons.getbootstrap.com/icons/webcam/
https://icons.getbootstrap.com/icons/envelope-plus-fill/

**Comment by mdo** [comment]
@Aporie Can you open new issue or two for those please?

**Comment by Aporie** [comment]
Sure,

I've created [#1083](https://github.com/twbs/icons/issues/1083) and [#1084](https://github.com/twbs/icons/issues/1084)

Thanks for this nice icon set :)
