### ISSUE TITLE
Transport Icons

### ISSUE THREAD

**Issue by adamfitton** [twbs/icons#1074]
Request for transport icons:
- Bus
- Train
- Airplane
- Truck
- Car
- Railway
- Road
- Tram
- Bike
- Motorbike
- Helicopter
- Boat

**Comment by vanillajonathan** [comment]
- Airship
- Armoured personnel carrier (APC)
- Battle tank
- Drone
- Hot-air balloon 🎈
- Hovercraft
- Hyperloop
- Jetpack 😁
- Space shuttle 🚀
- Subway 🚇

**Comment by mdo** [comment]
Duplicate of #886.
