### ISSUE TITLE
Envelope plus icon display issue

### ISSUE THREAD

**Issue by Aporie** [twbs/icons#1084]
Have a bug with the "envelope plus" icon.
`<i class="bi bi-envelope-plus-fill"></i> ` 
Render:![image](https://user-images.githubusercontent.com/3462591/140321399-5317a5ba-9d7c-40a4-bd56-eee47b6cfe3f.png)
Whereas in the doc we have:
https://icons.getbootstrap.com/icons/envelope-plus-fill/

**Comment by nickatid** [comment]
Same issue for envelop check and send check.
