### ISSUE TITLE
Add a 2K icon and 360° icon

### ISSUE THREAD

**Issue by 2590081** [twbs/icons#1087]
<img width="571" alt="Capture d’écran, le 2021-11-05 à 09 40 02" src="https://user-images.githubusercontent.com/90344523/140519432-8c11c216-3204-4f9a-8230-b30ab5cf9ec1.png">

Add 360° icon #985

**Comment by mdo** [comment]
No plans for a 2K badge, and the 360 request is covered elsewhere.
