### ISSUE TITLE
Keys, Recovery Keys/Lock, Smoking, Medals, Cup and Rocket

### ISSUE THREAD

**Issue by ahmetkucukonder** [twbs/icons#1103]
Now I will use Bootstrap-Icons in my all projects, let's share the shortcomings and let's grow together!

**Comment by bhch** [comment]
Most of these already exist:

 - Key: https://icons.getbootstrap.com/icons/key/ and https://icons.getbootstrap.com/icons/key-fill/
 - Lock: https://icons.getbootstrap.com/icons/lock/ and https://icons.getbootstrap.com/icons/lock-fill/
 - Medal: https://icons.getbootstrap.com/icons/award/ and https://icons.getbootstrap.com/icons/award-fill/
 - Cup: https://icons.getbootstrap.com/icons/cup/ and https://icons.getbootstrap.com/icons/cup-fill/

**Comment by ahmetkucukonder** [comment]
> Most of these already exist:
> 
> * Key: https://icons.getbootstrap.com/icons/key/ and https://icons.getbootstrap.com/icons/key-fill/
> * Lock: https://icons.getbootstrap.com/icons/lock/ and https://icons.getbootstrap.com/icons/lock-fill/
> * Medal: https://icons.getbootstrap.com/icons/award/ and https://icons.getbootstrap.com/icons/award-fill/
> * Cup: https://icons.getbootstrap.com/icons/cup/ and https://icons.getbootstrap.com/icons/cup-fill/

Like This:
Keys: https://d1nhio0ox7pgb.cloudfront.net/_img/i_collection_png/512x512/plain/keys.png
Recovery lock/keys: https://cdn1.iconfinder.com/data/icons/restore/1000/Restore-10-512.png
Medal: https://fontawesome.com/v5.15/icons/medal?style=solid
Coffee/Cup: https://fontawesome.com/v5.15/icons/mug-hot?style=solid

I guess I didn't explain well enough, sorry my mistake 😅
