### ISSUE TITLE
intel & AMD

### ISSUE THREAD

**Issue by evrifaessa** [twbs/icons#1128]
- [intel](https://upload.wikimedia.org/wikipedia/commons/6/6a/Intel_logo_%282020%2C_dark_blue%29.svg)
- [AMD](https://upload.wikimedia.org/wikipedia/commons/7/7c/AMD_Logo.svg)

**Comment by korki43** [comment]
Those are mostly just text, I don't think that they would fit well inside of bootstrap icons. Maybe have a look at the `cpu` and `motherboard` icons.

**Comment by mdo** [comment]
Agreed on above comment. Passing on these.
