### ISSUE TITLE
Switch to https://www.npmjs.com/package/gh-pages

### ISSUE THREAD

**Issue by XhmikosR** [twbs/icons#113]
@mdo WDYT? Instead of doing that custom stuff we do now, this should be a better solution.

**Comment by mdo** [comment]
Thoughts on using an Action instead? https://github.com/marketplace/actions/hugo-deploy-github-pages

**Comment by XhmikosR** [comment]
We could use an action, but no need to use a so specific one.

https://github.com/peaceiris/actions-gh-pages

**Comment by XhmikosR** [comment]
This was fixed in #133
