### ISSUE TITLE
Biological Virus Representation

### ISSUE THREAD

**Issue by humble-barnacle001** [twbs/icons#1135]
In the era of ongoing pandemic situation kindly look into adding svg representation related to biological health issues:
- Virus/Bacteria
- Mask
- Doctor
- Hospital

**Comment by korki43** [comment]
For Doctor & Hospital see #850. But Virus/Bacteria & Mask are great requests that i haven't seen so far. Thank you!

**Comment by mdo** [comment]
Combining with #850.
