### ISSUE TITLE
File rename, Deselect All and Invert Selection

### ISSUE THREAD

**Issue by whomotwani** [twbs/icons#1136]

**Comment by korki43** [comment]
How do you imagine these icons?

**Comment by whomotwani** [comment]
Hey, while working on my side project I realized the necessity of these icons, which I recently found in Windows 10 File Explorer, please have a look.
![image](https://user-images.githubusercontent.com/65462301/147903907-b19c33a0-d60d-4151-9cbd-97d7399305c8.png)
