### ISSUE TITLE
Dollar icon is not loading

### ISSUE THREAD

**Issue by MrBessrour** [twbs/icons#1138]
I am using the bootstrap web font in Vuejs 3 project, all the icons are working except the Dollar sign $.
```
<i class="bi bi-currency-dollar"></i>
```
this is the CDN link i am using :
````
 <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
  />
```

**Comment by korki43** [comment]
Version 1.4.1 does not include the dollar icon. It was added in version 1.5.

**Comment by MrBessrour** [comment]
Thanks @korki43

**Comment by korki43** [comment]
You're welcome. If you have no further questions please close this issue.
