### ISSUE TITLE
Requesting to add doctor and medical icons

### ISSUE THREAD

**Issue by emranffl** [twbs/icons#1139]
Doctor/nurse, hospital building, stethoscope, surgery, etc, related icons are necessary and are missing.  Kindly add them.

**Comment by korki43** [comment]
fontawesome `medical` for inspiration
https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=medical&s=solid&m=free

**Comment by mdo** [comment]
Duplicate of #850.
