### ISSUE TITLE
[Suggestion] Open icon details from the docs in a modal window instead of a "new page"

### ISSUE THREAD

**Issue by WilliamStam** [twbs/icons#1142]
One of the things i hated about font awesome originally was how "clunky" it was to work with the docs part. 

would it be possible to open the icons in a modal window instead? like click on the icon, decide nopes.. click on the next 1. 

this way you dont loose your "place" on the list and you dont have to open in new tab the whole time. 

Im presuming since the docs are built up and become static files this might be a bit more "interesting" to solve. but it really would be useful i think

Apologies if this is in the wrong place. i

**Comment by mdo** [comment]
For now we'll leave as is—the pages are helpful for permalinks to individual icons. Wouldn't mind some kind of modal or quick copy on the homepage eventually though.
