### ISSUE TITLE
Apple Icon not Working

### ISSUE THREAD

**Issue by farisfaisalthena** [twbs/icons#1143]
When using `<i class="bi bi-apple"></i>`, the icon will not be rendered.

- Operating System - MacOS Monterey (Version 12.0.1)
- Browser - Google Chrome (Version 96.0.4664.110 (Official Build) (x86_64))

**Comment by humble-barnacle001** [comment]
Have you included the corresponding css stylesheet?

**Comment by farisfaisalthena** [comment]
could u elaborate please

**Comment by humble-barnacle001** [comment]
Have you followed any of the following steps: https://icons.getbootstrap.com/#install ?

**Comment by humble-barnacle001** [comment]
Make it something like this:
```html
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    </head>
    <body>
        <i class="bi bi-apple"></i>
    </body>
</html>
```

**Comment by farisfaisalthena** [comment]
> `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">`

When updating bootstrap-icon dependencies, this was not updated as well. I have fixed it and now its working as expected. Thank you

**Comment by humble-barnacle001** [comment]
I guess you could close the issue if your problem is resolved
