### ISSUE TITLE
I miss the Cut, Copy, Paste, Undo and Redo 

### ISSUE THREAD

**Issue by tonibabieka** [twbs/icons#1157]
I miss the cut, copy, paste, undo and redo icons.
It would be nice some data add, remove and edit icons.
Thanks
Tony

**Comment by korki43** [comment]
What icons do you expect for cut, copy, paste, undo and redo?

I think these (already existing icons) are recognizable:
- cut: `scissors`
- copy: `clipboard`
- paste: `clipboard-plus`
- undo/redo: some arrow to the left or right

You can search for icons in the documentation (https://icons.getbootstrap.com/). For explicit undo and redo icons see #909.

**Comment by mdo** [comment]
Semi-duplicate of #909. Rest is covered by other options as mentioned above.
