### ISSUE TITLE
How to find correspoding "Unicode HTML Entity" value?

### ISSUE THREAD

**Issue by balintn22** [twbs/icons#1161]
Hi,
I'd like to use Bootstrap icons in my Xamarin app. The method I found requires the "Unicode HTML Entity", the hex code of the unicode character.
If I go to tis page https://icons.getbootstrap.com/ I can find an icon I need, but can't see the corresponding code, not even when inspecting page source.
Someone suggested finding the codes here https://github.com/twbs/icons/blob/main/font/bootstrap-icons.css
However, when I use hex values taken from bootstrap-icons.css, Xamarin doesn't display the expected icon.
An example I tested is 
    .bi-plus-circle-fill::before { content: "\f4f9"; }
that shows as an unknown character (empty square).
Another example is 
    .bi-zoom-in::before { content: "\f62c"; }
(used in Xamarin as &#xf62c;) also shows as an unknown character (empty square).
However, if I take codes from this page https://glyphicons.bootstrapcheatsheets.com/#, they display correctly, i.e. 
    .glyphicon-glyphicon-zoom-in, code &#xe015;
it does display a magnifier glass with a plus as expected.

Is it that the font is not installed correctly?
Or do I need to find the codes some other way?

**Comment by balintn22** [comment]
Installing the font on Windows and finding characters in Character map does help, but it doesn't have the same glyphs as on the page https://icons.getbootstrap.com/

**Comment by balintn22** [comment]
So it seems the font file I had was wrong/old.
I downlaoaded the font files from the v1.7.2 release, converted bootstrap-icons.woff to .ttf and now I'm getting glyphs matching the codes in https://icons.getbootstrap.com/.

**Comment by korki43** [comment]
Seems like you already fixed your main problem. To address the question in the title: Currently the best way to find the code points is to search in the `bootstrap-icons.css` file. There is an open PR that'll add code points to the docs (#1149).

Please also note that glyphicons.bootstrapcheatsheets.com is not provided by twbs/bootstrap.

**Comment by balintn22** [comment]
Thanks for the answer.
For anyone's benefit, I captured the steps I took here: https://stackoverflow.com/questions/70586555/how-to-display-bootstrap-icons-in-xamarin/70586556#70586556
