### ISSUE TITLE
Minified SVGs

### ISSUE THREAD

**Issue by inwardmovement** [twbs/icons#1179]
Having minified SVGs out of the box would be practical, as whitespaces create issues in HTML.

**Comment by mdo** [comment]
Do you have an example of issues created by the nested formatting of the HTML inside the SVGs? I've not see any problems myself.

**Comment by inwardmovement** [comment]
The problem was coming from reset styles that display SVGs as block, we can close this (and we can still minify in Hugo with `| minify` if needed).
