### ISSUE TITLE
Remove spacing inside SVGs

### ISSUE THREAD

**Issue by inwardmovement** [twbs/icons#121]
So that we can properly set spacing around SVGs with CSS (otherwise we have to figure out the spacing inside the SVGs and take it into account when applying margins/paddings).

**Comment by mdo** [comment]
Bulk of this was tackled in Alpha 3 when I resized the `viewBox`, and I'm unsure about removing more and making the icons all different sizes. That makes it more difficult to normalize the sizing between each icon. Plus, all the icon sizing and SVG optimization is scripted, so handling variable dimensions makes that more difficult, too.

**Comment by inwardmovement** [comment]
> Bulk of this was tackled in Alpha 3 w
Indeed
