### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by PanderMusubi** [twbs/icons#1217]
Artwork:
- https://gitlab.com/fdroid/artwork/-/blob/master/fdroid-logo-2015/default-app.svg
- https://gitlab.com/fdroid/artwork/-/blob/master/fdroid-logo-2015/default_notification.svg

License:
- https://gitlab.com/fdroid/artwork/-/tree/master/fdroid-logo-2015#license

See also:
- https://github.com/twbs/icons/issues/1175
- https://github.com/twbs/icons/issues/905

**Comment by mdo** [comment]
Not sure what this is, I'll pass on including it for now.

**Comment by PanderMusubi** [comment]
It is alternate app store to Google Play with only FOSS apps, see https://en.wikipedia.org/wiki/F-Droid
