### ISSUE TITLE
Tools Icon Cutoff

### ISSUE THREAD

**Issue by XmlmXmlmX** [twbs/icons#1226]
The screwdriver handle in the tool icon has two truncated edges:

![image](https://user-images.githubusercontent.com/677165/154301246-8361fbe9-044f-4456-bba8-b08c42ad2f20.png)

**Comment by XmlmXmlmX** [comment]
Here is a fixed version:
https://www.figma.com/file/1FGQIMku3WBD3vsYHJ8lGp/Bootstrap-Icon-Override%3A-Tools?node-id=0%3A16

**Comment by mdo** [comment]
Fixed by #1311
