### ISSUE TITLE
`x-lg` rendered incorrectly

### ISSUE THREAD

**Issue by rin4046** [twbs/icons#1238]
https://github.com/twbs/icons/issues/1062 This issue has not been fixed and the bug still shows in Bootstrap Icons v1.8.1.

<img width="595" alt="スクリーンショット 2022-02-26 19 03 51" src="https://user-images.githubusercontent.com/72665456/155839217-b685a6ef-1535-4e7c-89e3-ea42b99202b4.png">

**Comment by mdo** [comment]
Fixed by #1311
