### ISSUE TITLE
Ubuntu Icon

### ISSUE THREAD

**Issue by Hetarth02** [twbs/icons#1245]
Would be helpful to have an icon for Ubuntu OS.
For Reference,
![image](https://user-images.githubusercontent.com/80420115/156346960-88137f16-af3b-420e-8e39-e1a9edb8ca52.png)

**Comment by PanderMusubi** [comment]
The icon https://icons.getbootstrap.com/icons/ubuntu/ is not looking like the Ubuntu logo, while other brand logos are used mostly identical. Is there a reason why this is altered so much?

**Comment by mdo** [comment]
- https://canonical.com/blog/a-new-look-for-the-circle-of-friends
- https://news.itsfoss.com/ubuntu-new-logo/

**Comment by PanderMusubi** [comment]
Ah, thanks!
