### ISSUE TITLE
bi-windows not showing, adding css unicode as :before shows wrong

### ISSUE THREAD

**Issue by maxgx** [twbs/icons#1248]
i'm including BI through CND: https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css

i'm trying to display Windows' logo using <i class="bi bi-windows"></i> but there's no output (other icons are working fine).

if i try adding CSS:

.bi-windows:before {
content:'\F65E';
}

i get a G with a cedilla.

**Comment by mdo** [comment]
Windows was added in v1.6.0. You gave to update.

**Comment by maxgx** [comment]
understood, thanks
