### ISSUE TITLE
Rendering icons based on unicode value not working

### ISSUE THREAD

**Issue by dattakugve** [twbs/icons#1266]
Hi  I am trying to display bootstrap icon in <option>  element.  For this I am using below code

```
<!DOCTYPE>
<html>
<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
<body>

<select>
<option>
&#xF1AA;
</option>

</select>
</body>
</html>
```

`"&#xF1AA;"`  is the html code for  border-bottom icon as per the [doc](https://icons.getbootstrap.com/icons/border-bottom/) . But when I use this code in html icon is not rendering.  Did I miss something here?

**Comment by korki43** [comment]
You need to specify the `bootstrap-icons` font manually. The stylesheet only applies the font to `.bi::before`.

Example codepen: https://codepen.io/korki43/pen/KKZdBEy
Also note, that firefox does not support styling `<option>` tags (https://stackoverflow.com/q/39515909).
