### ISSUE TITLE
Migrate from legacy glyphicon

### ISSUE THREAD

**Issue by flibustenet** [twbs/icons#1273]
Hi,

I would like to migrate from old bootstrap 3 glyphicon. I'm looking for a translate table to replace the old name to new name.
Also is it a goal to have all glyphicon translated here ? I'm surprise to don't see `hand-left` `hand-right` for example.

Thx

**Comment by mdo** [comment]
There's no migration guide, they are completely different icon sets. Glyphicons is an external library from Bootstrap, as are these icons.
