### ISSUE TITLE
Update clipboard.js (v2.0.11)

### ISSUE THREAD

**Issue by coliff** [twbs/icons#1274]
clipboard.js has had a few minor releases so could copy and paste it to:
https://github.com/twbs/icons/blob/main/docs/assets/js/vendor/clipboard.min.js

REF: https://github.com/zenorocha/clipboard.js/releases

**Comment by darkworks** [comment]
hmmm interesting i was not aware that bootstrap icons is shipped with clipboard js too . hmmm can u put some light on it how to use it , or by direct calling clipboard js it should awake

**Comment by coliff** [comment]
@darkworks 
Clipboard JS is used on the icons website for copying to the clipboard the icon font and SVG code from the icon pages.
