### ISSUE TITLE
Home assistant icons (Google Home, Alexa) 

### ISSUE THREAD

**Issue by nTamura** [twbs/icons#1292]

**Comment by korki43** [comment]
I think these icons can also be used to show some sort of home assistant:
- [`robot`](https://icons.getbootstrap.com/icons/robot/)
- [`soundwave`](https://github.com/twbs/icons/issues/1289)

If you want to display individual home assistant systems (Google Home, Siri) you can also try using some brand icons.
- [`apple`](https://icons.getbootstrap.com/icons/apple/)
- [`google`](https://icons.getbootstrap.com/icons/google/)
- [`microsoft`](https://icons.getbootstrap.com/icons/microsoft/)

**Comment by mdo** [comment]
Google Home is now Google Nest, with no specific logo as far as I can tell. Alexa I can add.
