### ISSUE TITLE
house-heart Icon Font Displays Standard Version

### ISSUE THREAD

**Issue by kanine** [twbs/icons#1305]
Icons 1.8.1
Browser Chrome / Edge

Using the Icon Font notation for the house-heart icons is displaying the standard version of this icon.

`<i class="bi bi-house-heart-fill"></i> <i class="bi bi-house-heart"></i> `

Have tested with the CDN css and also downloaded the distribution for v.1.8.1

**Comment by mdo** [comment]
Fixed by #1311
