### ISSUE TITLE
Open in Penpot

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/icons#1314]
On the website there is now a "Open in Figma" link.

There could also be a "Open in Penpot" link.

Penpot is a design and prototyping platform meant for cross-domain teams. Penpot is web based and works with SVG.
https://penpot.app/

**Comment by mdo** [comment]
I don't use that app at all and all the icons are hand drawn and published in Figma by me, so I won't be adding this :). Thanks though!

**Comment by vanillajonathan** [comment]
A benefit of having the icons available on Penpot would be that UI / UX designers who use Penpot could use the Bootstrap icons in their UI mockups.
