### ISSUE TITLE
Floppy as Save Icon

### ISSUE THREAD

**Issue by shishirraven** [twbs/icons#1352]
Floppy Icon should also be added for situations where instead of Download actual save is required which updates the work online. 

For example in the web app where I am using bootstrap Icons, its difficult to identify the save button quickly. (Its the cloud upload Icon I had to use)
 
![image](https://user-images.githubusercontent.com/4470383/176593918-e8d462bb-f80a-4975-b823-f123251aa243.png)

Also in the Electron Desktop Apps "Floppy" Save button is more relevant. 
Where the work can be saved on desktop on offline apps. 

There are many similar use cases where "floppy" Save button would help. 

I want to request the bootstrap icon team to add it.

**Comment by mdo** [comment]
Closing as duplicate, which you knew since you commented there, too ;).
