### ISSUE TITLE
bi-translate show Ě on a Samsung phone

### ISSUE THREAD

**Issue by joooKiwi** [twbs/icons#1359]
As simple as it may be, the simple use of the translate svg icon does not show the icon, but a letter Ě instead.

It is as simple as `<i class="bi bi-translate"></i>`
I've test this on the iPhone of a friend and it work fine on this device.

The use of the svg work properly (at least).

This is quite weird to have this precise behaviour.

- Operating system and version (Android)
- Browser and version (Samsung Browser)
- https://codepen.io/joookiwi/pen/gOepMQb

**Comment by mdo** [comment]
This may be a browser support issue, I'm not entirely sure. Do any other icons have this issue for you?

**Comment by joooKiwi** [comment]
I'll create a copepen displaying every icons by CSS and give it a return (with only the ones that don't display).

**Comment by joooKiwi** [comment]
There might be some that I've forgotten, but this is thoses that I found.

Here is every icons: https://codepen.io/joookiwi/pen/YzaXraE
And here is the icons that don't display: https://codepen.io/joookiwi/pen/RwMPxgr

Bellow is the icons (without the bi before),
the character shown on Samsung.
And if it's displayed on Windows.

(Note that the icons were retrieved from the file in Node.js (_bootstrap-icons.css_)
| Icon                       |     Displayed text (on Samsung) | Display on Windows |
|:---------------------------|--------------------------------:|:------------------:|
| 123                        |                               Ŗ |                    |
| cloud-haze-1               |                                 |         No         |
| question-diamond           |                             2/7 |                    |
| question-octagon-fill      |                             3/7 |                    |
| question-octagon           |                             4/7 |                    |
| question-square-fill       |                             5/7 |                    |
| question-square            |                             6/7 |                    |
| rainbow                    |                             2/9 |                    |
| receipt-cutoff             |                             4/9 |                    |
| receipt                    |                             5/9 |                    |
| reception-0                |                             7/9 |                    |
| reception-1                |                             8/9 |                    |
| view-list                  |                               A |                    |
| view-stacked               |                               B |                    |
| vinyl-fill                 |                               C |                    |
| vinyl                      |                               D |                    |
| voicemail                  |                               E |                    |
| volume-down-fill           |                               F |                    |
| volume-down                |                               G |                    |
| volume-mute-fill           |                               H |                    |
| volume-mute                |                               I |                    |
| volume-off-fill            |                               J |                    |
| volume-off                 |                               K |                    |
| volume-up-fill             |                               L |                    |
| volume-up                  |                               M |                    |
| vr                         |                               N |                    |
| wallet-fill                |                               O |                    |
| wallet                     |                               P |                    |
| wallet2                    |                               Q |                    |
| watch                      |                               R |                    |
| water                      |                               S |                    |
| whatsapp                   |                               T |                    |
| wifi-1                     |                               U |                    |
| wifi-2                     |                               V |                    |
| wifi-off                   |                               W |                    |
| wifi                       |                               X |                    |
| wind                       |                               Y |                    |
| window-dock                |                               Z |                    |
| window-sidebar             |                               Æ |                    |
| window                     |                               Ŋ |                    |
| wrench                     |                               Œ |                    |
| x-circle-fill              |                               Ð |                    |
| x-circle                   |                               Ħ |                    |
| x-diamond-fill             |                               Ĳ |                    |
| x-diamond                  |      İ _(Maybe this character)_ |                    |
| x-octagon-fill             |      ɭ _(Maybe this character)_ |                    |
| x-octagon                  |                               Ø |                    |
| x-square-fill              |                               Þ |                    |
| x-square                   |                               Ŧ |                    |
| youtube                    |                                 |                    |
| zoom-in                    |                               & |                    |
| currency-euro              | SS _(Can't find the character)_ |                    |
| currency-exchange          |                               $ |                    |
| currency-pound             |                               € |                    |
| currency-yen               |                               ¢ |                    |
| dash-lg                    |                               £ |                    |
| exclamation-lg             |                               ¥ |                    |
| file-earmark-pdf           |                               ! |                    |
| file-pdf-fill              |                               ? |                    |
| gender-female              |                               ¿ |                    |
| gender-male                |                               ¡ |                    |
| gender-trans               |                               Ă |                    |
| headset-vr                 |                               Ā |                    |
| info-lg                    |                               Ą |                    |
| mastodon                   |                               À |                    |
| messenger                  |                               Á |                    |
| piggy-bank-fill            |                               Â |                    |
| piggy-bank                 |                               Ã |                    |
| pin-map-fill               |                               Ä |                    |
| pin-map                    |                               Å |                    |
| plus-lg                    |                               Ć |                    |
| question-lg                |                               Č |                    |
| recycle                    |                               Ċ |                    |
| reddit                     |                               Ĉ |                    |
| safe-fill                  |                               Ç |                    |
| safe2-fill                 |                               Ď |                    |
| safe2                      |                               Đ |                    |
| sd-card-fill               |                               È |                    |
| sd-card                    |                               É |                    |
| skype                      |                               Ê |                    |
| slash-lg                   |                               Ë |                    |
| translate                  |                         _E + ˇ_ |                    |
| x-lg                       |                               Ė |                    |
| safe                       |                               Ē |                    |
| apple                      |                               Ę |                    |
| microsoft                  |                               Ğ |                    |
| windows                    |                               Ģ |                    |
| behance                    |                               Ě |                    |
| dribbble                   |                               Ġ |                    |
| line                       |                               Ĝ |                    |
| medium                     |                               Ĥ |                    |
| paypal                     |                               Ì |                    |
| pinterest                  |                               Í |                    |
| signal                     |                               Î |                    |
| snapshat                   |                               Ï |                    |
| spotify                    |                               Ī |                    |
| stack-overflow             |                               Į |                    |
| strava                     |                               Ĩ |                    |
| wordpress                  |                               Ĭ |                    |
| vimeo                      |                               Ĵ |                    |
| activity                   |                               Ķ |                    |
| easel2-fill                |                               Ĺ |                    |
| easel2                     |                               Ľ |                    |
| easel3-fill                |                               Ļ |                    |
| easel3                     |                               Ŀ |                    |
| fan                        |                               Ń |                    |
| graph-down-arrow           |                               Ñ |                    |
| graph-up-arrow             |                         _N + ˇ_ |                    |
| hypnotize                  |                               Ņ |                    |
| magic                      |                               Ò |                    |
| person-rolodex             |                               Ó |                    |
| person-video               |                               Ô |                    |
| person-video2              |                               Õ |                    |
| person-video3              |                               Ö |                    |
| person-workspace           |                               Ő |                    |
| radioactive                |                               Ō |                    |
| webcam-fill                |                               Ŏ |                    |
| webcam                     |                               Ŕ |                    |
| yin-yang                   |                               Ř |                    |
| bandaid-fill               |                               Ś |                    |
| bandaid                    |                               Ș |                    |
| bluethooth                 |                               Ş |                    |
| body-text                  |                               Š |                    |
| boombox                    |                               Ŝ |                    |
| boxes                      |                               Ť |                    |
| dpad-fill                  |                               Ţ |                    |
| ear-fill                   |                               Ű |                    |
| ear                        |                               Ù |                    |
| ~~envelope-check-1~~       |                               Ú |         No         |
| envelope-check-fill        |                               Û |                    |
| envelope-check             |                               Ü |                    |
| ~~envelope-dash-1~~        |                               Ū |         No         |
| envelope-dash-fill         |                               Ų |                    |
| envelope-dash              |                               Ů |                    |
| ~~envelope-exclamation-1~~ |                               Ũ |         No         |
| envelope-exclamation-fill  |                               Ŭ |                    |
| envelope-exclamation       |                         _W + `_ |                    |
| envelope-plus-fill         |                         _W + ´_ |                    |
| envelope-plus              |                               Ŵ |                    |
| ~~envelope-slash-1~~       |                         _W + ¨_ |         No         |
| envelope-slash-fill        |                               Ỳ |                    |
| envelope-slash             |                               Ý |                    |
| ~~envelope-x-1~~           |                               Ŷ |         No         |
| envelope-x-fill            |                               Ÿ |                    |
| envelope-x                 |                               Ż |                    |
| explicit-fill              |                               Ź |                    |
| git                        |                               Ž |                    |
| infinity                   |                               % |                    |
| list-columns-reverse       |                               ‰ |                    |
| list-columns               |                               / |                    |
| meta                       |                               \ |                    |
| motorboard-fill            |                               @ |         No         |
| motorboard                 |                               ( |         No         |
| nintendo-switch            |                               ) |                    |
| pc-display-horizontal      |                               { |                    |
| pc-display                 |                               } |                    |
| pc-horizontal              |                               [ |                    |
| pc                         |                               ] |                    |
| playstation                |                               * |                    |
| plus-slash-minus           |                               ‘ |                    |
| projector-fill             |                               ’ |                    |
| projector                  |                               “ |                    |
| qr-code-scan               |                               ” |                    |
| ~~send-exclamation-1~~     |                               □ |         No         |
| ~~terminal-dash-1~~        |                               □ |         No         |
| terminal-dash              |                               , |                    |
| ~~displayport-1~~          |                                 |         No         |
| ssd-fill                   |                               □ |         No         |
| ssd                        |                               □ |         No         |
| ~~filetype-ppt-1~~         |                                 |         No         |
| ~~filetype-xls-1~~         |                               □ |         No         |

**Comment by mdo** [comment]
It sounds like the browser isn't loading the icon font. I don't think there's anything I can do about that though. I'm unaware of icon font browser compatibility honestly. If the fonts don't work, I'd consider the SVGs instead.
