### ISSUE TITLE
Floppy icon for save

### ISSUE THREAD

**Issue by sanjeetchahal** [twbs/icons#1360]
Hi @mdo 

There should be floppy icon to save actions. floppy icon is very eye catchy for the most of the users to find out the save button. because from many past years we are seeing this icon in many softwares. E.g. every windows software still using this icon

![image](https://user-images.githubusercontent.com/50857468/176987715-31122810-ad12-4ea8-a234-46ed3a9d81d7.png)

### **And Google's Product too still using the floppy icon** 

![image](https://user-images.githubusercontent.com/50857468/176987828-2bc4fd57-5f6d-4573-84c6-2a2ff1fbc723.png)

### **I hope you can understand the importance of the floppy icon**

I request you to please provide this icon. 

Thanks

**Comment by mdo** [comment]
This has been answered in other issues.

**Comment by scottkuhl** [comment]
> This has been answered in other issues.

And obviously your users do not agree with you.  People keep opening issues.  Stop being stubborn and just add another icon.

You’re arguments don’t hold up to it being outdated when you use a magnifying glass as search.  That is also outdated, but like the floppy it’s universal.

Just. Make. Another. Icon. Please.
