### ISSUE TITLE
Inconsistent blurriness while using raw SVG icons

### ISSUE THREAD

**Issue by oliverfindl** [twbs/icons#1383]
Hello,

I prototyped my app using this package via CSS font and now I'm optimizing build size, therefore I'm switching to raw SVGs (copied from website, not from this repo). Here is example with 2 icons I'm using ([download](https://github.com/twbs/icons/blob/main/icons/download.svg) and [box-arrow-up-right](https://github.com/twbs/icons/blob/main/icons/box-arrow-up-right.svg)), while first icon in both cases is icon from CSS font and second one is raw SVG. Using default Bootstrap CSS and having same icons side by side, there is noticeable blur on first SVG icon compared to icon from CSS font, while second SVG icon looks more crisp than one from CSS font.

![Screenshot from 2022-07-20 20-38-59](https://user-images.githubusercontent.com/33978096/180062156-44ba683d-9bb8-4f00-91e6-1a7d50ea30d4.png)

SVG icons are styled like this:
```css
svg.bootstrap-svg-icon {
	height: 1em;
	vertical-align: -.125em; /* copied from this repo */
}
```
Tested in Chrome and Firefox under Ubuntu. Screenshot is from Chrome.

Is there any way I can make icons more crisp / less blurry? I would say (in my particular case), icons from CSS font are equally blurry, while SVGs are inconsistent.

Thanks.

**Comment by oliverfindl** [comment]
Update:

It looks this bad on Full HD screens. It looks OK-ish on screens with higher pixel density.

Thanks.

**Comment by mdo** [comment]
Do you have a live demo of the problem I can look at?

**Comment by oliverfindl** [comment]
Hello,

unfortunately no, I don't have an online example, but here is code for simple recreation of it.

```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="https://unpkg.com/bootstrap@5.2.0/dist/css/bootstrap.min.css" />
		<link rel="stylesheet" href="https://unpkg.com/bootstrap-icons@1.9.1/font/bootstrap-icons.css" />
		<title>Document</title>
		<style>
			svg.bootstrap-svg-icon {
				height: 1em;
				vertical-align: -.125em; /* copied from this repo */
			}
		</style>
	</head>
	<body class="bg-light">
		<div class="container p-5">
			<button type="button" class="btn btn-primary">
				<i class="bi bi-download me-1"></i>
				<svg xmlns="http://www.w3.org/2000/svg" class="bootstrap-svg-icon me-1" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
					<path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z" />
					<path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z" />
				</svg>
				Download
			</button>
			<hr />
			<button type="button" class="btn btn-primary">
				<i class="bi bi-box-arrow-up-right me-1"></i>
				<svg xmlns="http://www.w3.org/2000/svg" class="bootstrap-svg-icon me-1" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-up-right" viewBox="0 0 16 16">
					<path fill-rule="evenodd" d="M8.636 3.5a.5.5 0 0 0-.5-.5H1.5A1.5 1.5 0 0 0 0 4.5v10A1.5 1.5 0 0 0 1.5 16h10a1.5 1.5 0 0 0 1.5-1.5V7.864a.5.5 0 0 0-1 0V14.5a.5.5 0 0 1-.5.5h-10a.5.5 0 0 1-.5-.5v-10a.5.5 0 0 1 .5-.5h6.636a.5.5 0 0 0 .5-.5z" />
					<path fill-rule="evenodd" d="M16 .5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h3.793L6.146 9.146a.5.5 0 1 0 .708.708L15 1.707V5.5a.5.5 0 0 0 1 0v-5z" />
				</svg>
				Open
			</button>
		</div>
	</body>
</html>
```

Which looks like this:
![Screenshot from 2022-08-28 20-12-31](https://user-images.githubusercontent.com/33978096/187088863-442132eb-0e70-4d57-9a00-e1845ff7861b.png)

Thanks.

**Comment by mdo** [comment]
Not sure what the issue could be, but I've looked at this repeatedly and don't see any issues on my end. https://codepen.io/emdeoh/pen/KKeddoj
