### ISSUE TITLE
bi-1-circle-fill | Icon not working | Using as font

### ISSUE THREAD

**Issue by Lakro** [twbs/icons#1385]
Hi,

I found following Icon not working when using it by icon-font v1.9.1:

**bi-1-circle-fill**
Used HTML-Code: `<i class="bi bi-1-circle-fill"></i>` 

ERROR IS: 
`only filled circle shows up without number`

Tried with CSS Local + official CDN
In both cases I found following CSS-Code:

```
  .bi-1-circle-fill::before { content: "\f796"; }
```

Same issue when opening `index.html`  
from download package!

Checked on Desktop:
+ Firefox v102
+ Chrome v103

Operating-System: Windows 10 / v21H2

Maybe someone is able to confirm that.

Best Regards
Lakro

--- and big THKs for your wonderfull work here :-)

**Comment by amaurisa-insight** [comment]
This issue is Happening Again:

ERROR IS:
only filled circle shows up without number

.bi-1-circle-fill::before {
    content: "\f796";
}

**Comment by grrinch** [comment]
I confirm - just came across this issue today. Version 1.9.1,

Code:
```html
<i class="bi bi-1-circle-fill"></i>
```

Same with the CSS use:
```css
.my-icon-1-bi {
    font-family: bootstrap-icons;
    font-size: 2rem;
    content: "\F796";
}
```

Expected:
![image](https://user-images.githubusercontent.com/5729796/193860114-abbe5f45-7bcc-4f63-9a25-80f3073b7ba0.png)

Actual result:
![image](https://user-images.githubusercontent.com/5729796/193860319-562d5ec4-f389-4d07-9964-7153883ff439.png)
