### ISSUE TITLE
New Number-Icons | Add Icons with '0' 

### ISSUE THREAD

**Issue by Lakro** [twbs/icons#1386]
Hi,

concerning the new Icons v1.9.1:  
I like the new number-Icons in the different forms.

But what I miss is the Number `0` (Zero)

### Just as nice Feature request:

Simple add a number `0` to the circle- and square-icons.  
With this simple add on we would be able to combine the Icons to every mulitple number as we would need it ... and I am sure the creative people will get some more Ideas to use it ... ;-)

Best regards
Lakro

---- and a big THKs for your wonderfull work here

**Comment by mdo** [comment]
Fixed by #1468.
