### ISSUE TITLE
A bordered "Server" Icon

### ISSUE THREAD

**Issue by simo026q** [twbs/icons#1476]
I would love to see a bordered version of the current [Server Icon](https://icons.getbootstrap.com/icons/server/) like [this icon](https://fontawesome.com/icons/database?s=regular&f=classic) from Font Awesome. That would need the current icon to be renamed "server-fill".

**Note:** _It would be nice if you added "database" to the icon tags - in my book it's a database icon and not a server icon :)_

**Comment by mdo** [comment]
Yes, agreed! Needs some other variants too for plus, minus, etc.

**Comment by mdo** [comment]
Got a whole slew of them coming.

<img width="1321" alt="CleanShot 2022-11-09 at 16 13 21@2x" src="https://user-images.githubusercontent.com/98681/200969129-648fe591-61e0-484c-bcfc-1a4060da9899.png">

**Comment by simo026q** [comment]
> Got a whole slew of them coming.

Looks great!
