### ISSUE TITLE
vcard

### ISSUE THREAD

**Issue by lonix1** [twbs/icons#1477]
A "vcard" icon is useful for contacts, address books, carddav/caldav, etc. The library contains all sorts of similar icons (people, cards) but not a vcard icon, which looks mostly alike in all apps and is familar to users.

Some examples: https://www.google.com/search?q=vcard+icon&tbm=isch

**Comment by denisz1** [comment]
@mdo Yes me too. The repro link show the problem. It is too short against the other icons.

Also, I learn a new word "scrunched", ha!

**Comment by denisz1** [comment]
@lonix1 I did that, look at [this](https://github.com/twbs/icons/issues/1539).
