### ISSUE TITLE
[icon request] Log in/out icons

### ISSUE THREAD

**Issue by septatrix** [twbs/icons#148]
We currently use Bootstrap 3 with Glyphicons but want to update to Bootstrap 4 (and 5 once it comes out) and like the style of the icon set. However there are not Log in/out icons anymore like glyphicons `glyphicon-log-in` or fontawesomes `sign-in-alt` (as well as corresponding logout icons).

**Comment by ffes** [comment]
We use https://icons.getbootstrap.com/icons/box-arrow-in-right/ for sign in. Seems very similar to the icons you request
