### ISSUE TITLE
New person icons filled gear / lock / etc.

### ISSUE THREAD

**Issue by Fewiel** [twbs/icons#1487]
I just tried the new person icons (bi-person-fill-gear/lock/x) but it seems they are rendered incorrectly/filled in the small sub-icons.  

Tested on Windows 10, Chrome, Firefox, Edge. See attached image:  
![image](https://user-images.githubusercontent.com/37041411/201449534-893e0388-5f4f-4908-b4d3-135759c63374.png)  

Also created a test html to reproduce this behavior:

```html
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
	</head>
	<body>
		<i class="bi bi-person-fill-gear"></i>
		<i class="bi bi-person-fill-lock"></i>
		<i class="bi bi-person-fill-x"></i>
	</body>
</html>
```

**Comment by mdo** [comment]
Fixed by #1488.
