### ISSUE TITLE
bi bi-database classes aren't displaying

### ISSUE THREAD

**Issue by shawnnolanjr** [twbs/icons#1496]
Before opening, [search for duplicate or closed issues](https://github.com/twbs/icons/issues?utf8=%E2%9C%93&q=is%3Aissue).

As appropriate, please include:

- Operating system and version: **macOS Ventura 13.0**
- Browser and version: 
-- **Chrome (Version 107.0.5304.110 Official Build x86_64)**
-- **Brave (Version 1.45.123  Chromium: 107.0.5304.110 Official Build x86_64)**
-- **FireFox (107.0 64-bit)**

So I'm using `"bootstrap-icons": "1.10.2",` in my angular project, and all other icons I've been using are working just fine, except for the "database" group of icons. I've tried 3 different types, and they all don't seem to show up for some reason. I've created an empty bootstrap project using the CDN and they show up just fine, but when using the `bootstrap-icons` package, I can't seem to get them to show up. I was able to get them to display using the SVG, so it seems that only `bi bi-database(-*)` classes for some reason aren't displaying them.

Attaching screenshots:
FireFox:
<img width="1385" alt="Screenshot 2022-11-16 at 11 05 34 AM" src="https://user-images.githubusercontent.com/8684308/202272021-a9da3dae-c5d4-4735-8dce-88d9f35d29f8.png">

Chrome:
<img width="1526" alt="Screenshot 2022-11-16 at 11 02 30 AM" src="https://user-images.githubusercontent.com/8684308/202272027-5b9c2bfa-074e-4750-8e1d-7cbfbeeabdf7.png">

**Comment by shawnnolanjr** [comment]
> Does this still happen?

From the last time I tried it, yes.

**Comment by XhmikosR** [comment]
Weird, doesn't make any sense... Works fine here and on our docs as you can see.

You should clean your node_modules folder and reinstall the latest version.
