### ISSUE TITLE
"trash" icon in svg and web font  do not show the same results

### ISSUE THREAD

**Issue by fenbox** [twbs/icons#1500]
Using "trash" icon in svg and web font do not show the same results.
I'm not sure it's a bug.

![image](https://user-images.githubusercontent.com/360618/202653430-08ac269e-e8a3-4276-8e53-6ee77bec385b.png)

- System: macOS 13.0.1
- Browser: Microsoft Edge Version 107.0.1418.52

**Comment by XhmikosR** [comment]
I cannot reproduce on my system. Maybe it was a bug that's been fixed?

**Comment by fenbox** [comment]
No it's not been fixed.

I still can set the trash icon are displayed different on the list page and the details page.

<img width="347" alt="image" src="https://user-images.githubusercontent.com/360618/227701506-a61b9329-480d-4f34-83df-60895a244669.png">

<img width="639" alt="image" src="https://user-images.githubusercontent.com/360618/227701528-0060cce3-1464-4e80-9360-1281901cb263.png">

**Comment by XhmikosR** [comment]
OK I confirmed it. The font icon has this issue. The sprite is fine.
