### ISSUE TITLE
Accessibility: website dark theme

### ISSUE THREAD

**Issue by PositiveUser** [twbs/icons#1509]
Please add a switch to toggle theme.
Place it in the navbar so it can be seen and interacted at all times.

**Comment by korki43** [comment]
This would require changing the classname of every element or messing with Bootstraps internal variables. See https://github.com/twbs/bootstrap/issues/37549 for dark mode support in Bootstrap CSS.

**Comment by Dhananjay-12** [comment]
hi @PositiveUser  are there any issues i could work on.

**Comment by PositiveUser** [comment]
> hi @PositiveUser are there any issues i could work on.

I prefer dark theme. I need something that toggles the theme of website. Moreover, dark theme will help preview how the icons would look like in a dark theme.

**Comment by Dhananjay-12** [comment]
> This would require changing the classname of every element or messing with Bootstraps internal variables. See [twbs/bootstrap#37549](https://github.com/twbs/bootstrap/issues/37549) for dark mode support in Bootstrap CSS.

Is this true??
If not then I want to work on it 😄😄

**Comment by korki43** [comment]
Dark mode was added in #1544 after the release of Bootstrap v5.3.1-alpha1 which introduced dark & light modes to Bootstrap.
