### ISSUE TITLE
icon does not appear

### ISSUE THREAD

**Issue by maritogaleano** [twbs/icons#1523]
When using some icons in bootstrap 5 they do not appear, example:

```
**<li>
      <a class="dropdown-item" href="#"> <i class="bi bi-person-lock"></i> Cambiar Clave</a>
</li>**
```

![image](https://user-images.githubusercontent.com/57814047/204556940-db4c3bc2-6068-48c4-a69a-9057d14a7ce6.png)

I've even upgraded the version, but the error still persists

![image](https://user-images.githubusercontent.com/57814047/204556580-231ae039-ef41-42b6-81df-7b8707aa61e8.png)

**This is what I currently have installed:**

"@angular/animations": "~13.3.0",
    "@angular/common": "~13.3.0",
    "@angular/compiler": "~13.3.0",
    "@angular/core": "~13.3.0",
    "@angular/forms": "~13.3.0",
    "@angular/localize": "~13.3.0",
    "@angular/platform-browser": "~13.3.0",
    "@angular/platform-browser-dynamic": "~13.3.0",
    "@angular/router": "~13.3.0",
    "@ng-bootstrap/ng-bootstrap": "^12.1.2",
    "@popperjs/core": "^2.11.5",
    "bootstrap": "^5.2.0-beta1",
    "bootstrap-icons": "^1.8.3",
    "ngx-mask": "^13.1.15",
    "ngx-pagination": "^6.0.2",
    "rxjs": "~7.5.0",
    "sweetalert2": "^11.4.18",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"

**Comment by mdo** [comment]
Your package version is most likely out of date.
