### ISSUE TITLE
Aliases for caret-like icons

### ISSUE THREAD

**Issue by lonix1** [twbs/icons#1530]
I was looking for a "caret" pointing up and down. The sort used for "collapsing" and "expanding" content. I was about to lodge an icon request, then realised what I want already exists, but under a different name ("chevron").

These up/down/left/right icons are similar, so should have aliases to match **in the search page**:
- carets
- chevrons
- triangles
- angles (how they're named in FA - personally I dislike that, but might increase discoverability for other users)

**Comment by korki43** [comment]
We now have caret and chevron icons so I don't think it would be useful to add those tags anymore.
