### ISSUE TITLE
Missing icon which is available in FA6

### ISSUE THREAD

**Issue by gtbu** [twbs/icons#1552]
I miss a login-icon and a sitemap-icon

**Comment by korki43** [comment]
There are a lot of existing icons which you can use:

Login:
- https://icons.getbootstrap.com/icons/box-arrow-in-right/
- https://icons.getbootstrap.com/icons/door-open/
- https://icons.getbootstrap.com/icons/unlock/
- https://icons.getbootstrap.com/icons/person-circle/

Sitemap:
- https://icons.getbootstrap.com/icons/list-ul/
- https://icons.getbootstrap.com/icons/list-nested/
