### ISSUE TITLE
.bi and .bi-icon-name classes on svg

### ISSUE THREAD

**Issue by 2acode** [twbs/icons#1553]
I just have some doubts:
- why are "bi" and "bi-icon-name" classes used in all svgs? With and without I see no difference considering that you can insert it directly into the code without even importing the css. Do they have a specific purpose and is it mandatory / useful to use them even with svgs?
- why are both classes "bi bi-icon-name" used in the examples when in the css there are already "[class^" and "[class*]" which make the use of class "bi" useless? Should "bi-icon-name" already suffice in these cases?

Thank you

**Comment by mdo** [comment]
They're so you can easily style the SVGs if you so choose. The CSS can likely be deduped—the base class `.bi` is a faster, more performant selector.
