### ISSUE TITLE
Sprite not working in download version and readme is missing

### ISSUE THREAD

**Issue by danielniccoli** [twbs/icons#1562]
I'm using the download version (1.10.3).

The ZIP file does not include a readme. (https://github.com/twbs/icons/releases/tag/v1.10.3)

![grafik](https://user-images.githubusercontent.com/2971735/212415734-ab191dd4-02c0-4239-b3be-1a25a925aa62.png)

And the sprite variant does not work.

![grafik](https://user-images.githubusercontent.com/2971735/212416025-28a56ee4-be95-4560-b2e2-d809796e2971.png)

```
<svg class="bi" width="32" height="32" fill="currentColor">
  <use xlink:href="bootstrap-icons.svg#heart-fill"/>
</svg>
<svg class="bi" width="32" height="32" fill="currentColor">
  <use xlink:href="bootstrap-icons.svg#toggles"/>
</svg>
<svg class="bi" width="32" height="32" fill="currentColor">
  <use xlink:href="bootstrap-icons.svg#shop"/>
</svg>
```

Error is: GET http://127.0.0.1:5500/bootstrap-icons.svg

**Comment by XhmikosR** [comment]
How are running that server? because the zip file does include the sprite.
