### ISSUE TITLE
Icon: person-check fetches person-check-fill

### ISSUE THREAD

**Issue by VenomXL** [twbs/icons#1568]
`<i class="bi bi-person-check"></i>` 
Fetches 
![fetched](https://user-images.githubusercontent.com/102675524/213847552-e89442fa-bb22-4ea6-a100-13bf886978ad.png)
Instead of 
![correct image](https://user-images.githubusercontent.com/102675524/213847573-00ee2a26-17c6-470a-b29e-4fa617be3c3b.png)

**Comment by XhmikosR** [comment]
Works fine on our docs.
