### ISSUE TITLE
SVG Icon look blurry after export from Figma File

### ISSUE THREAD

**Issue by imprathamesh** [twbs/icons#1572]
Hello,
I got figma file of icons from figma community, I tried to export the icon x-diamond 24px. After putting into html It get blurry or but same icon i use it from bootstrap icons lib it looks sharp, why ? Im missing some tweak after exporting

**Comment by imprathamesh** [comment]
https://github.com/twbs/icons/issues/1383 this same problem I am getting

**Comment by mdo** [comment]
Could be you're increasing the icons size by only 50% instead of even increments of 100%? Width of icon strokes are 1px in most cases, so 24px would be 1.5px. Just guessing though, as we obviously don't see any issues on our end 🤔
