### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by matrndev** [twbs/icons#1589]
Hey, I'd like to use Boostrap Icons on my website. Do I need to disclose that I use Bootstrap Icons in the footer of my website?

**Comment by tjkuson** [comment]
This is from the [licence](LICENSE.md) file.

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

I understand this to mean that you should include a copy of the Bootstrap Icons licence (and thus attribution) somewhere on your website.

**Disclaimer: this is not legal advice, and I am not a lawyer!**

**Comment by emmahsax** [comment]
OR, if your website has a license file, then you could just include the Bootstrap Icons file in that file. Alternatively, just include links to the open source license file (if you don't want to have lots of copy-paste everywhere).

**I am also not a lawyer**

**Comment by mdo** [comment]
I am also not a lawyer 😂, but as the creator and maintainer of this project, I can answer that.

No, you don't. If you want to, go for it! But otherwise including the license file in the appropriate location of your source code is what's typically required.
