### ISSUE TITLE
Dear bootstrap icons designers.Numbers 10 and 11 and 12

### ISSUE THREAD

**Issue by y377** [twbs/icons#1592]
Currently already 1 to 9, looking forward to 10 and 11 and 12 to make up the perfect month icon, I used bootstrap to make the timeline because without 10 and 11 and 12, they are two separate icons that look very disjointed as follows.
Dear bootstrap icons designers.
I have a request, can you design these three icons first, because I am writing a Jekyll theme (open source), and Jekyll is using liquid template syntax, so when it comes to the number 0, it is difficult to handle, which in turn will affect the judgment style
**thank very much**

![image](https://user-images.githubusercontent.com/58632405/219344213-0ea3b5e7-0f86-4c43-95b5-b675bfc94303.png)

## Expected results
![image](https://user-images.githubusercontent.com/58632405/220236986-df7f07db-e223-474d-9851-8d2c983d3bda.png)
![image](https://user-images.githubusercontent.com/58632405/220237055-8e70a5f0-d138-4feb-960a-6b99dbc492f2.png)
![image](https://user-images.githubusercontent.com/58632405/220237095-eb56f5bd-bef7-4b2d-b07b-bb0bd53692c6.png)

**Comment by y377** [comment]
**Friends, put me up, so that the designer can see my request**

**Comment by mdo** [comment]
I don't see too much value in adding these ourselves. It'd require text set in a different size, and/or redrawing the other icons to have smaller text to match. It's unclear where we'd stop beyond 12 as well—why not 14 for a week, or 31 for a month? I get the calendar use case, but if you need that flexibility of single and double digits, you could create this in HTML and CSS pretty easily and have more options.

**Comment by y377** [comment]
you are funny
