### ISSUE TITLE
Floppy disk save

### ISSUE THREAD

**Issue by hellwaiver** [twbs/icons#1599]
I can't find an icon that is suitable to be used as a save icon. I've seen the existing save icons but they are inadequate (they look like download buttons). I noticed there's been a few requests for this shot down already, but I honestly don't understand why it can't be added. Users expect to see a floppy disk icon when saving.

**Comment by tminei** [comment]
I think the era of using the floppy disk as a save icon is over. I might suggest you use synonymous images for this purpose:
![image](https://user-images.githubusercontent.com/34548743/224047568-7e96d89e-efc9-48b3-8d2c-457178b0d179.png)
By the way - fun fact, fontawesome is not using the correct 3.5" floppy disk icon - on the icon we see the back of the floppy disk and therefore the bevelled corner should be at the top left:
![image](https://user-images.githubusercontent.com/34548743/224049435-3e60a248-c427-46f6-a7ef-35bb9e55d5b8.png)

![2023-03-09_16-06](https://user-images.githubusercontent.com/34548743/224049868-b765275a-043d-4a0f-84b6-1a35cc49ca02.png)

**Comment by tminei** [comment]
Maybe you need some from theres:
![image](https://user-images.githubusercontent.com/34548743/224300123-3a7a2bfd-55d5-47a5-ac9b-d02f9c402147.png)
![image](https://user-images.githubusercontent.com/34548743/224300245-3d9786ed-b890-4bb4-ba3d-5d04c75cbe30.png)
By the way, you always can use a svg as icon in your project:
`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M5 3a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V5.5L18.5 3H17v6a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1V3H5m7 1v5h3V4h-3m-5 8h10a1 1 0 0 1 1 1v6H6v-6a1 1 0 0 1 1-1Z"/></svg>`
![image](https://user-images.githubusercontent.com/34548743/224300444-1b21dbfd-ed1e-45cb-bd70-64d506903654.png)

**Comment by tminei** [comment]
> What popular software uses downwards arrows to indicate saving?
I think that for client-server applications, the floppy disk icon does not make it clear whether the file should be saved to the server or the client, hence the under-,upper-score arrows

**Comment by RobineSavert** [comment]
For UI purposes use, the "bookmark" icon. This is modern, globally recognized "Save" icon:


![image](https://user-images.githubusercontent.com/9988362/227579686-eb95eb14-f6bb-4177-9c0a-061d5e7349be.png)

**Comment by hellwaiver** [comment]
Not convinced by that. A bookmark is used to signify saving a place for something, not to save your own changes.

**Comment by mdo** [comment]
Allow me to lay it to rest: I'll add the floppy disk in a future update. I'll also comment more on the whys and the community's response. But figured it'd be helpful to at least share this short update :).

**Comment by RobineSavert** [comment]
> Not convinced by that. A bookmark is used to signify saving a place for something, not to save your own changes.

Im just going to leave this here:

[UX Movement Save Icon](https://uxmovement.medium.com/why-the-floppy-disk-icon-for-save-must-die-166fa5baa693)

**Comment by korki43** [comment]
duplicate of #1440

**Comment by JustCallMeAD** [comment]
I am all for having a floppy disk icon that can be used as a save icon, as I can see why people would still like to use it. 

Another option, for anyone that is interested, is to use a tick / check icon for save and an x icon for cancel.

https://icons.getbootstrap.com/icons/check/
https://icons.getbootstrap.com/icons/x/

**Comment by mdo** [comment]
Added in #1792.
