### ISSUE TITLE
ARXivar is a quite diffused document management platform in Italy

### ISSUE THREAD

**Issue by andrea-colleoni** [twbs/icons#1608]
ARXivar is a quite diffused document management platform in Italy   
We have the SVG logo, but it should be useful to have an icon in the icon set.

![Icona ARXivar](https://user-images.githubusercontent.com/2152787/224645524-4666db9c-03b8-4f47-946a-db4045c6cfef.svg)

**Comment by korki43** [comment]
I don't think it is necessary to create a dedicated icon for this brand. The logo is already really minimalistic so you can use it next to Bootstrap icons without changing anything.
