### ISSUE TITLE
Missing tags and categories for icons

### ISSUE THREAD

**Issue by AnimeAllstar** [twbs/icons#1616]
Docs missing tags and categories for icons:

Folder: https://github.com/twbs/icons/tree/main/docs/content/icons

Icons missing categories:
- [ ] alexa
- [ ] boxes
- [ ] chevron-expand
- [ ] filetype-ppt
- [ ] filetype-xls
- [ ] pass
- [ ] pass-fill
- [ ] vinyl

Icons missing tags:
- [ ] alexa
- [ ] chevron-expand
- [ ] explicit-fill
- [ ] explicit
- [ ] filetype-ppt
- [ ] filetype-xls
- [ ] pass-fill
- [ ] pass
- [ ] patch-minus-fill
- [ ] patch-minus
- [ ] patch-plus-fill
- [ ] patch-plus
- [ ] patch-question-fill
- [ ] patch-question
- [ ] scooter
- [ ] sina-weibo
- [ ] tencent-qq
- [ ] tiktok
- [ ] usb-plug-fill
- [ ] usb-symbol
- [ ] usb
- [ ] usb-plug
- [ ] wikipedia

I could try an open a PR for this, but I wasn't sure if tags and categories for these icons were left empty for a reason or if there are generated automatically somehow.

**Comment by XhmikosR** [comment]
My guess is that someone missed those, so feel free to submit a PR.
