### ISSUE TITLE
Icon request for sorting arrows on data table

### ISSUE THREAD

**Issue by RobineSavert** [twbs/icons#1659]
In our old project, we use a data table with sorting function. The icon in the column headers are 2 chevrons on top of eachother, but Bootstrap Icon set does not contain something like this. Is it possible to add? They look like this:

![image](https://user-images.githubusercontent.com/9988362/227966904-0c6234e2-4c14-4f74-8db7-e7fe28f2aa03.png)

**Comment by korki43** [comment]
Have a look at https://icons.getbootstrap.com/icons/chevron-expand/

Isn't this exactly what you're looking for? ;-)

**Comment by RobineSavert** [comment]
> Have a look at https://icons.getbootstrap.com/icons/chevron-expand/
> 
> Isn't this exactly what you're looking for? ;-)

Yes, this is perfect, thanks!
