### ISSUE TITLE
[icon request] translations/languages icon

### ISSUE THREAD

**Issue by inwardmovement** [twbs/icons#168]
A _translations_ or _languages_ icon would be useful for languages dropdowns, like :

![image](https://user-images.githubusercontent.com/9438102/86528557-7c287c80-bea9-11ea-88f4-a41a32c3b473.png) ![image](https://user-images.githubusercontent.com/9438102/86528543-5f8c4480-bea9-11ea-9903-2d7224754dd8.png)

**Comment by guoyunhe** [comment]
I also need this icon!

**Comment by ayoubkhan558** [comment]
yes we need this

**Comment by micschk** [comment]
Language icon would be nice!
