### ISSUE TITLE
Icon Requests: Platforms

### ISSUE THREAD

**Issue by trymeouteh** [twbs/icons#1690]
Please create icons for the following platforms

Lemmy - Federated Reddit Alternative
Plemora - Federated Twitter Alternative
Peertube - Federated YouTube Alternative
LBRY - Decentralized YouTube Alternative
Plume - Federated Blogging Alternative
Manyverse - P2P Social Media
Matrix - Federated Messanger
SimpleX - Decentralized Messanger
Gitea - Github Alternative
Forgejo - Github Alternative

**Comment by shaunroselt** [comment]
+1 for Gitea

I need a Gitea icon. For now, I'm using the normal `git` icon, but would be nice to have an actual Gitea logo icon.

This is their logo:
![Gitea Logo](https://github.com/twbs/icons/assets/5418178/222efc9c-3cc6-49cd-ac27-723466c1ceb9)
