### ISSUE TITLE
Icon Request: Codeberg

### ISSUE THREAD

**Issue by websick-dev** [twbs/icons#1699]
Official Codeberg SVG icons can be found here: https://codeberg.org/Codeberg/Design/src/branch/main/logo/icon/svg

**Comment by mdo** [comment]
Going to pass on adding this brand, thanks.

**Comment by TheDragon44** [comment]
Can you please explain the reason for rejecting it? 

Accepting all other git forges, except Codeberg seems.... Bizzare, at a minimum

**Comment by dcnorris** [comment]
Would you be open to reconsidering that decision at this time?
