### ISSUE TITLE
Icon request: paw print 

### ISSUE THREAD

**Issue by ChrisT44** [twbs/icons#1703]
I could really do with an icon to represent animals - ideally something generic like a paw print.

**Comment by tjkuson** [comment]
Hi! I think this is a duplicate. #1318

**Comment by ChrisT44** [comment]
Ok not planned but can we request it? I need it and have seen other posts requesting the same.

**Comment by Aworldc** [comment]
I think it was just closed because it's a duplicate. See the link in the comment above yours.
