### ISSUE TITLE
`*-half` icons should have consistent filled side

### ISSUE THREAD

**Issue by tmorehouse** [twbs/icons#171]
All of the `fill`'ed versions of icons should be consistently filled on the left side.

Some filled Icons have the right side filled, where as the majority are left filled (ie. diamond, circle, triangle and square should be left filled)

Perhaps all `*-half` fill icons should be filled on the left, and maybe have an alt `*-half-right` version filled on the right?

Use-case example:  ratings widget which shows `#.5` rating.  LTR would use the default half icon (`*-half`), while RTL could use the `*-fill-right` version). Typically users would want the star icons, but may use other icons for this purpose.

/cc @mdo 

(context: working on a rating component that allows users to select their base icon, and noticed the inconsistent half side being filled)

**Comment by tmorehouse** [comment]
Example:

![image](https://user-images.githubusercontent.com/2781561/77280814-20443a00-6ca4-11ea-91d8-c90e6eacd88b.png)

**Comment by mdo** [comment]
Have fixed this in Figma and will re-export for the the next alpha. Good call.

**Comment by tmorehouse** [comment]
@mdo It looks like the shapes still have inconsistent sides filled in (based n the deploy preview):

![image](https://user-images.githubusercontent.com/2781561/82382782-fb014d00-9a02-11ea-9672-b591c073dbf0.png)

Book, circle, diamond, square and triangle should probably be filled on the left side.

**Comment by mdo** [comment]
Addressed in #249. I never actually exported the new half icons, sorry! And I've added book to the mix, too, since I had previously only done the shapes.

![Screen Shot 2020-05-19 at 3 21 40 PM](https://user-images.githubusercontent.com/98681/82384324-83bcc080-99e4-11ea-9866-a93b5a91c1c9.png)

**Comment by tmorehouse** [comment]
No prob ;-)
