### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by e-mccormick** [twbs/icons#1714]
While looking at the icon previews, you use the metadata in icons-<ver>\docs\content\icons. So for 0 circle you have 0-circle.md which contains: 
```
---
title: 0 circle
categories:
  - Shapes
tags:
  - number
  - numeral
---
```

What I propose is that future versions actually compile that into the SVG metadata. I opened a few of the SVG files and their metadata is blank. You have all this metadata on the code side, so why not add it to the images?

**Comment by mdo** [comment]
Not sure why we'd do that?
