### ISSUE TITLE
The degree of recognition is not high,Hand thumbs

### ISSUE THREAD

**Issue by ZhangChengLin** [twbs/icons#1719]
https://icons.getbootstrap.com/icons/hand-thumbs-up-fill/
https://icons.getbootstrap.com/icons/hand-thumbs-up/
https://icons.getbootstrap.com/icons/hand-thumbs-down-fill/
https://icons.getbootstrap.com/icons/hand-thumbs-down/

https://icons.getbootstrap.com/icons/hand-thumbs-up/

The degree of recognition is not high, what does it look like when it is a small icon, is it a wine bottle?

**Comment by mdo** [comment]
Tagging for a future update to potentially revisit the base icon.
