### ISSUE TITLE
Icon Request: Flash

### ISSUE THREAD

**Issue by KarloX2** [twbs/icons#1742]
Please add a Flash icon

**Comment by mdo** [comment]
As in Adobe Flash? Isn't that dead?

**Comment by KarloX2** [comment]
I don't mean the product icon, but a just a flash like [here](https://icon-icons.com/de/symbol/flash/84029) (outlined & filled)

**Comment by mdo** [comment]
We have lightning icons :)

**Comment by KarloX2** [comment]
Ah ok, thanks. If there's something like aliases for searching you may consider to add "flash" to that icon.

**Comment by mdo** [comment]
> Ah ok, thanks. If there's something like aliases for searching you may consider to add "flash" to that icon.

Yup, there are. Feel free to open a pull request to add that to them :).
