### ISSUE TITLE
Status of the repository?

### ISSUE THREAD

**Issue by mrdrogdrog** [twbs/icons#1743]
Hello,

4 months ago I opened several pull requests for icons that are missing and are needed in my project(s).
Nothing has happened since then.

Is this project dead/unmaintained?😟

**Comment by ddudda174** [comment]
I guess mdo was busy getting Bootstrap v5.3 out of Alpha/Beta status and is now probably busy improving and updating it. Guess we have to wait here a bit ;)

**Comment by mdo** [comment]
I basically add all the icons myself, sorry for leaving you hanging! Have another update coming, just been busy :).

**Comment by mrdrogdrog** [comment]
@mdo no stress, take your time. I just wanted to know if I need to fork/look for an alternative  😅
Happy to hear that you're still there. ❤️
