### ISSUE TITLE
Font - path in .min.css

### ISSUE THREAD

**Issue by gtbu** [twbs/icons#1745]
in bootstrap-icons.scss the path is $bootstrap-icons-font-dir: "./fonts" !default;
Compiled it is  
@font-face {
	 font-display: block;
	 font-family: "bootstrap-icons";
	 src: url("./fonts/bootstrap-icons.woff2?24e3eb84d0bcaf83d77f904c78ac1f47") format("woff2"), url("./fonts/bootstrap-icons.woff?24e3eb84d0bcaf83d77f904c78ac1f47") format("woff");
}
 ..................................................................
similar in  bootstrap-icons.css  ..... src: url("./fonts/bootstrap-icons.woff2?1fa40e8900654d2863d011707b9fb6f2") format("woff2"),....
...............................................................................................................................
but in in bootstrap-icons.min.css  the path is 
 .....src:url("fonts/bootstrap-icons.woff2?1fa40e8900654d2863d011707b9fb6f2") ****
The ./ is missing - which can cause path-problems

**Comment by mdo** [comment]
I believe this is the result of the minifier, and since your comment suggests this _could_ be a bug and isn't actually one for you, going to close out for now.
