### ISSUE TITLE
Suggestion: Set icon height/width to 1em, then use font-size to size icons

### ISSUE THREAD

**Issue by saturdaywalkers** [twbs/icons#1749]
If you set SVG width and height to 1em...
``` .icon { display:inline-block; height:1em; width:1em }```

Then you can size icons using font-size, e.g., an icon inside an h1 tag will be h1 font-size.

I think Font Awesome use this approach.

**Comment by mdo** [comment]
You can do that with the font version. We'll keep it as pixel dimensions for the SVG for now.
