### ISSUE TITLE
Add Icon for Rock Scaler Mining Machine

### ISSUE THREAD

**Issue by shaunroselt** [twbs/icons#1767]
Please add an icon for a `Rock Scaler` Vehicle.

The icon can look something like this:

![Rock Scaler Icon](https://github.com/twbs/icons/assets/5418178/e4cc765f-b30d-47a3-b091-f9c3653cd8a7)

This is how they look in real life:
![Rock Scaler Mining Machine](https://github.com/twbs/icons/assets/5418178/f646debb-2e68-4fc0-ae24-0845fd7b4267)
![Rock Scaler Mining Machine](https://github.com/twbs/icons/assets/5418178/b36d1a5a-94ec-48dd-845b-79206a421b64)
![Rock Scaler Mining Machine](https://github.com/twbs/icons/assets/5418178/2888c15d-0672-43ed-ab16-7fbda8c0cd2b)
![Rock Scaler Mining Machine](https://github.com/twbs/icons/assets/5418178/8d2a7447-8776-49d0-bedd-4ba979473bee)

**Comment by mdo** [comment]
Sorry, I don't see myself making that kind of icon in a 16x16 pixel grid.

**Comment by shaunroselt** [comment]
> Sorry, I don't see myself making that kind of icon in a 16x16 pixel grid.

Are all the icons 16x16?

**Comment by mdo** [comment]
Yes
