### ISSUE TITLE
Floppy disk for save action.

### ISSUE THREAD

**Issue by urza** [twbs/icons#1777]
I don't want "download" icon on "save". I need "save current work" which is represented by floppy disk, not "down arrow". Please add this important and crucial icon.

**Comment by Aworldc** [comment]
Yes. please.

**Comment by shaunroselt** [comment]
This is a possible duplicate of https://github.com/twbs/icons/issues/1599

**Comment by Aworldc** [comment]
> This is a possible duplicate of #1599

Yes, but no one has taken action yet.

**Comment by shaunroselt** [comment]
@mdo "closed this as not planned" ???

**Comment by mdo** [comment]
As mentioned, it’s a duplicate issue. And GitHub has no mark as dupe option.
