### ISSUE TITLE
Twitter rebranded

### ISSUE THREAD

**Issue by pmalicki11** [twbs/icons#1778]
According to twitter rebranding to x this new icon will be needed.

**Comment by Aworldc** [comment]
can we please keep the old Twitter logo as well?

**Comment by KGRlabs** [comment]
I was expecting Bootstrap to make that a top priority. After all, Bootstrap *is* made by Twitter.

**Comment by mdo** [comment]
> I was expecting Bootstrap to make that a top priority. After all, Bootstrap *is* made by Twitter.

It is in fact not made by Twitter.

**Comment by KGRlabs** [comment]
Well then why does it say “from Twitter” on the v2.0.2 homepage? Was the project sold without me noticing?

**Comment by mdo** [comment]
> Well then why does it say “from Twitter” on the v2.0.2 homepage? Was the project sold without me noticing?

We made it while at Twitter, and take it with us when we quit over a decade ago :).

**Comment by kalebjdavenport** [comment]
I apologize on behalf of society, but I'm upvoting this request as well 🤣

**Comment by fulldecent** [comment]
The latest image is here:

https://github.com/twbs/icons/pull/1792/files?short_path=13363f0#diff-13363f01cff5747871cdea584fbec3ca9789b0f4cb52689116c1694a0c430cab

You can follow there to watch the progress on merging and releasing this issue.
