### ISSUE TITLE
v1.11.0 contains the v1.10.5 files in the icons/font folder

### ISSUE THREAD

**Issue by spasibych** [twbs/icons#1807]
v1.11.0 contains v1.10.5 files in the icons/font folder, for example bootstrap-icons.scss says "Bootstrap Icons v1.10.5".
Is the version number not changed by mistake or are all the files old?

**Comment by mdo** [comment]
Probably a miss on my part

**Comment by Alex-Toucan** [comment]
Now it seems like the icons are there but the version tag is still wrong.
