### ISSUE TITLE
Icons displayed incorrectly in icon font (parts of icons are filled that shouldn't be)

### ISSUE THREAD

**Issue by jkrei0** [twbs/icons#1817]
- Operating system: Windows 10
- Browser and version: Firefox 116.0.3, can also reproduce on chromium (Vivaldi)

The following screenshots are from the icons listing at [icons.getbootstrap.com](https://icons.getbootstrap.com)
![image](https://github.com/twbs/icons/assets/51007423/7eb4298f-b688-4c4c-b63c-51d9d8c32d57) ![image](https://github.com/twbs/icons/assets/51007423/dec64f2a-c54d-4605-8c11-a4f5b8eff65f) ![image](https://github.com/twbs/icons/assets/51007423/77800170-bac1-4b9a-a57d-cba82ad22ac1)

These icons have fill in places they should not. When clicked on to view larger/details, they display properly, and appear to display properly when embedded as an SVG, but not when using the icon font (see [jsfiddle demo of issue](https://jsfiddle.net/jessecode/7dvkbmq5/3/))

**Comment by spasibych** [comment]
I see the same on macOS 13.4 in Safari 16.5, Firefox 117.0.1 and Chrome 117.0.5938.88

**Comment by mdo** [comment]
Oops, my bad. I thought I checked all the full rules. Will update soon and get another release out when I can.

**Comment by jkrei0** [comment]
`balloon-heart-fill` also seems to be affected by the same issue, but was not fixed in v1.11.1
![image](https://github.com/twbs/icons/assets/51007423/a5ea2944-d4f1-4610-9424-ad23f8f4a439)
