### ISSUE TITLE
gitattribute concern with LF CRLF for woff files

### ISSUE THREAD

**Issue by bbruckert** [twbs/icons#1823]
Hello,
I'm running bootstrap-icon v1.11.1 through composer, and in our git architecture, the gitattribute don't force the commit to keep the font files woff and woff2 in a binary states.
To solve the issue, I changed the .gitattribute as follow : 
I added in the .gitattributes : 
*.woff    -text diff
*.woff2    -text diff

This way, the fact to commit my project don't change the file.
I don'yt know if this is a bug or a feature. Hope this may help
regards
Benoit

**Comment by XhmikosR** [comment]
woff files are binary files so they shouldn't be affected by line endings. Either you have a pretty ancient git version or a global .gitattributes file that's causing this.
