### ISSUE TITLE
docs: SVG Sprite page no longer loads icons

### ISSUE THREAD

**Issue by Le0Developer** [twbs/icons#1852]
Sprites stopped loading on https://icons.getbootstrap.com/sprite/.
This does not affect any other page as far as I can see.

<img width="1351" alt="image" src="https://github.com/twbs/icons/assets/40232557/3df5d04b-60f4-456d-9e5a-4392de39d190">

Tested on multiple devices (macOS, iOS, Windows 10, Android) and browsers (Chrome, Firefox, Safari) and confirmed by 5 friends of mine.

**Comment by XhmikosR** [comment]
Confirmed. Not sure exactly when this broke, if someone figures this out before I find some time pleasese make a PR and CC me.

**Comment by XhmikosR** [comment]
This broke in #1812 https://deploy-preview-1812--bootstrap-icons.netlify.app/sprite/

**Comment by XhmikosR** [comment]
Reported the issue upstream in https://github.com/xmldom/xmldom/issues/583
