### ISSUE TITLE
Docs: Broken link in usage instructions

### ISSUE THREAD

**Issue by coliff** [twbs/icons#1863]
Near the bottom of the page at: https://icons.getbootstrap.com/#working-with-svgs there is a link to https://simplyaccessible.com/article/7-solutions-svgs/#acc-heading-2 which is dead. The domain isn't accessible so I think the link should be removed.

Seeing as that link doesn't work and the other two links are regarding Internet Explorer perhaps this whole section could be removed?
![image](https://github.com/twbs/icons/assets/1212885/dfe6303a-adda-49cf-8643-1a736f4678af)

Alternatively, link to:
https://web.archive.org/web/20201112013541/https://simplyaccessible.com/article/7-solutions-svgs/#acc-heading-2
or perhaps this article:
https://www.scottohara.me/blog/2019/05/22/contextual-images-svgs-and-a11y.html

**Comment by XhmikosR** [comment]
Feel free to make a PR with the web archive link for now.
