### ISSUE TITLE
[icon request] Weak Wi-Fi singal

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/icons#189]
Icon to indicate when the Wi-Fi signal is weak.

**Comment by tmorehouse** [comment]
or `wifi-half`

**Comment by vanillajonathan** [comment]
I think that Android can even represent the signal strength with even more granularity.
Perhaps levels like; 100%, 75%, 50%, 25% and off.

**Comment by IamTregsthedev** [comment]
I can try to design a simple wifi down logo and see how it comes out.

**Comment by mdo** [comment]
This is already done in #290 :).
