### ISSUE TITLE
Newgrounds icon

### ISSUE THREAD

**Issue by ACrazyTown** [twbs/icons#2002]
Would it be possible to add an icon for [newgrounds](https://newgrounds.com/)?

They have some [design files](https://www.newgrounds.com/wiki/creator-resources/ng-design-assets) available which may be helpful:
![image](https://github.com/twbs/icons/assets/47027981/5a04a686-686a-437d-9622-749ce6285831)

**Comment by mdo** [comment]
Going to pass on this one. Seems a bit too specific.
