### ISSUE TITLE
Inner padding icons

### ISSUE THREAD

**Issue by Buchenblatt** [twbs/icons#2018]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi folks!

Some icons do not fill the space and therefore appear smaller.

### Reduced test cases

![bootstrap-icons](https://github.com/twbs/bootstrap/assets/171018621/e86ac53e-9b86-40fe-ad94-ce5cb438936b)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3

**Comment by xonicsolutions** [comment]
I've the same issue as described above. Would be nice if this issue would be fixed soon.

**Comment by xonicsolutions** [comment]
he is there any update yet?

**Comment by mdo** [comment]
Won't be redrawing icons anytime soon. Most are relatively sized to one another to ensure some visual consistency, but I get how that can look the opposite way. Already have this in mind for v2.
