### ISSUE TITLE
Remove clip-rule="evenodd" in path

### ISSUE THREAD

**Issue by bastienmoulia** [twbs/icons#205]
There is no use of `clipPath`, so the `clip-rule` seems useless.

Is there any reason to keep it?

**Comment by mdo** [comment]
I don't know for sure, but it seems like it's still needed when the SVGs are being exported and/or optimized with SVGO? There are plenty of subtractions in these icons where one shape is a cutout of the other. Will need more experienced folks to weigh in or to do some more research here.

**Comment by mdo** [comment]
Actually you're right, it does seem to be removable. I saw something else earlier that gave me the impression it was still being used in some places. Looking into it now.
