### ISSUE TITLE
Facebook Icon in square, or without circle

### ISSUE THREAD

**Issue by azam4code** [twbs/icons#2055]
The current Facebook icon is in a circle, but it would be better if it were just in a square and without the circle, because other social icons like Instagram or LinkedIn are in a square
![Screenshot 2024-09-25 163129](https://github.com/user-attachments/assets/e2df47b9-35bb-4f9c-aa4f-6b265f54dd81)
![Screenshot 2024-09-25 163221](https://github.com/user-attachments/assets/ad768a4e-a955-4da3-9db9-0d2c232a435b)
![Screenshot 2024-09-25 163238](https://github.com/user-attachments/assets/b67d08ae-6ac0-4d55-aab6-f40eacc52a53)

**Comment by Alex-Toucan** [comment]
Reminder that Facebook's logo is now officially a circle.

**Comment by Alex-Toucan** [comment]
For reference:
![Facebook_f_logo_(2021) svg](https://github.com/user-attachments/assets/cf6993a1-91e8-4f92-844a-a79f22805458)

**Comment by azam4code** [comment]
> w officially a circle.

I understand that Facebook's logo is currently displayed in a circle, but from a design perspective, if you're using the LinkedIn logo in a square format along with other social media logos, it would be more consistent to use a square version of the Facebook icon as well. This ensures a cohesive and balanced look across all the social icons. Using a simple Facebook icon without the circle would help maintain uniformity and create a cleaner, more structured design.
![Screenshot 2024-09-27 175124](https://github.com/user-attachments/assets/b08d3c03-c4a4-4346-a848-613401d9ff08)

**Comment by Alex-Toucan** [comment]
@azam4code usually Bootstrap Icons and other icon packs like to keep things official and up to date

**Comment by azam4code** [comment]
> usually Bootstrap Icons and other icon packs like to keep things official and up to date

@Alex-Toucan  I get that icon packs like to stay official, but my point was more about keeping the design consistent. Using a square Facebook icon alongside other square logos can help create a more balanced look, even if it's a slight tweak from the official design.

**Comment by Alex-Toucan** [comment]
@azam4code Just saying it's less likely they'll add something that's outdated nowadays.

**Comment by mdo** [comment]
Unsure if I'll add it—as mentioned, the Facebook logo is circular and the LinkedIn one is a square. I don't want to be in a spot where it's expected I do a variation for every brand.
