### ISSUE TITLE
[icon request] Phone (filled)

### ISSUE THREAD

**Issue by wfabritius** [twbs/icons#211]
Request for a "filled" phone icon, something like below:
https://fontawesome.com/icons/phone?style=solid

The current phone icons are unfilled, and also use a "mobile" phone design rather than "landline".
This makes them less recognisable, particularly at small sizes (e.g. button icons).

**Comment by Spayke01** [comment]
thank you, thats the only reason im not using this icons, 
this is must have, i use this icon in every design

**Comment by psjishnu** [comment]
@mdo  Issue fixed

**Comment by mdo** [comment]
This is being addressed in Figma first, and has been included in #273. Thanks though!
