### ISSUE TITLE
path stroke-width  = 1px  does not work

### ISSUE THREAD

**Issue by amuste** [twbs/icons#220]
When the icons are use in CSS set the stroke-width to 1px does not work.

**Comment by mdo** [comment]
These icons are only using fill; there’s no use of strokes anywhere.

**Comment by amuste** [comment]
Thanks for the quick response. 

this is from the documentation: https://icons.getbootstrap.com/

.bi::before {
  display: inline-block;
  content: "";
  background-image: url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'><path fill='none' stroke='%23333' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M5 14l6-6-6-6'/></svg>");
  background-repeat: no-repeat;
  background-size: 1rem 1rem;
}

**Comment by mdo** [comment]
Ah, apologies, I need to fix that. A few icons had a bug where I didn't properly outline them. Will fix!

**Comment by amuste** [comment]
I have fixed it in my application, now works perfectly

Thanks a lot
