### ISSUE TITLE
Rename arrow up down, arrow down up

### ISSUE THREAD

**Issue by slawbeard** [twbs/icons#239]
Order is important when calling double arrow icons or glyphs. Your arrow left right is correct (left first on top, right second on bottom)... in a similar way your current icon is arrow down up due to the order show. Now having pointed this out, you should have BOTH sets of left/right right/left and up/down down/up. Unicode and TeX do this as well - it is pretty much standard. 

In a science related field like chemistry, only “right left” is used for equilibrium states and “up down” for coupled electron spin states.

**Comment by mdo** [comment]
Fixed by #240.
