### ISSUE TITLE
[icon request] Add push pin/thumbtack icon

### ISSUE THREAD

**Issue by catchmyfame** [twbs/icons#257]
Can we have a push pin/thumbtack icon similar to the correspondong glyphicon? It's useful for a variety of things like pinned items, reminders, etc.

**Comment by RubenVerg** [comment]
like 📍 or like 📌? just wondering

**Comment by catchmyfame** [comment]
> like 📍 or like 📌? just wondering

I'd prefer the second example you listed. Something close to what BS3 had (https://getbootstrap.com/docs/3.3/components/) glyphicon glyphicon-pushpin

**Comment by RubenVerg** [comment]
☹
I like 📍 more, beacuse you can also use it to indicate locations, not only pinned stuff.

**Comment by catchmyfame** [comment]
> ☹ I like 📍 more, beacuse you can also use it to indicate locations, not only pinned stuff. From: 

I don't see why both couldn't be included

**Comment by RubenVerg** [comment]
Weel, more icons = more work!

________________________________

**Comment by RubenVerg** [comment]
also just realized there's `location` for 📍

**Comment by catchmyfame** [comment]
Thanks all
