### ISSUE TITLE
Deploy action

### ISSUE THREAD

**Issue by mdo** [twbs/icons#258]
Unclear if something I did triggered this, or if the action is broken somehow but today I noticed that the Icons site was on alpha 3 instead of alpha 4. Manually pushed to the `gh-pages` branch to resolve it for now.

**Comment by bastienmoulia** [comment]
@mdo Do you still have your `secrets.PERSONAL_TOKEN` ?

**Comment by XhmikosR** [comment]
Could be something temporary that caused the hook not to fire. If happens again, reopen the issue and ping me.
