### ISSUE TITLE
Save (floppy disk) icon

### ISSUE THREAD

**Issue by yousifalraheem** [twbs/icons#272]
Please add an icon representing **save**. Something similar to the one in [fontawesome](https://fontawesome.com/icons/save?style=regular)

**Comment by XmlmXmlmX** [comment]
The committed `save`-icons don't really look like a common save icon:

![image](https://user-images.githubusercontent.com/677165/107632875-63feb400-6c67-11eb-88bc-b22513e54bd5.png)

Why not use a well known floppy-disk as suggested in the issues title?

![image](https://user-images.githubusercontent.com/677165/107633331-1c2c5c80-6c68-11eb-9930-c0fc53d92ac3.png)

**Comment by mdo** [comment]
> Why not use a well known floppy-disk as suggested in the issues title?

Personally I haven't clicked a floppy disk icon for years—a growing majority of interfaces don't use it and instead opt for download icons. These save icons are reminiscent enough of floppy disks to work well IMO.

**Comment by scottkuhl** [comment]
> > Why not use a well known floppy-disk as suggested in the issues title?
> 
> Personally I haven't clicked a floppy disk icon for years—a growing majority of interfaces don't use it and instead opt for download icons. These save icons are reminiscent enough of floppy disks to work well IMO.

This is just wrong.  There have been 4 issues opened now about this.  No matter what you believe or you are trying to push, this confuses users.  The number one feedback I get with this icon set is where is the save?

It’s not about you and what you have personally clicked.  The floppy is a universal standard.

Please stop closing these issues and provide an alternative.

**Comment by samuelstroschein** [comment]
> a growing majority of interfaces don't use it and instead opt for download icons 

I am building a web app that is modifying files, not downloading them. Using bootstrap's "save" icons which are "download" icons is confusing.

**Comment by shishirraven** [comment]
I agree that "Floppy" icon is most recognized symbol of Save, in situations where a group of Icons are placed together. 
The user should be able to easily identify which one is save button. 

See the following bar and we had to use to "Cloud Upload" icon, which is not the best for the users to identify easily, even I get confused when I am the developer of the app. 

![image](https://user-images.githubusercontent.com/4470383/176592964-0d0ee972-a05c-4b04-948b-bab4980e8abe.png)

The save icons are good but only in case we are downloading some file from the web. But when you are working on an app and saving your work or draft online or working on a electron app, I think floppy is much more relevant.

**Comment by scottkuhl** [comment]
> I agree that "Floppy" icon is most recognized symbol of Save, in situations where a group of Icons are placed together. The user should be able to easily identify which one is save button.
> 
> See the following bar and we had to use to "Cloud Upload" icon, which is not the best for the users to identify easily, even I get confused when I am the developer of the app.
> 
> ![image](https://user-images.githubusercontent.com/4470383/176592964-0d0ee972-a05c-4b04-948b-bab4980e8abe.png)
> 
> The save icons are good but only in case we are downloading some file from the web. But when you are working on an app and saving your work or draft online or working on a electron app, I think floppy is much more relevant.

I agree, it’s strange that the maintainers will not add an additional icon.  It makes no sense to dig in on this issue.  How many us are still walking around with magnifying glasses in our pockets looking for stuff, but it’s still the search icon.  I really wish we could convince the maintainers to add this request.  The time it takes to closing multiple issues about this is longer than making the icon.

This one single issue is why I can’t get buy off from my company to use this icon set.  So sad.
