### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by mdo** [twbs/icons#3]
Add copy to clipboard for SVG code in the docs (clicking the icon should do it)

**Comment by mdo** [comment]
@XhmikosR I tried to bring this over from Bootstrap proper and it ended up causing tons of JS errors. I'm guessing I was missing some linting support files or something. Might ping you in a PR on this later.

**Comment by XhmikosR** [comment]
Should be easy to do, if you have a WIP branch so that I can see how you want to implement it, that would help :)

**Comment by inwardmovement** [comment]
I may have a try to PR for this tomorrow
