### ISSUE TITLE
[Icon request] Heartbeat icon

### ISSUE THREAD

**Issue by naitsirch** [twbs/icons#301]
I'd like to request a heartbeat icon that can be used as an association of monitoring.

Examples:
* https://fontawesome.com/icons/monitor-heart-rate?style=regular
* https://cdn1.iconfinder.com/data/icons/complete-medical-healthcare-icons-for-apps-and-web/128/pulse2-512.png
* https://cdn.onlinewebfonts.com/svg/img_493599.png

**Comment by tranlamnhatnam** [comment]
+1
