### ISSUE TITLE
Number Icon

### ISSUE THREAD

**Issue by shishirraven** [twbs/icons#314]

**Comment by mdo** [comment]
What kind of numbers? Numbed list? Random number? Specific numbers?

**Comment by hijuliancode** [comment]
Hi!, Here is the PR: https://github.com/twbs/icons/pull/320

**Comment by shishirraven** [comment]
> What kind of numbers? Numbed list? Random number? Specific numbers?
Just something to depict number input. 
like date input, location input, and number input. 
So I was looking for an icon which can depict number. 
it could be an icon with "123" written.

**Comment by y377** [comment]
> What kind of numbers? Numbed list? Random number? Specific numbers?

Hi, can you add 11 and 12? I want to add the month, 1 to 12
