### ISSUE TITLE
[Icon Request] Light Bulb

### ISSUE THREAD

**Issue by cbarest** [twbs/icons#323]
Would be nice to add a light bulb icon for tips, ideas, thoughts, etc.
Similar to: 
![light-bulb](https://user-images.githubusercontent.com/11466745/85791191-6a9fe180-b6ff-11ea-9bb7-5ed392868037.png)
Could make a few variants including: 
- outline & solid
- with and without rays coming out of bulb

**Comment by adrianoresende** [comment]
+1

**Comment by jonalxh** [comment]
+1
