### ISSUE TITLE
Videoconference icon

### ISSUE THREAD

**Issue by inwardmovement** [twbs/icons#329]
For reference:
https://www.google.com/search?q=Video+Conference+icon&tbm=isch
![image](https://user-images.githubusercontent.com/9438102/85916533-faee3b80-b851-11ea-9d7d-e47a7987d68e.png)

**Comment by mdo** [comment]
Added a few video-person icons awhile back:

- https://icons.getbootstrap.com/icons/person-video3/
- https://icons.getbootstrap.com/icons/person-video2/
- https://icons.getbootstrap.com/icons/person-video/
