### ISSUE TITLE
Typed files icons

### ISSUE THREAD

**Issue by inwardmovement** [twbs/icons#330]
Combining [files](https://icons.getbootstrap.com/icons/files/) and [file-spreadsheet](https://icons.getbootstrap.com/icons/file-spreadsheet/), [file-text](https://icons.getbootstrap.com/icons/file-text/)...

And maybe an alternative with a file extension label (txt, pdf, etc.)

For reference:
https://www.google.com/search?q=files+text+icon&tbm=isch
![image](https://user-images.githubusercontent.com/9438102/85916678-697fc900-b853-11ea-94de-d12508985d67.png)

**Comment by vanillajonathan** [comment]
There are lots now.
- https://icons.getbootstrap.com/icons/file-earmark-bar-graph/
- https://icons.getbootstrap.com/icons/file-earmark-binary/
- https://icons.getbootstrap.com/icons/file-earmark-code/
- https://icons.getbootstrap.com/icons/file-earmark-diff/
- https://icons.getbootstrap.com/icons/file-earmark-excel/
- https://icons.getbootstrap.com/icons/file-earmark-image/
- https://icons.getbootstrap.com/icons/file-earmark-font/
- https://icons.getbootstrap.com/icons/file-earmark-medical/
- https://icons.getbootstrap.com/icons/file-earmark-music/
- https://icons.getbootstrap.com/icons/file-earmark-pdf/
- https://icons.getbootstrap.com/icons/file-earmark-play/
- https://icons.getbootstrap.com/icons/file-earmark-ppt/
- https://icons.getbootstrap.com/icons/file-earmark-richtext/
- https://icons.getbootstrap.com/icons/file-earmark-slides/
- https://icons.getbootstrap.com/icons/file-earmark-spreadsheet/
- https://icons.getbootstrap.com/icons/file-earmark-text/
- https://icons.getbootstrap.com/icons/file-earmark-word/
- https://icons.getbootstrap.com/icons/file-earmark-zip/
- https://icons.getbootstrap.com/icons/file-earmark-x/

Is there any more that you miss?

**Comment by inwardmovement** [comment]
No we can close, thank you!
