### ISSUE TITLE
Join us icon

### ISSUE THREAD

**Issue by inwardmovement** [twbs/icons#331]
For reference:
https://www.google.com/search?tbm=isch&q=join+icon
![image](https://user-images.githubusercontent.com/9438102/85916754-05113980-b854-11ea-83a2-b817692f6675.png)

**Comment by korki43** [comment]
Is this what you are looking for?

https://icons.getbootstrap.com/icons/person-plus/
https://icons.getbootstrap.com/icons/people/

**Comment by inwardmovement** [comment]
Not really. The concept of "joining us" may not be easy to express as an icon...

**Comment by mdo** [comment]
@korki43 is right, these are the options that get you closest to this concept:

- https://icons.getbootstrap.com/icons/person-plus/
- https://icons.getbootstrap.com/icons/person-plus-fill/
