### ISSUE TITLE
Commitee icons

### ISSUE THREAD

**Issue by inwardmovement** [twbs/icons#332]
With various types of commitees: communication, steering, advising, community management, etc.

For reference:
https://www.google.com/search?tbm=isch&q=committee+icon
![image](https://user-images.githubusercontent.com/9438102/85916783-443f8a80-b854-11ea-8dd8-cc72ae8eafa1.png)

**Comment by mdo** [comment]
The people icons are probably best here:

- https://icons.getbootstrap.com/icons/people/
- https://icons.getbootstrap.com/icons/people-fill/
