### ISSUE TITLE
[Suggestion] Support for slippy map markers

### ISSUE THREAD

**Issue by saturdaywalkers** [twbs/icons#337]
Leaflet, Google & Bing maps support SVG icons.

Suggestion: support svg icons as  map markers / icons / pushpins 

maybe:
- layer a given icon svg on top of generic  larger shield / circle / pushpin icon svg - leaflet only
- duplicate (all icons) on top of (each background icon) - would work for for all 3

From memory, with Leaflet, an icon can be a divIcon (a div with any content), while Google and Bing maps need a url or inline SVG
https://leafletjs.com/reference-1.6.0.html#divicon
https://developers.google.com/maps/documentation/javascript/reference/marker#Icon / symbol inteface / path
https://docs.microsoft.com/en-us/bingmaps/v8-web-control/map-control-api/pushpinoptions-object

Not a small ask, but would be very popular - there is no good way of doing this now

**Comment by mdo** [comment]
Thanks, but I don't see myself jumping into this. If someone else wants to take this on as a supplement to this repo, they're more than welcome.
