### ISSUE TITLE
More times icons

### ISSUE THREAD

**Issue by afuno** [twbs/icons#343]
The "times" (you have them called "x") icons for all types - users, calendars, clock, circles, squares, etc.

For reference:

- [First](https://www.google.com/search?q=user+times+icon&tbm=isch&ved=2ahUKEwiXl_jcn6_qAhVI1eAKHcauCjEQ2-cCegQIABAA&oq=user+times+icon&gs_lcp=CgNpbWcQAzoCCAA6BAgAEB46BggAEAUQHlCzCFjCKWCjK2gAcAB4AIABggGIAfYFkgEDMC42mAEAoAEBqgELZ3dzLXdpei1pbWc&sclient=img&ei=JS7-XtfwB8iqgwfG3aqIAw)
- [Second](https://www.google.com/search?q=calendar+times+icon&tbm=isch&ved=2ahUKEwigxuLEoK_qAhVE7eAKHW5OAKAQ2-cCegQIABAA&oq=calendar+times+icon&gs_lcp=CgNpbWcQA1CLPFjsRGDgSGgAcAB4AIABzwGIAc4IkgEFMC43LjGYAQCgAQGqAQtnd3Mtd2l6LWltZw&sclient=img&ei=_i7-XqDPNcTagwfunIGACg)

<img width="500" alt="Снимок экрана 2020-07-02 в 22 01 13" src="https://user-images.githubusercontent.com/2853419/86399336-bb8b7900-bcaf-11ea-9d7a-3260239c16f4.png">
<img width="500" alt="Снимок экрана 2020-07-02 в 22 02 25" src="https://user-images.githubusercontent.com/2853419/86399346-c0502d00-bcaf-11ea-801b-5a5204169887.png">

**Comment by mdo** [comment]
This is pretty well covered by icons today.
