### ISSUE TITLE
Unify box arrow icons

### ISSUE THREAD

**Issue by Tr1KzZ** [twbs/icons#356]
I also kinda dislike the "box arrow left" and "box arrow in left" (and related) icons a bit, because the boxes don't match in size. Uniform boxes would probably be more harmonious.

I have quickly arranged the icons next to each other and added red lines to make different box sizes more clear. You can see nicely that the supposedly same box-arrow-icons don't have the same size.

I personally would stick to the format of the icons inside the red rect (most appealing in my oppinion) and orientate the remaining icons accordingly to these.

The box differs mainly for the box arrow in and not in icons. The difference between the "top/bottom" and "left/right" box arrow icons could theoretically remain untouched, since they seem to be only 90 degree rotated versions.

![Screenshot_3](https://user-images.githubusercontent.com/67892761/86741198-7d87af80-c037-11ea-8c4d-26a21f5e4248.png)

**Comment by mdo** [comment]
Yeah, this one will be a little difficult to make completely consistent across each icon. I'm also noticing I need to redraw my arrows in general to fix some path issues. Will do my best!
