### ISSUE TITLE
Eraser, eyedropper, and symmetry digital art icons

### ISSUE THREAD

**Issue by jkrei0** [twbs/icons#366]
There are pen/pencil/brush icons already, and I think it would be nice to add eraser, eyedropper, and symmetry icons.

These would be nice to have for digital art websites/programs.

**Comment by mdo** [comment]
By symmetry, do you mean alignment and distribution?

**Comment by 99banana** [comment]
Many digital art programs have the option to mirror your strokes across a line of symmetry. What I mean by a symmetry icon is something that represents a mirrored object, eg.

![Symmetry icon example](https://tse1.mm.bing.net/th?id=OIP.Xjm1SVoINNc3kWMo2MAmMAHaHa&pid=Api)
