### ISSUE TITLE
Source files with strokes

### ISSUE THREAD

**Issue by JohannesDeml** [twbs/icons#369]
I just noticed that all icon strokes are already converted to paths in the icons folder. Is there another folder location were I can find the source files? If not, are there plans to also include the source files with which the icons were created? Right now it is very hard to remix the icons, since the strokes are already converted to paths. This makes it hard to modify the stroke with / animate them / remix them.

**Comment by mdo** [comment]
Figma file is linked from the readme and many icons have their vector originals hidden in the art boards. For v1, I'm going all in on fill and no stroke for ease of use and consistency. Unsure what'll happen in future versions.

**Comment by JohannesDeml** [comment]
Thanks for the reply. I took a look at the figma file before, but didn't see the source files at first glimpse. Thanks for clarifying!

**Comment by bbarry** [comment]
It would be nice to note compatible paths/strokes for mashup icons as well at some point. Eg:

* a set of uppercase/lowercase letters (or instructions on how to center a letter of your choice in your font)
* a few different checkmarks/dots/filled interior squares

all of which could work in various combinations with

* outline square
* outline circle
* chat left/right/square/original...

and so on. Remix-able source sets would offer a huge boon to bootstrap compatible design/animation libraries.

I'm imagining stuff like a chat app with typing icons that have the first letter of each person's name animating to ellipsis in a dual tone icon or something like that.

**Comment by mdo** [comment]
Figma has some source assets in each icon's artboard, but not everyone. There aren't stroke only versions for every icon and I have no plans to add that anytime soon unfortunately :).
