### ISSUE TITLE
Bootstrap Icons Sprite Not Showing

### ISSUE THREAD

**Issue by billstrahlend** [twbs/icons#371]
As appropriate, please include:

- Operating system and version (macOS 10.15.5 (Catalina))
- Browser and version (Chrome (83.0.4103.116), Firefox (77.0.1), Safari (13.1.1), Microsoft Edge (83.0.478.64))

I am attempting to use the Bootstrap icons on my webpage using the sprite option and method. I placed the following in the body of the webpage:

&lt;article&gt;
    &lt;h1&gt;Bootstrap Icons&lt;/h1&gt;					
    &lt;svg class="bi" width="32" height="32" fill="currentColor"&gt;
        &lt;use xlink:href="assets/img/bootstrap-icons.svg#heart-fill"/&gt;
    &lt;/svg&gt;
    &lt;svg class="bi" width="32" height="32" fill="currentColor"&gt;
        &lt;use xlink:href="assets/img/bootstrap-icons.svg#toggles"/&gt;
    &lt;/svg&gt;
    &lt;svg class="bi" width="32" height="32" fill="currentColor"&gt;
        &lt;use xlink:href="assets/img/bootstrap-icons.svg#shop"/&gt;
    &lt;/svg&gt;				
&lt;/article&gt;

I have in place in the &lt;head&gt; tags:
&lt;link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"&gt;

and at the bottom of the <body> I have the following:

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

====

All I get on my webpage is the appropriate spacing where the icons should be, but no icons. All that is there is the space of 32x32 for each of the icons, but nothing else.

**Comment by mdo** [comment]
This is most likely an implementation problem, and not a bug on our end. If you need help with something like this, we'd need a live demo and not snippets of code. For example, Bootstrap's CSS and JS has no bearing on these icons and wouldn't need to be included here.

**Comment by oldcastlehq** [comment]
In my case, I cannot find the stripe.svg file from the latest release.

**Comment by yansusanto** [comment]
Yes, Sprite svg is not included even when it is installed via NPM

**Comment by billstrahlend** [comment]
For me, it was an issue of my page running from file:///... instead of localhost or up on the web. This issue is resolved for me.

**Comment by mdo** [comment]
> Yes, Sprite svg is not included even when it is installed via NPM

I just ran a fresh `npm i boostrap-icons` and the sprite is there, where it should be (it's not inside the icons folder, but the root of the `bootstrap-icons` directory).

**Comment by yansusanto** [comment]
Thanks, @mdo I did the fresh install. It is there now in alpha5 but not in alpha4.

**Comment by estsim** [comment]
Installed today, all files are there. Every separate svg shows, but the sprite isn't working for me.
