### ISSUE TITLE
Working with SVGs Docs - IE11 compatibility

### ISSUE THREAD

**Issue by coliff** [twbs/icons#372]
The notes for Working with SVGs are helpful. Do you think it could be a good idea to add a note about suggesting using svg4everybody for IE 11 support when using the SVG Sprite method?

That polyfill works great, is lightweight (1KB gzipped) and is easy to implement with:
```
  <script nomodule src="svg4everybody.min.js"></script>
  <script nomodule>svg4everybody();</script>
```

REF: https://github.com/jonathantneal/svg4everybody

**Comment by billstrahlend** [comment]
IE11 support from Microsoft will end in 2025 for the general public and up to 2029 for Enterprise versions of Windows 10. Microsoft will not be developing new versions of IE anymore. Microsoft has shifted all development for their new browser, Edge. This is why most developers are no longer supporting IE modifications. I personally don't build out for IE anymore.

https://www.microsoft.com/en-us/microsoft-365/windows/end-of-ie-support

https://support.microsoft.com/en-us/lifecycle/search?alpha=Windows%2010

**Comment by coliff** [comment]
Thanks - Yes, I'm well aware the IE11 support timeline - and I know some developers are choosing to not support it. I'm not sure how relevant that is in regards to this issue/suggestion though. In the 'Working with SVGs' section there is already a note about fixing focus handling for Internet Explorer by adding `focusable="false"` - I'm just suggesting adding a note and a link to a fix.

**Comment by mdo** [comment]
I'm in favor. I've not used this myself personally, so a little snippet and context in our docs could be helpful.

**Comment by coliff** [comment]
thanks @mdo - I'll open a PR tomorrow morning. 👍
