### ISSUE TITLE
icon request: site nav (hamburger icon / trigram for heaven)

### ISSUE THREAD

**Issue by bbarry** [twbs/icons#378]
This is the only icon missing from this collection that will keep me (and likely many others) using font awesome.

**Comment by mdo** [comment]
Does https://icons.getbootstrap.com/icons/list/ work for this?

**Comment by ffes** [comment]
I am not the OP, but for me it does.

This issue was created when this icon already existed. It shows how important the tags are.

**Comment by bbarry** [comment]
Yes it works, I was pretty sure I saw one here with 4 rows at the time I entered this.
