### ISSUE TITLE
Social Media Icons 

### ISSUE THREAD

**Issue by dh00mk3tu** [twbs/icons#380]
There's no support for social media icons.
Major one's that really should be included 

1. Quora
2. Twitter
3. Telegram
4. Facebook
5. YouTube
6. Instagram
7. WhatsApp
8. Twitch 
9. GitHub  
10. Outlook
11. LinkedIn

**Comment by mdo** [comment]
Duplicate of #96.

**Comment by dh00mk3tu** [comment]
Oh,
I am sorry, I did check in on previous issues but didn't find this one in particular
