### ISSUE TITLE
Sprite not always Working

### ISSUE THREAD

**Issue by ben29** [twbs/icons#381]
- Operating system and version macOS - last version
- Browser and version Chrome - last version
- No Adblock or something.
- no console error log

when I even browser to here:
https://icons.getbootstrap.com/

![GitHub Logo](https://i.ibb.co/pJHVGwk/Screen-Shot-2020-07-30-at-16-38-57.png)

as you see I can't see the sprite.. the same problem happen on my website...

but after few refresh's the icons will be shown

**Comment by o-alquimista** [comment]
I can only reproduce this on Chromium/Chrome. On Firefox and WebKit browsers such as GNOME Web, this is not reproducible.

A normal page reload `Ctrl + R` works without issues. But if I do a full page reload `Ctrl + Shift + R`, the sprites will eventually disappear at some point, and become visible again in subsequent page reloads. It could also happen when you're opening the page for the first time ever, or after a long time. It could be related to caching.

Should we treat this as a Chromium bug and report it to them instead?

**Comment by bastienmoulia** [comment]
It is a known issue https://bugs.chromium.org/p/chromium/issues/detail?id=1107442 in Chrome 84 and should be fix in Chrome 85.

**Comment by XhmikosR** [comment]
Is this still an issue?

**Comment by ben29** [comment]
To be honest i check if fontawsome have the same problem
But it’s look they don’t have any issue with it
After updating to last chrome version
Looks normal
