### ISSUE TITLE
Wrong way around: calendar2-week / calendar2-week-fill

### ISSUE THREAD

**Issue by tstewart-klaudhaus** [twbs/icons#382]
Looks like the normal and "fill" version of calendar2-week (and -range and and -event) have been mixed up. The "fill" name is assigned to the outline image and vice versa.

You can see this by entering "calendar2" in the search field on https://icons.getbootstrap.com/ and comparing icons. 

Fixing this will have some effect on existing designs.

**Comment by mdo** [comment]
This is fixed in the upcoming release. Was addressed when I re-exported tons of icons.
