### ISSUE TITLE
Terrible markup is a bad practice

### ISSUE THREAD

**Issue by thednp** [twbs/icons#395]
From my experience working with SVG, the idea to have multiple `<path>` Elements per shape is horrible from a development standpoint. Yes you can color/style each shape separately, but I would like to see `bootstrap-icons.svg` with this structure:
* one `<svg>` Element with the `viewBox` attribute
* all icons with a single `<path>` Element for each shape
* no `fill-rule`, `stroke`-related attributes, or any attribute to "shape" the shape

Example:
```markup
  <svg id="bs" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 16 16">
      <path fill="currentColor" id="alarm" d="M6.5 0a.5.5 0 000 1H7v1.07a7.001 7.001 0 00-3.273 12.474l-.602.602a.5.5 0 00.707.708l.746-.746A6.97 6.97 0 008 16a6.97 6.97 0 003.422-.892l.746.746a.5.5 0 00.707-.708l-.601-.602A7.001 7.001 0 009 2.07V1h.5a.5.5 0 000-1h-3zm1.038 3.018a6.093 6.093 0 01.924 0 6 6 0 11-.924 0zM8.5 5.5a.5.5 0 00-1 0v3.362l-1.429 2.38a.5.5 0 10.858.515l1.5-2.5A.5.5 0 008.5 9V5.5zM0 3.5c0 .753.333 1.429.86 1.887A8.035 8.035 0 014.387 1.86 2.5 2.5 0 000 3.5zM13.5 1c-.753 0-1.429.333-1.887.86a8.035 8.035 0 013.527 3.527A2.5 2.5 0 0013.5 1z"/>
</svg>
  
```

Benefits outweigh any CONs
* Significantly lighter size (no `<symbol>` wrapper with own viewBox), since the library has potential to grow, this makes more and more sense
* Much faster parsing of the markup, possibly most important
* Devs can create font-icons if they so chose or need, real easy
* Easier to manage a growing icons base 

Suggestion: share the source of the `bootstrap-icons.svg` with the above markup.

**Comment by thednp** [comment]
[This](https://raw.githubusercontent.com/twbs/icons/icon-font/dist/font/bootstrap-icons.svg) makes sense.

**Comment by mdo** [comment]
SVGs are optimized manually as best as I can in Figma, and then with an automated script and SVGO. If there's something that comes to mind for how I can improve those things, please let me know.

**Comment by thednp** [comment]
Thanks for the reply. I feel you man. Just please try and keep consistency first, optimizations come in time.
