### ISSUE TITLE
The bootstrap-icons.svg for font-icons is broken

### ISSUE THREAD

**Issue by thednp** [twbs/icons#396]
![image](https://user-images.githubusercontent.com/6761246/89708126-f85c2700-d963-11ea-9141-f7024cded58c.png)

Possibly related to some svgo processing.

**Comment by thednp** [comment]
For those interested, I made a new tool to solve that, check my [SVGPathCommander](https://thednp.github.io/svg-path-commander/).

**Comment by mdo** [comment]
Don't know what this is in reference to... the code in the screenshot doesn't exist here.

**Comment by thednp** [comment]
@mdo [what is this](https://github.com/twbs/icons/blob/8db7e4436461c00fadad082240e1ae6a75374d17/dist/font/bootstrap-icons.svg#L723)?

**Comment by mdo** [comment]
Ah, I forgot to push the updated sprite from my latest PRs. Was looking at a different version of that earlier.

**Comment by thednp** [comment]
Keep up the good work Mark. Shiny!

**Comment by thednp** [comment]
Ah, I was hoping you also update the [font-icon](https://github.com/twbs/icons/blob/icon-font/dist/font/bootstrap-icons.svg) svg file.

**Comment by mdo** [comment]
My work on the font files hit some snags so I've had to focus on the SVG cleanup first. Hoping to come back to it soon or get some contributor help there.

**Comment by thednp** [comment]
Well, let me tell you something. I've developed a [JS tool](https://github.com/thednp/svg-path-commander) (hoping to contribute for your project, an ES6 tool you can also work with), something to work with SVG path commands, but you don't seem to have any logic to the drawing and attributes of those shapes.

Please allow me to explain (I happen to have some experience working with SVG):
* when you draw shapes/symbols with path + sub-path/s, only use `fill-rule: evenodd` if it's really needed (like paths intersect and design wise required)
* when a shape like the above is followed by another one like it, you better take into account these additional paths, make sure the fill rule from first shape/symbol is consistent with the second, the second might probably need `fill-rule: reverse` or `nonzero`
* think of the symbols as if they-re made of a single path element, a much more simple way to explain what's needed because there is no SVGO or similar script to merge paths perfectly, because so far tinkering with your files in the last couple days, I couldn't find one way to make all symbols look like the demo.
* the logic should be documented, so that people understand and contribute (like I would), see below a conversion from your latest bootstrap-icons.svg to a font-icon ready all multi-path symbols into one path

I hope I'm not boring you much.

![font-icon](https://user-images.githubusercontent.com/6761246/90635357-a0050f00-e218-11ea-8890-fed25277b11e.png)

**Comment by thednp** [comment]
[HERE YOU GO](https://github.com/twbs/icons/files/5162708/extract_bootstrap_icons.zip)

I made a tool for you based on latest [bootstrap-icons.svg](https://github.com/twbs/icons/blob/main/bootstrap-icons.svg) file to convert all your shapes to normal without `fill-rule: evenodd`, however some didn't follow any logic so they can be manually edited [here](https://thednp.github.io/svg-path-commander/).
