### ISSUE TITLE
Which font is used when numbers/letters are used ?

### ISSUE THREAD

**Issue by pierrebaronqumu** [twbs/icons#401]
This is actually a question. 

Some icons, like bade-xx have letters, numbers used in them. What is the font used when drawing those icons ? 

It would be interesting to document it so that contribution can use the same font and provide a more consistent icon set.

**Comment by pierrebaronqumu** [comment]
When playing with the Figma file, I noticed that the `SF Compact Text` font is being used, however, I cannot quite get it to match the icons.

![image](https://user-images.githubusercontent.com/55976399/90619686-6f69a900-e209-11ea-8030-24ddea8a683c.png)

**Comment by mdo** [comment]
> I noticed that the `SF Compact Text` font is being used, however, I cannot quite get it to match the icons.

Yup, that's right. That's the base font, but with some custom modifications.

**Comment by pierrebaronqumu** [comment]
Would it be possible to get the custom modifications?

That way people can make some icons contributions including text and we will still have a consistent icon set.

**Comment by mdo** [comment]
It involves converting to outlines, then manually adjusting certain characters and their spacing to hit whole pixels as much as possible. I'm afraid I don't have a list of modifications I've made to each one.
