### ISSUE TITLE
figma file can't open 

### ISSUE THREAD

**Issue by sa1i** [twbs/icons#410]
I can't open this figma file 
https://www.figma.com/file/9YmlUAwhMv99G4yP4yN7Jy/Bootstrap-Icons-v1.0.0?node-id=0%3A1

**Comment by fortunewalla** [comment]
Same problem. I get the message:

> File not found
> 
> Either this file doesn’t exist or you don’t have permission to view it. Ask the file owner to verify the link and/or update permissions.
> 
> You’re signed in as \*\*\*\*@\*\*.com. Sign out

**Comment by mdo** [comment]
Apologies, it's been updated! https://www.figma.com/file/9YmlUAwhMv99G4yP4yN7Jy/Bootstrap-Icons-v1.0.0?node-id=0%3A1
