### ISSUE TITLE
Duplicate squared arrow icon 

### ISSUE THREAD

**Issue by pschuchmann** [twbs/icons#423]
Hi there,

I was just browsing the available icons and searched for some arrow icons and while browsing I found a duplicate icon.

`arrow-down-square-fill.svg` and `arrow-up-square-fill.svg` seem to have the same path information. The arrow up actually shows a downward pointing arrow.

**Comment by bastienmoulia** [comment]
The problem also exist in the Figma file : https://www.figma.com/file/9YmlUAwhMv99G4yP4yN7Jy/Bootstrap-Icons-v1.0.0?node-id=3938%3A5017
