### ISSUE TITLE
Request for Mega Phone icon

### ISSUE THREAD

**Issue by techmeav** [twbs/icons#424]
Hi there this is Anirudh. I am requesting for a megaphone icon, silent icon 📢 and loud icon like these emojies 📣.
I hope that BootStrap makes these icons.
Thanks in Advance

**Comment by techmeav** [comment]
> Hi there this is Anirudh. I am requesting for a megaphone icon, silent icon 📢 and loud icon like these emojies 📣.
> I hope that BootStrap makes these icons.
> Thanks in Advance

Also I want the icon in line not solid

**Comment by dsentker** [comment]
+1

**Comment by ffes** [comment]
dup of #357?

**Comment by techmeav** [comment]
No

**Comment by mdo** [comment]
Duplicate of #357.
