### ISSUE TITLE
Figma link not working un README

### ISSUE THREAD

**Issue by bastienmoulia** [twbs/icons#427]
The link to the page https://www.figma.com/file/9YmlUAwhMv99G4yP4yN7Jy/Bootstrap-Icons-v1.0.0?node-id=0%3A1 indicate :

> File not found
> Either this file doesn’t exist or you don’t have permission to view it. Ask the file owner to verify the link and/or update permissions.

**Comment by mdo** [comment]
Apologies, it's been updated! https://www.figma.com/file/9YmlUAwhMv99G4yP4yN7Jy/Bootstrap-Icons-v1.0.0?node-id=0%3A1
