### ISSUE TITLE
Include IDs in the single SVG files

### ISSUE THREAD

**Issue by igorprakljacic** [twbs/icons#430]
The problem with including a SVG via the IMG tag is that there is no way to change the style via CSS.
If the SVG had an ID, then you could include this via the SVG tag and have better control over the style.

<svg class="bi" width="32" height="32" fill="currentColor">
  <use xlink:href="heart-fill.svg#self"/>
</svg>

**Comment by RubenVerg** [comment]
There's the spritesheet for this purpose

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by igorprakljacic** [comment]
I know but what if i only want to use like lets say 10 icons?

File size of bootstrap-icons.svg is 578kb
10 randomly selected icons is 6,32kb

**Comment by RubenVerg** [comment]
Is it just my browser that only loads the required ID size? It apparently parses the file once and then -as long as it’s cached- loads the correct part only

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by igorprakljacic** [comment]
I just checked it in the ff dev tools: The transferred size is actually 96,14KB (due to gzip).
So it is less problematic then i thought, when loading a web page for the first time.

**Comment by mdo** [comment]
No plans to add IDs at this time—we have classes in place already and that should be enough.

**Comment by dvdkon** [comment]
I've run into a slightly different problem with the lack of IDs in the individual SVGs: According to the SVG2 spec and MDN, the `<use>` tag should accept a bare path to an SVG file in its `href` attribute and display it whole. However, this doesn't seem to work in Firefox or Chrome. They both require a URL fragment pointing to an ID or they don't render anything. Currently I've worked around this problem by adding an id of "icon" to all the individual SVGs with a simple shell one-liner, but ideally this usecase would be supported in the upstream repo.
