### ISSUE TITLE
Translate icon

### ISSUE THREAD

**Issue by pierrebaronqumu** [twbs/icons#445]
Hi,

It would be nice to have a Translate icon like 
![image](https://user-images.githubusercontent.com/55976399/93894802-0c2ad500-fce7-11ea-9706-7302b18e825c.png)

or https://fontawesome.com/icons/language?style=solid in the app.

I would be OK to do it myself but I recall that there are some custom modifications regarding letters in the icons (cf: https://github.com/twbs/icons/issues/401#issuecomment-678003249).

**Comment by mdo** [comment]
Duplicate of #168
