### ISSUE TITLE
Svg icons with one Path inside

### ISSUE THREAD

**Issue by punker76** [twbs/icons#454]
Thx for this awesome icon library.

It would be great to have these svg icons as one path svg version, to use this at the Xaml world.

Example:

Instead this Svg:

```xml
<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-align-bottom" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M6 2a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V2z"/>
  <path fill-rule="evenodd" d="M1 14.5a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13a.5.5 0 0 1-.5-.5z"/>
</svg>
```

it would be nice to have such Svg:

```xml
<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-align-bottom" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M 1,14.5 A 0.5,0.5 0 0 1 1.5,14 h 13 a 0.5,0.5 0 0 1 0,1 H 1.5 A 0.5,0.5 0 0 1 1,14.5 Z M 6,2 A 1,1 0 0 1 7,1 h 2 a 1,1 0 0 1 1,1 V 12 A 1,1 0 0 1 9,13 H 7 A 1,1 0 0 1 6,12 Z" />
</svg>
```

Background, I would like to provide these icons in the [IconPacks](https://github.com/MahApps/MahApps.Metro.IconPacks) library. It's a lib to use Icons in a simple way for WPF and UWP applications.

**Comment by mdo** [comment]
No plans to reduce every single SVG to a single path. I don't optimized each one individually, so this mostly comes down to SVGO and more.

Related to #369
