### ISSUE TITLE
searching for an icon in a document is very weak and difficult

### ISSUE THREAD

**Issue by miladcatalan** [twbs/icons#455]
for example: user or location keyword is nothing found.
please add tags to icon for better search

**Comment by dsentker** [comment]
Same here. I was searching for a user icon and was disappointed for zero results. Later is found out that "person" was the right search term.

**Comment by mdo** [comment]
Yup, I'm going to see about replacing our current filter-search with Algolia so we can get something faster and more accurate.

**Comment by coliff** [comment]
The search does bring up results for the tags of icons, so searching for 'avatar', 'human' or individual' will show the 'person' icon.
https://icons.getbootstrap.com/icons/person/
I think we simply need to add the tag: 'user' to the person icons, and maybe add the tag: 'location' to the compass, geo and map icons. I don't think adding Algolia would help with that.

**Comment by ffes** [comment]
Adding `sun` to various brightness icons would also be useful, maybe add a tag like `night` to the moon icons. I was looking for them for a light/dark mode switch.

Seems an easy PR since they are mentioned in the `docs/content` directory. I see what I can do to add some tags I missed myself.

**Comment by mdo** [comment]
Thanks @ffes, that'd be awesome!
