### ISSUE TITLE
Cars, Memberships and groups

### ISSUE THREAD

**Issue by orjanalmen** [twbs/icons#457]
I’d love to see icons for cars, in profile with a few different types like sedan, hatchback, van, suv, station wagon, sports car etc. Also some other car and road related signs, like car wash, garage/workshop, car rental, tire, speedometer/gauges, steering wheel, airbag, baby seat, drawbar/hook, gas/petrol pump, electric car, manual and automatic transmission, charging points and so on.

Some more icons about groups and membership is also welcome

**Comment by mdo** [comment]
Closing this out for now as it's a little old and I've tackled quite a few things here. Unsure how much I'll get into individual car types or specific parts. More coming in v1.10.0 for other vehicles (taxi and EV).
