### ISSUE TITLE
 Adding Bootstrap icons to AdobeXD

### ISSUE THREAD

**Issue by diogui** [twbs/icons#468]
Probably this is not the place to post this request, but I didn't find a better one.
While doing mockups I would like to use Bootstrap Icons. To do so, I use a sw called [Nucleo](https://nucleoapp.com), to manage all my icons. 

The problem: when I add Bootstrap icons to Nucleo, the icons are so small that they are invisible, making very hard to use bootstrap icons during the mockup phase.
The request: bigger svg icons to import to Nucleoapp. 
![Screen Shot 2020-10-26 at 16 23 07](https://user-images.githubusercontent.com/875776/97199120-8dbec880-17a7-11eb-8375-cc6bc7ebfdeb.jpg)

**Comment by mdo** [comment]
Icons are drawn at a single size right now with no plans to expand them all to multiple sizes.
