### ISSUE TITLE
Adjust the P in the PowerPoint icon

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/icons#472]
The letter P in the PowerPoint icon looks a bit like a lowercase "p" while Microsoft uses an uppercase P as the letter in their icon.

The p-letter in the Bootstrap Icons has an what in typography is known as an "ascender".

**Comment by mdo** [comment]
Yeah, I can get behind that. I wasn't feeling the capital P when I first made this, but I'm happy to revisit.
