### ISSUE TITLE
Record

### ISSUE THREAD

**Issue by cesaric** [twbs/icons#474]
Record in regards to media (playback, record...) would be helpful.  Here's a few ideas that would be a good start:

1. Standard record (similar to the existing Bootstrap bullseye but with fewer concentric circles.
2. Record audio (mic icon with a circle overlay)
3. Record video  (camera/video icon with a circle overlay)

**Comment by mdo** [comment]
We have new record icons with v1.2.0, so closing this one out. No plans to currently add record indicator over other devices right now.
