### ISSUE TITLE
add flex icons : for flex layout 

### ISSUE THREAD

**Issue by joebnb** [twbs/icons#478]
horizontal:
![image](https://user-images.githubusercontent.com/1646883/97829298-99107780-1d04-11eb-89dd-a505d5324fe4.png)
vertical:
![image](https://user-images.githubusercontent.com/1646883/97829369-ce1cca00-1d04-11eb-9e40-4fd421d53b56.png)

could twbs extend to support flex layout ,align items and justify content,such as space between,space-around

https://developer.mozilla.org/de/docs/Web/CSS/justify-content
https://developer.mozilla.org/de/docs/Web/CSS/align-items

**Comment by mdo** [comment]
Skipping this for now, not sure there's much value in filled squares beyond that shapes we already provide.
