### ISSUE TITLE
How to remove icons from bootstrap-icons.svg?

### ISSUE THREAD

**Issue by farooqkz** [twbs/icons#486]
There is a guide on adding SVGs but no guide I can find for removing them from the library. A web application won't need ALL icons in the library so I think there should be either a way to remove them from the library or a way to compile the library with *just* icons which are needed.

**Comment by bastienmoulia** [comment]
You can use a tool like https://github.com/mrmlnc/svg2sprite-cli to generate the SVG sprite with only the icons you need.
