### ISSUE TITLE
README missing an image

### ISSUE THREAD

**Issue by Anthonyive** [twbs/icons#487]
- Operating system and version: macOS 10.15.7
- Browser and version: Safari 14.0

![Screen Shot 2020-11-09 at 11 55 27 AM](https://user-images.githubusercontent.com/8257285/98589663-76d9a500-2282-11eb-9768-089653384395.png)

**Comment by mdo** [comment]
Fixed in 0babd79dde4286e69ba16e03d6ff5c9967e99321.
