### ISSUE TITLE
Calendar-today

### ISSUE THREAD

**Issue by henjoh75** [twbs/icons#493]
I created a today-icon based on calendar-event.svg and arrow-left-short.svg and thought I'd share it with you. I saw another suggestion in issue 212, but I think my version is more clear. The idea is borrowed from the today icon in MS Outlook.

![calendar-today](https://user-images.githubusercontent.com/7062692/99235498-36d07000-27f6-11eb-9df8-131925a9c434.png)

[calendar-today.zip](https://github.com/twbs/icons/files/5545249/calendar-today.zip)

**Comment by mdo** [comment]
I think we're covered here for now with an the `calendar-event` icons that show a single event/day.
