### ISSUE TITLE
Universal Access Icon

### ISSUE THREAD

**Issue by juliolopez78** [twbs/icons#498]
Please add a universal access icon to this set. Something like the [Apple accessibility icon](https://developer.apple.com/assets/elements/icons/accessibility/accessibility-128x128_2x.png) or the [Font Awesome universal access icon](https://fontawesome.com/icons/universal-access?style=solid).

Thank you!

**Comment by lacutah** [comment]
Seconded - this would work for my use case and is free to use / already made but seems intended for the physical world: http://accessibleicon.org/#use - the other suggestions would be fine as well, I'm not sure of the semantic difference between the symbols.
