### ISSUE TITLE
Better sized "x" and plus

### ISSUE THREAD

**Issue by quasipickle** [twbs/icons#508]
The bare (ie: not framed in a square or circle) `.x` and `.plus` are not sized the same as arrows.  A bare arrow icon is the full size, 1em, while the apparent visual size of bare `.x` and `.plus` are about half that - 0.4375em and 0.5em respectively.

The bare arrows on the other hand, `.arrow-down` for example, are the full size, with `.*-short` denoting the arrows that are the same size as those used in the framed versions.

As there is currently no way to have a `.x` or `.plus` icon match the visual size of corresponding text, I request that `.x` and `.plus` be expanded to full 1em size, and new `.x-small` and `.plus-small` icons be added for those that want icons the same size as those in the framed versions.

**Comment by Prazdnik** [comment]
Is there any update on this issue?

**Comment by mdo** [comment]
> Is there any update on this issue?

If there was, you'd see it here ;).

**Comment by quasipickle** [comment]
> > Is there any update on this issue?
> 
> If there was, you'd see it here ;).

I think maybe he was wondering if the project thinks this is a good idea and will move forward, or if not and this will be closed.  It has been a couple of months without any feedback.
