### ISSUE TITLE
suggest use `bsi-` as icon-fonts class prefix

### ISSUE THREAD

**Issue by charescape** [twbs/icons#544]
#### Reason 1: Following bootstrap v5.0 data attributes namespace

> https://getbootstrap.com/docs/5.0/migration/#javascript
> Data attributes for all JavaScript plugins are now namespaced to help distinguish Bootstrap functionality from third parties and your own code. For example, we use `data-bs-toggle` instead of `data-toggle`.

#### Reason 2: Naming meaning

`bs` means bootstrap while `i` means icon

<hr>

before: 

```html
<i class="bi-alarm"></i>
```

after: 

```html
<i class="bsi-alarm"></i>
```

**Comment by mdo** [comment]
No plans to change this—it would be a breaking change and require a major release.
