### ISSUE TITLE
Remove Bootstrap's Sass map file

### ISSUE THREAD

**Issue by silvioprog** [twbs/icons#549]
It would be nice to provide the map file when installing the Bootstrap Icons via `npm i bootstrap-icons`. It would be useful to avoid warnings like the following:

```
DevTools failed to load SourceMap: Could not load content for http://localhost:3000/client/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

cheers

**Comment by mdo** [comment]
This isn't the `bootstrap-icons` map file fwiw, it's from Bootstrap's minified and purged CSS. It'll go away though with #547.

**Comment by silvioprog** [comment]
@mdo, After adding the `bootstrap.min.css.map` it solved the problem. Thank you very much! 😃
