### ISSUE TITLE
'Pin' Icon

### ISSUE THREAD

**Issue by Prazdnik** [twbs/icons#557]
Would it be possible to add a "**Pin**" icon? Like this https://www.flaticon.com/free-icon/pin_889668?term=pin&page=1&position=19
![image](https://user-images.githubusercontent.com/10244929/102332673-fb74bd00-3fbe-11eb-9e55-6b68ab1b95cc.png)

**Comment by ffes** [comment]
Looks like a dup of #257 to me

**Comment by mdo** [comment]
Ayy, that's right. Duplicate of #257.
