### ISSUE TITLE
Docs: show how to deploy with CDN

### ISSUE THREAD

**Issue by fulldecent** [twbs/icons#558]
CDN deployment is already support for Bootstrap. This is a simple and DRY strategy that also allows caching across many sites using Bootstrap.

> When you only need to include Bootstrap’s compiled CSS or JS, you can use jsDelivr.
> 
> https://getbootstrap.com

Please add similar support in the Bootstrap Icons documentation.

The same preferred CDN network also hosts Bootstrap Icons here https://www.jsdelivr.com/package/npm/bootstrap-icons?path=font%2Ffonts

**Comment by ccamiloo** [comment]
Version 1.2.2 is out now and not fixed this is the docs, I suggest to add in the usage section, this CDN:

`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.2.2/font/bootstrap-icons.css">`

**Comment by redbastie** [comment]
Would be awesome if you could have the CDN CSS minified as well.
