### ISSUE TITLE
Book icon code not showing the right icon

### ISSUE THREAD

**Issue by Tim-arts** [twbs/icons#559]
- Operating system and version Windows 10
- Browser and version: Chrome Version 87.0.4280.88 (Official Build) (64-bit)

When using the code of the book [icon ](https://icons.getbootstrap.com/icons/book/), the icon shown is the [book-fill](https://icons.getbootstrap.com/icons/book-fill/). However, when using the svg format, the right icon is displayed.

Code:
![image](https://user-images.githubusercontent.com/10064887/102392316-e8ed8a00-3fa4-11eb-8013-b178c59e0104.png)

Result:
![image](https://user-images.githubusercontent.com/10064887/102392300-e3903f80-3fa4-11eb-89fb-d9d9d036c4d8.png)

Expected result:
![image](https://user-images.githubusercontent.com/10064887/102393709-bb094500-3fa6-11eb-8586-29ccfe4e1b71.png)

**Comment by ffes** [comment]
Looks like a dup of #545 to me
