### ISSUE TITLE
Why not add alias for icons

### ISSUE THREAD

**Issue by ayoubkhan558** [twbs/icons#564]
Why not add alias for icons, As currently there is images icon, but if we search for gallery nothing appears, It should should images icon as alternative. 

![image](https://user-images.githubusercontent.com/20210961/102705769-f2dee980-423f-11eb-8aec-461cf3c7da53.png)
![image](https://user-images.githubusercontent.com/20210961/102705776-012d0580-4240-11eb-9acc-07552a828a46.png)

I think this can be achieved by adding tags with icons

**Comment by mdo** [comment]
There are aliases in the `.md` files. If something's missing, please submit a PR to add it :).

**Comment by ayoubkhan558** [comment]
@mdo but we should be able to search using alias. So we can quickly search similar or alternative icon.

**Comment by mdo** [comment]
You can do this today. For example, search for email and you'll see icons without `email` in the name.
