### ISSUE TITLE
[v1.2] React - Cannot modify width and height without viewBox='0 0 16 16'

### ISSUE THREAD

**Issue by anhtran** [twbs/icons#565]
import StarFilledIcon from 'bootstrap-icons/icons/star-fill.svg'
    <StarFilledIcon
        width={48} height={48}
        viewBox='0 0 16 16'
      />

**Comment by mdo** [comment]
As far as I know, that's correct behavior. My understanding is `viewBox` gives SVGs a set of coordinates to map their values against for rendering the graphics.
