### ISSUE TITLE
intersect image changed to front image

### ISSUE THREAD

**Issue by edgwork** [twbs/icons#594]
Hi,

Download version 1.2.2 and when open front/index.html file in my browser, I see that the "intersect" image displays the "front" image, check and I see that the SVG file is correct, apparently when generating the fonts, it is when they are changed not I have still identified the problem

Regards

**Comment by mdo** [comment]
They're basically the same icon for the foreseeable future.

**Comment by edgwork** [comment]
If the css style is used **bi-intersect** it presents the image **bi-front** instead of the correct bi-intersect

<i class="bi bi-intersect"> display the front icon font glyph instead of the intersect icon font glyph

![bi-intersect](https://user-images.githubusercontent.com/70344220/103236202-de6ab300-4909-11eb-82eb-5ff9af8fcf71.png)

Sorry my english

**Comment by mdo** [comment]
Ah sorry, I was looking at another icon. Confirmed the fill-rule problem is affecting this icon.
