### ISSUE TITLE
The news headline on the site does not lead to the latest release

### ISSUE THREAD

**Issue by Prazdnik** [twbs/icons#595]
Hello, on your [website ](https://icons.getbootstrap.com/) on label header old version. The link does not lead to the last blog post. This is a minor and non-critical bug. I wish you a good Christmas.
![image](https://user-images.githubusercontent.com/10244929/103060153-c75e5500-45d9-11eb-95be-762f2684ab3b.png)

**Expected Behavior:**
![image](https://user-images.githubusercontent.com/10244929/103060237-1efcc080-45da-11eb-96f7-52837b634fc2.png)

**Comment by mdo** [comment]
Icon fonts, social icons, and media icons were added in v1.2.0, not in v1.2.2. This is left as-is intentionally. Thanks, though!
