### ISSUE TITLE
Reply icons are backwards?

### ISSUE THREAD

**Issue by johnaau** [twbs/icons#604]
The reply icons all point towards the right, but in all email applications I checked reply icons point to the left, and forward icons point to the right.

Can these be reversed horizontally, as a forward icon does not make much sense when they are all put together and they all point to the right?

![Capture](https://user-images.githubusercontent.com/6590573/103158483-7be2bb80-4812-11eb-8924-99e3827e5d03.JPG)

![Capture2](https://user-images.githubusercontent.com/6590573/103158484-7e451580-4812-11eb-9084-7b05aa8fc2d0.JPG)

![Capture3](https://user-images.githubusercontent.com/6590573/103158507-bea49380-4812-11eb-9788-de36fe415410.JPG)

**Comment by Gh-Moradi** [comment]
You can use this class:
```
.flip-horizontal {
	-ms-filter: "progid:DXImageTransform.Microsoft.BasicImage(rotation=0, mirror=1)";
	-webkit-transform: scale(-1, 1);
	-ms-transform: scale(-1, 1);
	transform: scale(-1, 1);
}
```
