### ISSUE TITLE
some ICONS are solid？

### ISSUE THREAD

**Issue by wutao9510** [twbs/icons#612]
some ICONS are solid？bootstrap-icons #
for example, a hollow black ring becomes a solid black ball.

**Comment by mdo** [comment]
This was an issue with v1.2.0 and I fixed the majority of it with v1.2.2. Please be more specific as to which icons are issues, and which version of the project you're using.

**Comment by wutao9510** [comment]
yeah，i'm using the 1.2.1 version bootstrap-icons, such as series of card-* all becomes solid block！and, is this not the problem with version 1.2.2? looking forward to your repair soon, otherwise we will have to give up this too icon, although I prefer this set of ICONS

**Comment by wutao9510** [comment]
yeah，i'm using the 1.2.1 version bootstrap-icons, such as series of card-* all becomes solid block！and, is this not the problem with version 1.2.2? looking forward to your repair soon, otherwise we will have to give up this too icon, although I prefer this set of ICONS




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "twbs/icons"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月30日(星期三) 凌晨2:07
收件人:&nbsp;"twbs/icons"<icons@noreply.github.com&gt;;
抄送:&nbsp;"羽翼畅畅"<yuycc@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [twbs/icons] some ICONS are solid？ (#612)





 
This was an issue with v1.2.0 and I fixed the majority of it with v1.2.2. Please be more specific as to which icons are issues, and which version of the project you're using.

**Comment by mdo** [comment]
This was fixed in v1.2.2. https://blog.getbootstrap.com/2020/12/23/bootstrap-icons-1-2-2/
