### ISSUE TITLE
Graduation cap icon

### ISSUE THREAD

**Issue by Skyost** [twbs/icons#637]
It would be great from you if you could add an icon related to graduation ; something like this :

<img src="https://svgur.com/i/Wf3.svg" height="200" />

([PNG](https://user-images.githubusercontent.com/3882599/103566480-5c0e6000-4ec2-11eb-9ae6-09830962b176.png), [Credits](https://fontawesome.com/icons/graduation-cap?style=solid))

Thanks !

**Comment by vanillajonathan** [comment]
Related (but different) issue  #1033 deals with other hats such as fedora and hard hat (construction worker helmet).

**Comment by vanillajonathan** [comment]
v1.7.0 have a graduation cap icon called mortarboard, I do think "graduation cap" would be a better name though.
