### ISSUE TITLE
Add Windows, Microsoft, Apple, And Gmail Icons plz

### ISSUE THREAD

**Issue by Muaath5** [twbs/icons#638]
Add Windows, Microsoft, Apple, And Gmail Icons plz

**Comment by abumosaab** [comment]
Outlook icon as well.

**Comment by Muaath5** [comment]
> Outlook icon as well.

I mean Microsoft logo, like image here:

![Microsoft logo](https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1Mu3b?ver=5c31)

**Comment by kylek14** [comment]
@mdo As discussed on Reddit over the course of today, could you assign this issue to me? Additionally, do you want to merge issues #853 and #805 into this issue?

**Comment by mdo** [comment]
I have Mastodon, Skype, Reddit, and FB Messenger already done for v1.5.0 so you can skip those :)
