### ISSUE TITLE
External link icon

### ISSUE THREAD

**Issue by nemoo** [twbs/icons#642]
Please add an 'external link' icon. It is very common in in-house web applications which is where Bootstrap has a lot of users.

**Comment by mdo** [comment]
https://icons.getbootstrap.com/icons/box-arrow-up-right/ might work? Could also look at alternative options though :).

**Comment by nemoo** [comment]
I might work. The arrow seems pretty dominant compared to other "external link" icon implementations, though.

Strange that I didn't find it via the website search. It would be cool if whatever we use in the end is also searchable on the website with the semantic meaning "external link".
