### ISSUE TITLE
? question too small

### ISSUE THREAD

**Issue by AverTry** [twbs/icons#688]
Before opening, [search for duplicate or closed issues](https://github.com/twbs/icons/issues?utf8=%E2%9C%93&q=is%3Aissue).

As appropriate, please include:

- Operating system and version (Windows, macOS, Android, iOS) Win10Pro latest
- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser) Brave

Loaded in HTML via CDN - `<i class="bi-alarm"></i>` - Like this.
1. Question (?) icon too small
2. All Icons appear below center.

Went back to Font Awesome, :(

**Comment by lofwyr14** [comment]
The exclamation (!) is also too small. Would be nice to see larger ones. See screenshot from docs:

<img width="388" alt="exclamation" src="https://user-images.githubusercontent.com/8048454/105319044-949d8180-5bc4-11eb-8a64-5a8fc27f63df.png">
