### ISSUE TITLE
"mic-fill" and "mic" are similar

### ISSUE THREAD

**Issue by HNafiii** [twbs/icons#707]
![IMG_20210122_222748](https://user-images.githubusercontent.com/76960651/105513939-83a85980-5d05-11eb-8d8a-9780d4d9d3cc.JPG)

Hello Bootstrap

I have opened the offline icon gallery at Chrome after exttact the package. I've got a exact similarity the "mic-fill" and "mic". Previouly, I've found a similarity the "file-earmark-ppt" and "file-earmark-slides" etc. Please fix the icon that mentioned before.

Thanks

#FileEarmarkPPTIcon #FileEarmarkSlidesIcon
#MicFillIcon #MicIcon

**Comment by anitaparmar26** [comment]
I have the same Issue...looking for an update soon
