### ISSUE TITLE
bootstrap web fonticons not working properly 

### ISSUE THREAD

**Issue by armanab** [twbs/icons#714]
I have problem bootstrap 4 or 5 some svg web font icons not working

for example :

```
<i class="bi bi-star-fill"></i>
<i class="bi bi-star"></i>
```

**Comment by mdo** [comment]
Please provide a live demo of the problem via CodePen or JSBin.

**Comment by armanab** [comment]
Thank you for your answer.
My problem was solved.
I did not enter the  `bootstrap-icons.css` file reference

https://codepen.io/armanab/pen/NWbrPMg
