### ISSUE TITLE
Please delete master branch

### ISSUE THREAD

**Issue by ffes** [twbs/icons#715]
A while ago you switch to use `main` as the main branch. But the `master` branch is still available on GitHub: https://github.com/twbs/icons/branches

Could you please remove the unused `master` branch?

It is quite annoying especially for new use to new users. What is the right branch to keep up to date with?
And my autocompleting muscle memory (type `ma` and press `Tab`) doesn't work.

**Comment by mdo** [comment]
Done!

**Comment by ffes** [comment]
> Done!

Are you sure?
When I look at https://github.com/twbs/icons/branches/stale I still see the `master` branch.
