### ISSUE TITLE
Jet, Aeroplane Icon Request

### ISSUE THREAD

**Issue by ayoubkhan558** [twbs/icons#724]
Some examples are

![image](https://user-images.githubusercontent.com/20210961/106947014-b6c3f300-66de-11eb-9191-ea92146dfc6e.png)
![image](https://user-images.githubusercontent.com/20210961/106947031-bb88a700-66de-11eb-969a-000cfaa8e026.png)
![image](https://user-images.githubusercontent.com/20210961/106947061-c5120f00-66de-11eb-8c99-20cdc59cbe1a.png)

**Comment by mdo** [comment]
#106
