### ISSUE TITLE
Speedometer and Speedometer2 don't work

### ISSUE THREAD

**Issue by ryangriggs** [twbs/icons#738]
They simply don't load.  Sometimes they render as the "missing character" symbol, other times simply blank. Replace the name with another icon from the pack and it works fine.

**Comment by mdo** [comment]
They show in https://icons.getbootstrap.com/font/ and on their individual pages at https://icons.getbootstrap.com/icons/speedometer2/ and https://icons.getbootstrap.com/icons/speedometer/. Perhaps you're using the wrong version?

**Comment by ryangriggs** [comment]
Used the latest CDN links.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Ryan Griggs
Hilltop Computing
www.hilltop.net
859-328-3223
Toll Free: 1 (888) 5-HILLTOP (888-544-5586)

**Comment by mdo** [comment]
https://codepen.io/emdeoh/pen/QWGExmZ

**Comment by ryangriggs** [comment]
Hmm, I guess you're right - I used your CDN url and it's working.  Thanks!

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Ryan Griggs
Hilltop Computing
www.hilltop.net
859-328-3223
Toll Free: 1 (888) 5-HILLTOP (888-544-5586)
