### ISSUE TITLE
Font Display: Swap

### ISSUE THREAD

**Issue by riyuk** [twbs/icons#783]
Would it be possible to add a 
```font-display: swap;``` in the CSS-Definition?

Google provides a explaination for this here: https://web.dev/font-display/

**Comment by RubenVerg** [comment]
How would a system font provide a decent fallback for an icon font?

- RubenVerg ❤️


________________________________

**Comment by coliff** [comment]
The `font-display` descriptor has no valid value that is compatible with icon fonts.

https://www.zachleat.com/web/font-display-icon-fonts/

**Comment by mdo** [comment]
Closing per above comments.
