### ISSUE TITLE
Keyboard keys

### ISSUE THREAD

**Issue by aentwist** [twbs/icons#784]
For instructions and prompts, it might be nice to have keyboard key icons. At the simplest, these icons would be something like two concentric `bi-square` s with a text label. There are more options to add shape and depth to these as a design choice. Shadows should be avoided for consistency with the Bootstrap Icons set.

After designing the base 1U keycap, choosing a font, and positioning it, adding the text would be the only difference between all the 1U keys.

Please see [Google Images](https://www.google.com/search?q=keyboard+key+icons&tbm=isch) for a better understanding of the design choices and feasibility.

**Comment by RubenVerg** [comment]
Do we actually even have all symbols for the "special" keys? (eg helm for CTRL, those ISO ones)
I'd do those first

- RubenVerg ❤️


________________________________

**Comment by aentwist** [comment]
True, there are some that _could_ be used like [`arrow-left-right`](https://icons.getbootstrap.com/icons/arrow-left-right/) and [`arrow-return-left`](https://icons.getbootstrap.com/icons/arrow-return-left/), but the symbols are not really there.

**Comment by mdo** [comment]
Going to skip this one since we have the symbols for these modifier/special keys. No plans to do the nested boxes that look like actual keys.

**Comment by shaunroselt** [comment]
I'd like to have icons for different keyboard keys also.

The one I currently need is for the Enter key. So something like this:
![image](https://user-images.githubusercontent.com/5418178/177148859-2f86f3f8-2d9a-4869-8ef8-3505e778156e.png)
![image](https://user-images.githubusercontent.com/5418178/177148915-1d675ac4-4a99-41d5-9401-9339012a5b1d.png)
![image](https://user-images.githubusercontent.com/5418178/177148978-f89f81c0-ed7d-4568-879f-5c98bce6447c.png)
