### ISSUE TITLE
Please add GitLab icon

### ISSUE THREAD

**Issue by ffes** [twbs/icons#785]
Please add a GitLab icon.

The official SVG can be found at: https://about.gitlab.com/press/press-kit/

**Comment by lesander** [comment]
+1

**Comment by emmahsax** [comment]
I would also love a GitLab icon.

**Comment by princefishthrower** [comment]
Thirded 👍

**Comment by leonardwoo** [comment]
When will this issue be fixed?

**Comment by matrndev** [comment]
This is taking way too long. Please accept #1587...

**Comment by nsde** [comment]
Preview:

![gitlab-logo-600](https://user-images.githubusercontent.com/67185896/218836308-6fab4a22-4096-40cb-96de-3d98f4104385.svg)
