### ISSUE TITLE
Geo Icons turned into thumbs up

### ISSUE THREAD

**Issue by criting** [twbs/icons#789]
Suddenly all the geo icons I use on my website are displayed as a thumbs up, no issues with the other icons.

Does anyone have the same problem?

bi bi-geo-alt looks like a shopping cart
bi bi-geo-alt-fill looks like a thumbs up

Latest version of Bootstrap Icons.

**Comment by bastienmoulia** [comment]
Your bug is due that CSS content of icons are not the same in v1.3 and v1.4

Version 1.3
```
.bi-geo-alt-fill::before { content: "\f3c7"; }
.bi-geo-alt::before { content: "\f3c8"; }
```

Version 1.4
```
.bi-geo-alt-fill::before { content: "\f3e7"; }
.bi-geo-alt::before { content: "\f3e8"; }
```

A quick fix for you is to get the new bootstrap-icon.css file.
But the big issue is to keep the same content between versions if possible.

**Comment by criting** [comment]
Thank you! Decided to switch to alternative, but I'm glad you pointed the issue.
