### ISSUE TITLE
How to import the icons into a existing html

### ISSUE THREAD

**Issue by tiger2014** [twbs/icons#790]
Hi guys, 

You know we can import a CSS style into an html using "link rel='stylesheet'...."
     <link rel="stylesheet" href=".../bootstrap.min.css">
but I don't find the same import method on your page (https://icons.getbootstrap.com/). there is only an 'npm i bootstrap-icons'. I never use this.
Could you afford a method like using "link rel='stylesheet'...."

Thanks.

**Comment by coliff** [comment]
The [instructions are there in the CDN section](https://icons.getbootstrap.com/#cdn):

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
```
Then you can use the icon font like `<i class="bi-alarm"></i>` etc...
