### ISSUE TITLE
How to use Bootstrap Icons as CSS content, like :before or :after?

### ISSUE THREAD

**Issue by XIAOXIAOSIYU** [twbs/icons#794]
I couldn't find any information related to my question on our website, is that possible?

Thank you.

**Comment by korki43** [comment]
You can add bootstrap icons as `background-image` in `::before` and `::after`. You can either load them from an url or use a data uri for the svg. Here's an example: https://codesandbox.io/s/stupefied-sun-j67oh?file=/index.html.

**Comment by mdo** [comment]
Yup, that's right. Our icon font also works with this approach for what's it worth. Check out the dist files we include here.

**Comment by XIAOXIAOSIYU** [comment]
My apologies for the late reply! Thank you @korki43 for your help, but I know this approach, maybe I'm not clarify myself, I mean use our icon's unicode in the content, like content:"\f36c", not use it as background.

**Comment by korki43** [comment]
Sorry, I misunderstood you there. I don't think the unicode ranges are documented but you can view them here: 
https://github.com/twbs/icons/blob/33d0a8cf4859eb59e748e0e0fb294f672b909526/font/bootstrap-icons.css#L21-L1345

I think this file is generated and the codepoints will likely change in later versions of this project.

**Comment by XIAOXIAOSIYU** [comment]
@korki43 Very appreciate, this is exactly what I'm looking for. thank you.
