### ISSUE TITLE
CSS content of icons change between versions

### ISSUE THREAD

**Issue by bastienmoulia** [twbs/icons#799]
Following #789

In version 1.4, css icons which are after the new ones have a different css content value.

https://github.com/twbs/icons/compare/v1.3.0...v1.4.0#diff-94e7b9ffcf737b7ed500e63bc55fe10c91b2a6127da40f4dfa0e39b9027f6f33

It can be a problem if we use custom CSS with the fonts from NPM or another CDN.
Is it possible to add the icons in the font with new values not already taken?

**Comment by mdo** [comment]
I'll have to look if Fantasticon has an option for that.

**Comment by bastienmoulia** [comment]
@mdo Something like this in `.fantasticonrc.js`
```js
const codepoints = require("./font/bootstrap-icons.json");

module.exports = {
  ...
  codepoints: codepoints,
};
```
can work but the `bootstrap-icons.json`as to exist.
