### ISSUE TITLE
Programming & Coding Icons

### ISSUE THREAD

**Issue by ayoubkhan558** [twbs/icons#812]
Need programming coding icons.

- Programming languages
PHP, JavaScript, JQuery, 

- PHP
- JQuery
- JavaScript
- NodeJS
- HTML 5
- CSS3
- Python
- Java
- Kotlin
- TypeScript
- C++
- Rust
- C#
- Swift
- Perl
- Scala
- Ruby

-- TOOLS / Software's

- wordpress
- Gulp
- Grunt
- NPM
- Bower
- Yarn
- VS Code
- MySQL
- Xampp
- Wampp

**Comment by dk-raw** [comment]
That sounds great.

**Comment by vanillajonathan** [comment]
I don't believe the library-specific ones such as jQuery is any useful. Nor do I believe any of the tools/software-specific icons would be of any use.

I can imagine the language ones could be of some use, particularly the ones for JavaScript, HTML and CSS.

**Comment by stankastanek** [comment]
> jQuery is not a programming language, it is a JavaScript library. I don't believe the library-specific ones such as jQuery is any useful. Nor do I believe any of the tools/software-specific icons would be of any use.
> 
> I can imagine the language ones could be of some use, particularly the ones for JavaScript, HTML and CSS.

I fully share. but then Json, XML, and CSV would also make sence here so would be as set og languages and format types

**Comment by vanillajonathan** [comment]
> I fully share. but then Json, XML, and CSV would also make sence here so would be as set og languages and format types

Yes, file format types would be something that could be useful such as .txt, .md, .pdf, .json, .xml, etc, or types such as image, video, audio, text, and binary.

**Comment by shaunroselt** [comment]
I would very much like this.

I need a Delphi icon please.

https://en.m.wikipedia.org/wiki/Delphi_(software)

![image](https://user-images.githubusercontent.com/5418178/150018504-97c8334c-2abd-45af-8056-fac341423122.png)
