### ISSUE TITLE
Requests: shopping cart, shopping bag, shopping basket

### ISSUE THREAD

**Issue by xcartmods** [twbs/icons#83]
shopping cart
shopping bag
shopping basket

:)

**Comment by mdo** [comment]
Commerce related icons are being worked on for next release I hope. Here's a teaser of what's coming thus far.

![Screen Shot 2020-03-23 at 12 49 46 PM](https://user-images.githubusercontent.com/98681/77357104-d5a6da00-6d04-11ea-8518-ffc2a3b2766e.png)
