### ISSUE TITLE
Icons weight

### ISSUE THREAD

**Issue by danny007in** [twbs/icons#834]
How to change style
like
![image](https://user-images.githubusercontent.com/50356015/112975771-ade91e00-9171-11eb-9cf3-2425dc454f17.png)

**Comment by KonradDeskiewicz** [comment]
Unfortunately BI doesn't have "weight" separation like FA. Unfortunately, until the next major version, I don't think they will do something better like `bif bi-line` and `bil bi-circle`...

**Comment by mdo** [comment]
There's only a single weight at this time. Unsure when we'll add multiple weights, so closing out.
