### ISSUE TITLE
Bootstrap 4  Icons are not working  v1.4   Visual Studio 2017    

### ISSUE THREAD

**Issue by GoodSenseDomain** [twbs/icons#836]
I believe this may have worked in Visual Studio Code with Angular CLI. 

I'm using Visual Studio 2017 Community. 
ASP.NET MVC C#.    This is NOT a CORE solution.

It would help with a little more documentation of the installation and usage. 

NPM init -y created my package.json files. 
I'm not sure if they were created correctly.  
There is no documentation provided to be sure. 

NPM I bootstrap-icons
Node_Modules installed with bootstrap-icons and the fon and icons subfolders, etc...

I've added the 
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
to my <head> area.

I even added the 
@import url("https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css");
to my CSS just to be sure after the link in the <head> did not work.

I went by the following example below, from the bootstrap icons webpage:

Icon font
Icon fonts with classes for every icon are also included for Bootstrap Icons. Include the icon web fonts in your page via CSS, then reference the class names as needed in your HTML (e.g., <i class="bi-alarm-clock"></i>).

This is not recognized. 
The names are not recognized by the class designation.
I've tried restarting the IDE.  
I've tried Clean and Rebuild, not that it would make a difference, but I wanted to cover all bases.

It would be nice if someone created a nice short video of the installation process and usage as shown on the site. 
Too many times people make assumptions and leave out important information.
I've followed the instructions on the page and the class designation for <I> doesn't recognize it. 

Thanks!

**Comment by mdo** [comment]
You don't need npm if you're using the CDN. There's some usage guidelines in the docs, but I'd be happy to create a guide of sorts if it'd be helpful. Have any more context you can share for your setup?

**Comment by GoodSenseDomain** [comment]
Correct.  I initially used NPM and it wasn't working.  I was getting what appeared to be error messages, so I added the CDN. 

Nothing worked. 

However, now it works. 🤷🏽‍♂️
So I will close this.
