### ISSUE TITLE
Ensure text remains visible during webfont load

### ISSUE THREAD

**Issue by 7702244** [twbs/icons#837]
When I tested my project on Google PageSpeed, I found a problem with Bootstrap Icons.
Here's how Google solves this problem: https://web.dev/font-display/
In CSS need to add `font-display: swap`

![Screenshot](https://user-images.githubusercontent.com/56172899/113620164-9ecb0a00-9662-11eb-8216-24af65bffef2.png)

**Comment by RubenVerg** [comment]
you can't swap it with any sensible default

- RubenVerg ❤️


________________________________
From: 7702244 ***@***.***>
Sent: Monday, April 5, 2021 10:01:26 PM
To: twbs/icons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [twbs/icons] Ensure text remains visible during webfont load (#837)


When I tested my project on Google PageSpeed, I found a problem with Bootstrap Icons.
Here's how Google solves this problem: https://web.dev/font-display/<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fweb.dev%2Ffont-display%2F&data=04%7C01%7C%7C04c8f062e86646f49bae08d8f86d98b0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637532496880624533%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tNHU9DcDLJbaovkOnC0Pufsvb7wyLF8HdTvC5et7I3c%3D&reserved=0>
In CSS need to add font-display: swap

[Screenshot]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F56172899%2F113620164-9ecb0a00-9662-11eb-8216-24af65bffef2.png&data=04%7C01%7C%7C04c8f062e86646f49bae08d8f86d98b0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637532496880634524%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=p72xtI8ZG20JKXc4JwRUQiwy6Qutg3dPAmZeq9AE0m8%3D&reserved=0>

**Comment by RubenVerg** [comment]
you aren't supposed to just trick the thing, font-display: swap is meant for actual fonts, not icons

- RubenVerg ❤️


________________________________

**Comment by XhmikosR** [comment]
We specify `font-display: block` for some versions now.
