### ISSUE TITLE
Floppy icon

### ISSUE THREAD

**Issue by XIAOXIAOSIYU** [twbs/icons#852]
The current 'Save' icon quite confuses people , could you please use 'Floppy' icon instead, like this the FontAwesome's?
[Like here](https://fontawesome.com/icons/save?style=regular), Thank you.

**Comment by mdo** [comment]
Still thinking I'll stick with what we have here. Will keep an eye on the requests and feedback!

**Comment by XIAOXIAOSIYU** [comment]
Understood, and thank you for your time. what if we create another 'Save' icon with floppy? let people choose which one they like?
