### ISSUE TITLE
Icon for 'directions' / 'navigation'

### ISSUE THREAD

**Issue by remonator** [twbs/icons#863]
Request to add an icon that clearly resembles 'directions'.

Inspiriation from [Google Maps](https://www.google.com/maps):
![image](https://user-images.githubusercontent.com/54318829/116684951-ea4aac80-a9b1-11eb-8d02-9e0917518c20.png)

Inspiration from [FontAwesome 5](https://fontawesome.com/icons/directions?style=solid):
![image](https://user-images.githubusercontent.com/54318829/116684889-d8690980-a9b1-11eb-8686-f848e6f8b40b.png)

**Comment by mdo** [comment]
This should be taken cafe of by the v1.10.0 update.
