### ISSUE TITLE
Rocket icon

### ISSUE THREAD

**Issue by sovetski** [twbs/icons#869]
Is it possible to add a rocket icon like this ? 

https://fontawesome.com/icons?d=gallery&p=2&q=rocket
https://materialdesignicons.com/icon/rocket

![image](https://user-images.githubusercontent.com/13520683/116909130-0b2a3080-ac44-11eb-8bc2-adf9b5f5daf1.png)

etc.

**Comment by thenewseason** [comment]
It's been Rocket Age. We can see rockets anywhere!

**Comment by elpiel** [comment]
I'd love to have a rocket icon (including firing one and leaning towards the side)
