### ISSUE TITLE
[icon request] eye-slash-half

### ISSUE THREAD

**Issue by tmorehouse** [twbs/icons#87]
I would like to see a half filled version of the eye slash icon, similar to:

![image](https://user-images.githubusercontent.com/2781561/70941908-e66bf380-2023-11ea-855b-3038bbcaf8b6.png)

**Comment by tmorehouse** [comment]
Or an `eye-slash-half`:

![image](https://user-images.githubusercontent.com/2781561/72011878-1d06e980-3231-11ea-94e4-37da6dfa2b28.png)

**Comment by mdo** [comment]
_Revisiting old issues..._ Going to skip this one, thanks though!
