### ISSUE TITLE
Add composer.json and publish to Packagist

### ISSUE THREAD

**Issue by chaziz94** [twbs/icons#877]
Hello. So i've checked the Bootstrap Icons page and it appears it's only available on NPM.

This is a bit problematic for anyone using Composer, as the only other options are:

* Download the Zip file and extract it where-ever needed.
Makes sense, but a bit bloaty for a repository, plus it doesn't automatically update.
* Use the icon font via the CDN
This makes the most sense, but on Firefox Nightly (on Windows 7) the way the newspaper icon rendered gave me an headache once.
* Copy the SVG code and use in a HTML file
Makes sense, but it's a bit of a mess and whenever an icon gets updated in a newer release you'll need to manually replace it, one at a time.

I've done some research and there are outdated packages. For example, there's an [unofficial package](https://packagist.org/packages/automad/bootstrap-icons) on Packagist but it hasen't been updated for 5 months now and is 2 major versions behind, and there's [another one](https://packagist.org/packages/aeyoll/bootstrap-icons) which seems recent-ish but it seems like it's based on 1.4.0 and not 1.4.1

**Comment by mdo** [comment]
I'll take a look and see what I can do. I don't ever use Composer, so adding stuff that I don't actively maintain always bothers me a bit.

**Comment by chaziz94** [comment]
Tested out the composer branch and everything seems to work fine.

**Comment by reinhart1010** [comment]
> Hello. So i've checked the Bootstrap Icons page and it appears it's only available on NPM.
> 
> 
> 
> This is a bit problematic for anyone using Composer, as the only other options are:
> 
> 
> 
> * Download the Zip file and extract it where-ever needed.
> 
> Makes sense, but a bit bloaty for a repository, plus it doesn't automatically update.
> 
> * Use the icon font via the CDN
> 
> This makes the most sense, but on Firefox Nightly (on Windows 7) the way the newspaper icon rendered gave me an headache once.
> 
> * Copy the SVG code and use in a HTML file
> 
> Makes sense, but it's a bit of a mess and whenever an icon gets updated in a newer release you'll need to manually replace it, one at a time.
> 
> 
> 
> I've done some research and there are outdated packages. For example, there's an [unofficial package](https://packagist.org/packages/automad/bootstrap-icons) on Packagist but it hasen't been updated for 5 months now and is 2 major versions behind, and there's [another one](https://packagist.org/packages/aeyoll/bootstrap-icons) which seems recent-ish but it seems like it's based on 1.4.0 and not 1.4.1

For anyone using **Laravel Mix** the icons can still be installed by using NPM to install `bootstrap-icons`, then importing the icons CSS file to `/resources/sass/app.scss`, before compiling it with `npm run dev`. This is the method I used for https://github.com/himtibinus/unified-registration/blob/44b102416c51f05433b2ce783e2d7a8865354b55/resources/sass/app.scss#L11.

@chaziz94 You might want to add this as another "option" on the report description.

**Comment by chaziz94** [comment]
Due to the lack of progress, I ended up making a fork of this project with Composer support that included the new changes.

**Comment by mdo** [comment]
Fixed by #1038
