### ISSUE TITLE
Additional social media icons

### ISSUE THREAD

**Issue by mdo** [twbs/icons#883]
- [ ] Pinterest
- [ ] Dribbble
- [ ] Behance
- [ ] Vimeo
- [ ] Flickr

**Comment by philipkiely** [comment]
Hey @mdo,

3 social icons I use from Font Awesome that Bootstrap icons doesn't have and I would love to see:

[] Snapchat
[] Goodreads
[] Hacker News

All three of these are popular in the developer community and I think they would be strong additions.

I know you personally design most of the icons, but seeing as these have little artistic decision-making, I would be happy to contribute them to the project if you would like following the steps in the "Adding SVGs" directory.

I would be happy to contribute any other social icons you think are necessary, too.

**Comment by vanillajonathan** [comment]
- [ ] [Element](https://element.io/) (an app, part of the Matrix network)
- [ ] GitLab
- [ ] [Gitter](https://gitter.im/)
- [ ] [Matrix](https://matrix.org/)
- [ ] [XMPP](https://xmpp.org/)

Gitter is being acquired by Element and is now part of the Matrix ecosystem.
https://blog.gitter.im/2020/09/30/gitter-element-acquisition/
