### ISSUE TITLE
Transportation icons

### ISSUE THREAD

**Issue by maciek-szn** [twbs/icons#886]
Please consider adding some transportation icons:

- car
- bus
- tram
- trolleybus
- train
- plane
- bike
- motorcycle
- ship
- etc.

**Comment by ceyquem** [comment]
agree, also it would be nice to have icons for navigation
- start navigation (an north arrow in a circle)
- sign turn left
- sign turn right
- sign yield
- sign stop

**Comment by shaunroselt** [comment]
skateboard 🛹

**Comment by we3geeks** [comment]
... and 
- fuel pump
- charging station

**Comment by mdo** [comment]
Closing as mostly done in v1.9.0. Main one missing is motorcycle, which I may come back to at some point, and if folks want it enough we can get a new issue opened for it.

**Comment by shaunroselt** [comment]
`helicopter` missing too
