### ISSUE TITLE
icon tag load issue

### ISSUE THREAD

**Issue by rezamousa** [twbs/icons#889]
Two icons are not displayed!
1-[file-pdf](https://icons.getbootstrap.com/icons/file-pdf/)
2-[file-pdf-fill](https://icons.getbootstrap.com/icons/file-pdf-fill/)
i dont try svg, i just try web font tag
my browser is Edge

**Comment by korki43** [comment]
Are you sure that you used the latest version? `file-pdf`and `file-pdf-fill` were added in v1.5.

**Comment by mdo** [comment]
Closing per above comment.
