### ISSUE TITLE
unicode code are not documented

### ISSUE THREAD

**Issue by swirly** [twbs/icons#891]
Unicode code are not documented on the main site. 
It should be, as it is very usefull to have unicode code to manage CSS with ::before and ::after (you can not insert svg but you can insert a unicode character)

**Comment by RubenVerg** [comment]
Those change on every release, so you'd have to maintain it manually anyways

**Comment by swirly** [comment]
It's a real shame. Because if you want to use it in a ::before CSS, you can only use font and unicode code. Isn't there a way to maintain them constant ?

**Comment by mdo** [comment]
As of [v1.4.1](https://github.com/twbs/icons/releases/tag/v1.4.1), the code points for each icon should no longer be changing. If there's still a bug with that, please let us know. Otherwise the generated CSS file should be the "documentation" for that :).
