### ISSUE TITLE
Cube icon

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/icons#893]
I would like a cube icon.

https://lmgtfy.app/#gsc.tab=1&gsc.q=cube%20icon

**Comment by RubenVerg** [comment]
I'm pretty sure there's an icon called box or something that is a cube

- RubenVerg ❤️


________________________________
From: Jonathan ***@***.***>
Sent: Monday, May 17, 2021 2:05:20 PM
To: twbs/icons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [twbs/icons] Cube icon (#893)


I would like a cube icon.

https://lmgtfy.app/#gsc.tab=1&gsc.q=cube%20icon<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flmgtfy.app%2F%23gsc.tab%3D1%26gsc.q%3Dcube%2520icon&data=04%7C01%7C%7C92191ecffb164c52097f08d9192c0b6a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637568499218743292%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tbQazTYhKoM968sn4BjT6mdU2dDwgrhM5%2B6IyplabNM%3D&reserved=0>

**Comment by vanillajonathan** [comment]
> I'm pretty sure there's an icon called box or something that is a cube

Oops, there it is:
https://icons.getbootstrap.com/icons/box/

My bad. Can we add a "cube" alias to it?
