### ISSUE TITLE
Enter/leave, input/output, in/out icons

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/icons#894]
Icons for enter/leave, input/output, in/out, like for mail in/out, insert/retrieve from box, etc.

Use cases:
- Enter/leave door or building
- Move in/out from building
- Mail into inbox and mail out
- Incoming and outgoing messages
- Pack item into box and unpack item from box
- Hotel: check in, check out
- Git: pull/push
- Destination: arrive/depart

In:

    ┌──────┐
    │      │
    │   <──┼───
    │      │
    └──────┘

Out:

    ┌──────┐
    │      │
    │    ──┼───>
    │      │
    └──────┘

**Comment by RubenVerg** [comment]
There's something called similar to box-arrow-right and box-arrow-right-in or similar

- RubenVerg ❤️


________________________________
From: Jonathan ***@***.***>
Sent: Monday, May 17, 2021 5:03:31 PM
To: twbs/icons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [twbs/icons] Enter/leave, input/output, in/out icons (#894)


Icons for enter/leave, input/output, in/out, like for mail in/out, insert/retrieve from box, etc.

Use cases:

  *   Enter/leave door or building
  *   Move in/out from building
  *   Mail into inbox and mail out
  *   Incoming and outgoing messages
  *   Pack item into box and unpack item from box
  *   Hotel: check in, check out
  *   Git: pull/push
  *   Destination: arrive/depart

In:

┌──────┐

│      │

│   <──┼───

│      │

└──────┘



Out:

┌──────┐

│      │

│    ──┼───>

│      │

└──────┘

**Comment by vanillajonathan** [comment]
Oh, there is: [box-arrow-in-left](https://icons.getbootstrap.com/icons/box-arrow-in-left/) and [box-arrow-in-right](https://icons.getbootstrap.com/icons/box-arrow-in-right/), as well as [box-arrow-in-left](box-arrow-in-left) and [box-arrow-right](https://icons.getbootstrap.com/icons/box-arrow-right/).

These ought to be enough for many use cases, even if a box arguably can be considered pretty ambiguous.

Perhaps there could be an alias for "in" and "out".

**Comment by vanillajonathan** [comment]
@mdo Can we have some alias for "in" and "out"?
