### ISSUE TITLE
bi-translate is not avaiable but in documentation it shows

### ISSUE THREAD

**Issue by saswat3115** [twbs/icons#902]
![image](https://user-images.githubusercontent.com/14299682/119988053-53d6ce80-bfe3-11eb-9e2f-ae7604c146da.png)

![image](https://user-images.githubusercontent.com/14299682/119988083-5cc7a000-bfe3-11eb-93a0-e161b99ed3d6.png)

**Comment by kylek14** [comment]
@saswat3115 

Can you provide any additional details? I just did a quick test page and it is appearing normally using the icon font which is what I'm assuming you're using based on the code snippet included in your screenshot.

**Code i used for testing below:**
`<header>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</header>

You should see the icon  { <i class="bi bi-translate"></i> } between these two curly braces!`

**Comment by saswat3115** [comment]
Yes got it. I was using v1.3.0. Thanks @kylek14
