### ISSUE TITLE
Undo and redo icons

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/icons#909]
These would be useful to **undo** and **redo** operations in web applications that keep state.

**Comment by mdo** [comment]
I think these work:

https://icons.getbootstrap.com/icons/arrow-clockwise/
https://icons.getbootstrap.com/icons/arrow-counterclockwise/

Let me know if there's something different you're expecting.

**Comment by michaelkirkpatrick** [comment]
I'd love to see this icon-request re-opened. I agree with @vanillajonathan -- a clockwise arrow doesn't imply undo. macOS and Windows use a U shaped arrow (similar to the icons above) that better communicates "undo" which is a "go back" style action vs a circular action.
