### ISSUE TITLE
Refresh icon

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/icons#910]
This would be useful to refresh/reload content.

It would be arrow with a circular shape. As is common in web browsers that have back, forward and refresh buttons.

**Comment by mdo** [comment]
https://icons.getbootstrap.com/icons/arrow-clockwise/

**Comment by vanillajonathan** [comment]
@mdo Can we get the words "refresh" and/or "reload" added to the metadata on this icon in order to make it easier to find?
