### ISSUE TITLE
Icon fonts not showing on Heroku

### ISSUE THREAD

**Issue by viktorsmari** [twbs/icons#914]
We have a Ruby on Rails 6.1 project, using Webpacker on Heroku

The **Icon fonts** are **not showing** on Heroku, but normal SVG are working fine.
Both icons work fine on localhost

"@rails/webpacker": "5.2.1",
"bootstrap-icons": "^1.5.0" 

**Example:**
One button is using Icon font, and the other using SVG

On localhost (both are visible):
![2021-06-14_19-22-18](https://user-images.githubusercontent.com/1689020/121933391-4db45200-cd46-11eb-974b-e5dd63042439.png)

On Heroku (only SVG is visible):
![2021-06-14_19-25-50](https://user-images.githubusercontent.com/1689020/121933450-5f95f500-cd46-11eb-8072-141e79808426.png)

Heroku url:
https://new.make.works/styleguide

**Comment by mdo** [comment]
This likely isn't a bug on our end, but an implementation issue. Looks like you're missing the CSS for it? I don't see any styles being applied to the `.bi` class.

**Comment by viktorsmari** [comment]
Thanks @mdo - do you know why it's showing correctly on localhost?

I guess it's something to do with Heroku, but any tips in debugging would be great.

**Comment by mdo** [comment]
Depends on how you're including the CSS. If it's via npm, perhaps node_modules folder is missing? CSS paths could be incorrect?

**Comment by viktorsmari** [comment]
Thanks @mdo problem fixed!
Webpacker was not loading CSS in production, only in development.

If I injected this in the `<head>` using the Developer tools, it worked on Heroku:
`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">`

![2021-06-14_20-27-58](https://user-images.githubusercontent.com/1689020/121942970-624a1780-cd51-11eb-9f6e-9e9a2e91a5cb.png)

This is how the icons are imported:
https://github.com/fablabbcn/makeworks/blob/324152931ee13302856fd2b7eee763ccb8162cdf/app/javascript/packs/application.js#L11

The problem was this line was missing in our `<head>`, to make Webpacker load CSS files:
`<%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>`

This article helps explains it well:
https://stevepolito.design/blog/rails-6-bootstrap-4-webpacker-tutorial/
