### ISSUE TITLE
Inline icons don't scale with CSS without viewBox attribute

### ISSUE THREAD

**Issue by diomedtmc** [twbs/icons#919]
As appropriate, please include:

- Operating system and version: Windows 10
- Browser and version: Chrome (and others)
- Test Case:

Include an SVG from bootstrap-icons as an inline SVG.  I do this using webpack +svgr + react.  I import like this:

`import DizzySvg from 'bootstrap-icons/icons/emoji-dizzy.svg';`

I React like this:

`<DizzySvg viewBox="0 0 16 16" className="text-primary"/>`

And I style like this:

```
     svg {
        width: 400px;
        height: 400px;
     }
```
     
 First, because the viewBox is missing, it disrepects the CSS style change on dimensions (I have to add this into my React as seen above).  Second, it does not preserve aspect ratio if I only style one dimension (generally width).  All of the engineering I do these days does SVGs this way, as it allows us to pull in 1:1 the SVG into the distributable instead of the whole pack.  It also maximizes style flexibility.  Please include viewBox in the SVGs, and please work better to preserve aspect ratio by default.

**Comment by mdo** [comment]
`viewBox` is included in all our SVGs. It's part of the build process.

**Comment by diomedtmc** [comment]
Interesting…the dizzy one I mentioned above was rendering without it.  Maybe a one off bug?

**Comment by diomedtmc** [comment]
Well I'll be...I think it is being stripped!

**Comment by diomedtmc** [comment]
For reference if it ever comes up again:

https://github.com/gregberge/svgr/issues/142
