### ISSUE TITLE
Aug in icon calendar

### ISSUE THREAD

**Issue by vincentVDB** [twbs/icons#920]
The month which appears in the calendar icons is august with the first 3 letters : Aug
I think November is the month in which the first 3 letters are the most used in the main languages which use Latin characters.

Anglais : Nov-ember / Aug-ust
Espagnol: Nov-iembre / Ago-sto
Français : Nov-embre / Aoû-t
Portugais : Nov-embro / Ago-sto
Allemand : Nov-ember / Aug-ust
Italien : Nov-embre / Ago-sto

Can you change 'Aug' to 'Nov' ?

**Comment by mdo** [comment]
I'm open to it. The current date icons represent the release of Bootstrap 1.0.0, so that's how I ended up with those. I'll consider it!
