### ISSUE TITLE
I need several icons

### ISSUE THREAD

**Issue by luizcmarin** [twbs/icons#928]
I need several icons

How can I help with this? (please explain in a practical way)

Thanks you

**Comment by RubenVerg** [comment]
first of all by telling what these icons are, because maybe all of them were already requested

**Comment by luizcmarin** [comment]
Thanks for answering @RubenVerg 

But how could I help? For example, what do I need to do to submit an icon ready for evaluation?
Anyway, is it possible to participate more actively in their development than just "requesting" them?

**Comment by RubenVerg** [comment]
oh, if you want to design icons I suppose you can submit a PR, i don't know and I suppose it's the contributors' job to answer this one

**Comment by luizcmarin** [comment]
so i hope they respond at some point

**Comment by mdo** [comment]
There are issue forms for requesting specific new icons. I draw most of them myself and add them in new releases as I can :).
