### ISSUE TITLE
Technology icons request

### ISSUE THREAD

**Issue by stankastanek** [twbs/icons#930]
Hi,

could you please add some tech icons such as API, ESB, MFT, RPA, ETL, Scheduler ?

thanks

**Comment by vanillajonathan** [comment]
What does these acronyms mean in this context?

How would you imagine these  being represented?

**Comment by stankastanek** [comment]
The acronyms being the name of the technologies/Interfaces.

4 use cases I have in mind (and a need for):

- On a website where we propose the different kind of interfaces available to interact with different systems(API (Application Programming Interface, ESB (Enterprise Service Bus), MFT (Managed File Transport) or ETL (Extract Transform Load)
- On a website where you see the detailled documentation of an Interface, next to the name of the interface, we display the icont
- On a website, where you find a catalog of data (lets say anonymously pets, orders, customers,...) we display as icon the different way to read the data
- An icon in a menu to manage all the schedulled tasks (for the scheduler one) 

How I would imagine them being represented.

Either with a similar icon but different acronym such as 
![image](https://user-images.githubusercontent.com/31400389/126627032-02d56b25-7ce4-489d-b20f-e22f72958326.png)

or ideally something different and more reusable for other contexts/needs such as

RPA (Robotic Process Automation) - Actually a robot: 
![image](https://user-images.githubusercontent.com/31400389/126627151-9ec7ebe2-41b2-408f-b29a-a4da2356fca1.png)

API (Application Programming Interface) - something representing n-n generic connections:
![image](https://user-images.githubusercontent.com/31400389/126628140-47927b00-db10-459e-9d7a-c69994d55e1b.png)


ETL (Extract Transform Load) - something representing an action of tranfert with transformation :
![image](https://user-images.githubusercontent.com/31400389/126628304-24ee51dd-9843-4ec2-b0f8-7cc0b625407b.png)
or
![image](https://user-images.githubusercontent.com/31400389/126628342-b020196d-8752-4a8b-8de7-d89918c0a704.png)


ESB (Enterprise Service Bus) --> Not too far from the diagrams ones - Actually something representing a pipe with several plugs on top and others on bottom:
![image](https://user-images.githubusercontent.com/31400389/126627647-9c52ce44-67d1-424a-88e3-41fa3904332d.png)

MFT (Managed File Transfert) - Something representing a file and something either representing a transfert or a control :
![image](https://user-images.githubusercontent.com/31400389/126627782-33f745e2-f04e-47ed-966c-a839a677f51d.png)

Scheduler - Actually something representing a calendar and either an action or a timer :
![image](https://user-images.githubusercontent.com/31400389/126627956-0a452afe-d318-47fb-a874-62b60fd93803.png)

**Comment by ivan-au** [comment]
+1 on this one!  I've been using the gear icon for my automation options but a robot icon would do a much better job. I can also see a robot icon has also been requested on #577

**Comment by mdo** [comment]
These examples are quite detailed, not something we'll tackle here. Robot is coming in v1.7.0, and more device icons, too.
