### ISSUE TITLE
Coin icon in font appear as filled circle

### ISSUE THREAD

**Issue by kitvarela** [twbs/icons#939]
**OS**: Windows 10 Pro

**Browsers**: Chrome, Brave, Edge

**html used**: `<i class="bi-coin"></i>`

I have tried many other icons with no issue. Also using version _bootstrap-icons-1.5.0_

Screenshot of icon attached
![coin](https://user-images.githubusercontent.com/16439859/125175885-3e85c000-e19d-11eb-82bf-dc8127f24b18.jpg)

**Comment by Maelstorm1973** [comment]
I can confirm this.

**OS:** Windows 10 Pro 20H2
**Browsers:** Google Chrome, Mozilla Firefox

**HTML:**

```
<span class="input-group-text" id="after-test-item-1" ext-type="icon">
	<i class="bi bi-coin"></i>
</span>
```

Screenshot:

![icon_bug](https://user-images.githubusercontent.com/12518894/125483944-bc68bb62-f6ed-4394-856f-e735dcd5a64b.png)

**Comment by dk-raw** [comment]
Having the same problem here.

**Comment by hajirasyafi** [comment]
Yes I've same problem, running on chrome Version 92.0.4515.107 mac os big sur
