### ISSUE TITLE
graph-line icon

### ISSUE THREAD

**Issue by shaunroselt** [twbs/icons#940]
![image](https://user-images.githubusercontent.com/5418178/125203069-166a8f80-e277-11eb-9ee5-d75c805385e0.png)

I would like a graph-line icon. One that doesn't go up or down. Just a straight line on the graph.

**Comment by shaunroselt** [comment]
Someone please mark this as "icon-request" label 😁😅😅

**Comment by mdo** [comment]
Misunderstood this originally—thought we were missing one or the other. I don't think I'll add a straight line graph for now.
