### ISSUE TITLE
Activity Icon

### ISSUE THREAD

**Issue by shaunroselt** [twbs/icons#941]
Something like this:

![image](https://user-images.githubusercontent.com/5418178/125275428-4b2a2580-e30f-11eb-8495-794de80ac0eb.png)

**Comment by mjongbloet** [comment]
geadawdaxdvxvcxdvgeadawdaxdvxvcxdgeadawdaxdvxvcxd
geadawdaxdvxvcxd
geadawdaxdvxvcxd
