### ISSUE TITLE
Strava logo icon

### ISSUE THREAD

**Issue by honzajavorek** [twbs/icons#942]
I believe Strava is the most popular app for tracking sports activities. I'd like to add it to „social“ icons on my web so that people can join my Strava club.

Something like this: https://duckduckgo.com/?t=ffab&q=strava+logo&iax=images&ia=images

**Comment by Chaostheorie** [comment]
@honzajavorek it would be useful to maybe contact them regarding usage guidelines and copyright of their logo. Since they, most likely, own the logo it might be necessary to have permission from them before adding it to an icon set.

**Comment by honzajavorek** [comment]
That's a good idea. I [tried to contact them over Twitter](https://twitter.com/honzajavorek/status/1424668446759993344) first, if they won't reply I can try something else.

**Comment by honzajavorek** [comment]
@mdo Super cool, thanks!
