### ISSUE TITLE
Floppy save ?

### ISSUE THREAD

**Issue by josemedina760** [twbs/icons#966]
The save looks like a download for users and I had to use a svg from another library. The standard is a floppy disk, can we get a floppy in the next version ? Thanks!

**Comment by mdo** [comment]
No plans for a floppy disk icon at the moment—trying to push this floppy disk-esque one instead :).

**Comment by josemedina760** [comment]
@mdo Did you attach an image ? I'll wait for the next version hopefully something similar should help my users.

**Comment by scottkuhl** [comment]
> No plans for a floppy disk icon at the moment—trying to push this floppy disk-esque one instead :).

There have been 4 issues opened now about this. No matter what you believe or you are trying to push, this confuses users. The number one feedback I get with this icon set is where is the save?

The floppy is a universal standard.

Please stop closing these issues and provide an alternative.

**Comment by j-meds** [comment]
@scottkuhl i have moved to another icon library just because some of the norms are not there. I know they are trying to do something new and innovative but I just don’t want to confuse my users.

**Comment by mdo** [comment]
Floppy disks haven't been used in decades, I just don't see a reason to perpetuate something that's inaccurate.

> Please stop closing these issues and provide an alternative.

There are several alternatives for saving/downloading.

- https://icons.getbootstrap.com/icons/save/
- https://icons.getbootstrap.com/icons/save2/
- https://icons.getbootstrap.com/icons/download/
- https://icons.getbootstrap.com/icons/cloud-download/

**Comment by scottkuhl** [comment]
> Floppy disks haven't been used in decades, I just don't see a reason to perpetuate something that's inaccurate.
> 
> > Please stop closing these issues and provide an alternative.
> 
> There are several alternatives for saving/downloading.
> 
> * https://icons.getbootstrap.com/icons/save/
> * https://icons.getbootstrap.com/icons/save2/
> * https://icons.getbootstrap.com/icons/download/
> * https://icons.getbootstrap.com/icons/cloud-download/

It's not about you.  It's about the users.  Multiple people have opened and upvoted the issue of creating a "floppy" icon.  It's a universal standard even if it started representing something that is no longer around.

The alternatives you provided do not work.  We have run multiple tests with users.  No matter how you spin it.  They can't find the save button in this icon set.  They need a floppy!

Please, listen to the people using this icon set and just provide the icon we need.

**Comment by j-meds** [comment]
@mdo These are definitely great icons for sure, but my users thought they were download icons... Sorry I'm not trying to bash on anything but that's just some feedback I got from several companies and users. 

> Floppy disks haven't been used in decades,

Not sure where you've been but in the biggest systems floppy disk with pen is used widely. They are even used in Microsoft Azure devops which I use everyday along with million of others. Maybe just remove the down arrow from your save, that seems to be the confusion from the feedback I'm getting. Anyways the icons are beautiful I hope you can take this as insightful feedback from your users. Thanks.

**Comment by scottkuhl** [comment]
> @mdo These are definitely great icons for sure, but my users thought they were download icons... Sorry I'm not trying to bash on anything but that's just some feedback I got from several companies and users.

I completely agree with this.  There is nothing bad about the icons themselves.  Users just do not understand what they are.  For good or bad, the reality is they expect a save icon to look like a floppy.

**Comment by RubenVerg** [comment]
this thread confuses me so much. if the user's only way to tell what a button does is its icon, probably the UI isn't designed that well. there should always be a way to see a text description of what a button does for (a) accessibility and (b) clarity, especially because icons are meant to convey concepts, not the exact function the button has in your application. you get used to knowing "that thing" is a save button eventually, and if you don't, you just keep the text-showy mode on indefinitely, or go by position memory, or something.

**Comment by scottkuhl** [comment]
> this thread confuses me so much. if the user's only way to tell what a button does is its icon, perhaps the UI isn't designed that well. there should always be a way to see a text description of what a button does for (a) accessibility and (b) clarity, especially because icons are meant to convey concepts, not the exact function the button has in your application. you get used to knowing "that thing" is a save button eventually, and if you don't, you just keep the text-showy mode on indefinitely, or go by position memory, or something.

I never meant to imply we always and only use just the icon.  For example, on my latest project, which we have a team of usability and accessibility experts on, we show just the icon on toolbars.  That's a very common scenario in many applications.  You can still see the name on tooltips.  Just look at the toolbar on this site when you are writing a comment for an example.

Univeral icons such as Save, Bold, Italic, etc. save space on a screen.  It's not practical to always show the label when you have that many buttons.

https://medium.com/@Claromentis/why-icons-are-important-29dd86ac45d0

_In the technology world, icons represent a large portion of how users navigate around software or websites; we all recognise the ubiquitous “print” icon in Microsoft Word, or the “reply” icon in any email client.

Research has shown that icons, when used correctly, can enhance usability, be easily remembered, and improve the design of the webpages or software being used. On the other hand, when used incorrectly, icons can cause confusion, and completely affect the navigability for the user. If an icon is unclear in its intention, then the user won’t understand what will happen when they click it!_

I hope that helps.

**Comment by claviska** [comment]
> No plans for a floppy disk icon at the moment—trying to push this floppy disk-esque one instead :).

I absolutely love these icons, but I respectfully disagree on this point. Consider:

- We don't use [magnifying glasses](https://icons.getbootstrap.com/icons/search/) to search for things
- We don't use [hourglasses](https://icons.getbootstrap.com/icons/hourglass/) while we're waiting
- We don't use [film](https://icons.getbootstrap.com/icons/film/) in our cameras anymore
- [Bells](https://icons.getbootstrap.com/icons/bell/) don't go off when we get notifications
- We don't use paper for computer [files](https://icons.getbootstrap.com/icons/file/)
- Most of use don't have physical [calendars](https://icons.getbootstrap.com/icons/calendar/) anymore

But these are still included because, over time, they've grown to represent things and that's how we've come to understand them. The infamous floppy disk is synonymous with "save" even to younger generations that never used them. Most kids have no idea what a floppy disk is, but they know instantly what the "save icon" is.

> There are several alternatives for saving/downloading.
> 
> https://icons.getbootstrap.com/icons/save/
> https://icons.getbootstrap.com/icons/save2/
> https://icons.getbootstrap.com/icons/download/
> https://icons.getbootstrap.com/icons/cloud-download/

Unfortunately, the alternatives aren't nearly as intuitive and are easy to confuse with "download" or "share," both of which are very different from "save."

Given its prevalence and ubiquity, I respectfully ask that you reconsider allowing a floppy disk into Bootstrap Icons.

**Comment by christopherreay** [comment]
The "down" arrow means "download"

everyone I have spoken to is confused by this.

bootstrap is amazing. this is ... odd. Who is pushing this? I cant believe everyone in the bootstrap team is like "floppppieieissss sbaddddd"

**Comment by j-meds** [comment]
> > Floppy disks haven't been used in decades, I just don't see a reason to perpetuate something that's inaccurate.
> 
> I haven't seen a cassette tape in ages, yet an icon for that was released in v1.9.0 [just yesterday](https://github.com/twbs/icons/releases/tag/v1.9.0).
> 
> <img alt="CleanShot 2022-07-14 at 09 03 17@2x" width="331" src="https://user-images.githubusercontent.com/55639/178988962-1e4f1955-66ea-42cd-9682-63ca8d65ed12.png">
> 
> With all due respect, please reconsider your position on a meaningful save icon. There are a multitude of issues that @mdo continues to close that clearly indicate demand and, as I stated above, users who have never even seen a floppy disk are still more familiar with it meaning "Save" than any of the proposed alternatives.
> 
> To reiterate:
> 
> > I absolutely love these icons, but I respectfully disagree on this point. Consider:
> > We don't use [magnifying glasses](https://icons.getbootstrap.com/icons/search/) to search for things
> > We don't use [hourglasses](https://icons.getbootstrap.com/icons/hourglass/) while we're waiting
> > We don't use [film](https://icons.getbootstrap.com/icons/film/) in our cameras anymore
> > [Bells](https://icons.getbootstrap.com/icons/bell/) don't go off when we get notifications
> > We don't use paper for computer [files](https://icons.getbootstrap.com/icons/file/)
> > Most of use don't have physical [calendars](https://icons.getbootstrap.com/icons/calendar/) anymore
> 
> We're doing users a disservice by excluding it.
> 
> For reference, here are some other requests that were closed as well.
> 
> #1360 #1352 #1178 #1122 #852 #512 #277 #272
> 
> I appreciate that you may not want to draw it yourself. Are you willing to accept a PR provided it's drawn as consistently and professionally as the rest of the collection?

The creator of these icons said they won't add it. At this point just consider switching to FA/PI/MD icons.

> Floppy disks haven't been used in decades, I just don't see a reason to perpetuate something that's inaccurate.

Image below says otherwise. Azure below is used by millions of users, but obviously we are providing inaccurate information as floppy's haven't been seen in decades. Cassette tapes are in style now.

![image](https://user-images.githubusercontent.com/12689117/179051284-732e9bb8-e45d-4b81-b674-7446c90c83a9.png)

**Comment by Cadorin** [comment]
I have to agree with all the comments. Bootstrap is awesome. Your icons are amazing. However, people expect to have a floppy button to save their files. For example, Microsoft Word still uses a floppy disk icon to save documents. That's common sense. Icons with arrows are good for downloading files, but in my app users save their documents online, so they don't download anything. All the icons suggested to represent the save action are not suitable for my users and me. Please think it over. It's so simple to have a new SVG in the icon pack, I really don't understand why the Bootstrap team just refuses to include it. This refusal is repelling developers from using Bootstrap.

**Comment by christopherreay** [comment]
a downward arrow means download. what weird zealot is doing this? life is
too short to surround yourself with nonsense.

put in the icon

**Comment by Cadorin** [comment]
As Claviska said:
We don't use [magnifying glasses](https://icons.getbootstrap.com/icons/search/) to search for things
We don't use [hourglasses](https://icons.getbootstrap.com/icons/hourglass/) while we're waiting
We don't use [film](https://icons.getbootstrap.com/icons/film/) in our cameras anymore
[Bells](https://icons.getbootstrap.com/icons/bell/) don't go off when we get notifications
We don't use paper for computer [files](https://icons.getbootstrap.com/icons/file/)
Most users don't have physical [calendars](https://icons.getbootstrap.com/icons/calendar/) anymore

And

I haven't seen a cassette tape in ages, yet an icon for that was released in v1.9.0 [just yesterday](https://github.com/twbs/icons/releases/tag/v1.9.0).
--------------------------------------------------------------------------------
Why did you add a cassette icon, which is less valuable than a floppy disk icon? How many users asked for a cassette icon, and how many asked for a floppy disk? Is not having a floppy icon now a matter of honour for the Bootstrap team?

**Comment by christopherreay** [comment]
it's just... my clients get confused. ... i can't fix that

**Comment by simo026q** [comment]
> No plans for a floppy disk icon at the moment—trying to push this floppy disk-esque one instead :).

You have 33 icons that can represent a cart and you are telling me that you are not willing to add 1 highly requested icon? I have a hard time understanding that, people can still freely use the old save icons. If you are really that stubborn about not adding a floppy disk icon, at least try to change the current save icon so it doesn't get so easily confused with a download icon.

**Comment by jaimir14** [comment]
There are no good reasons for not adding a simply icon that a lot of people is asking since years now. Looks like some childish person just closed this ticket to "make a point"... it was just matter of adding a simply image, they are adding weird and unused images very often... they just don't want to accept that save icon should look like floppy disk and not the "save" icon that they added... Even worse, they are giving weird excuses, like "Floppy disks haven't been used in decades", really? so, looks like there is people using cassettes recently based on the icons you are adding...

**Comment by NylePudding** [comment]
It's a pretty wild decision to leave out the floppy disk. If anything, the fact it is rarely used physically anymore strengthens the meaning of the symbol. Folks who are unfamiliar with physical floppy disks have described it as the "save symbol", you can't get any less clear than that!

**Comment by mdo** [comment]
https://github.com/twbs/icons/issues/1599#issuecomment-1483319867
