### ISSUE TITLE
How to check unicode for certain icons?

### ISSUE THREAD

**Issue by chrisooo3** [twbs/icons#979]
I need to display icons in select input in `<option />` tag,
How to check unicode of your's icons? 
I need to know what are the unicodes for these icons:
1. `<i class="bi bi-sort-alpha-up"></i>`
2. `<i class="bi bi-sort-alpha-down"></i>`

Thanks in advance!

**Comment by RubenVerg** [comment]
if I remember correctly there's a PR for showing them in the icon page, for now I think you have to open the css file and search for the icon manually

**Comment by mdo** [comment]
Duplicate of #891.
