### ISSUE TITLE
add unity icon

### ISSUE THREAD

**Issue by Harindulk** [twbs/icons#983]
Please add unity icon
https://github.com/Harindulk/harindu.dev/blob/main/assets/icons/unity.svg

**Comment by evrifaessa** [comment]
Unity introduced a new logo:

![Unity logo](https://upload.wikimedia.org/wikipedia/commons/c/c4/Unity_2021.svg)

https://upload.wikimedia.org/wikipedia/commons/c/c4/Unity_2021.svg

**Comment by Harindulk** [comment]
@evrifaessa ah yeah
