### ISSUE TITLE
Update the Discord icon to the new official design

### ISSUE THREAD

**Issue by alex3025** [twbs/icons#994]
New icon design:

![image](https://user-images.githubusercontent.com/31188915/130841889-b484b1ea-359a-45c6-837d-f9ac69d9486d.png)

Source: https://discord.com/branding

**Comment by honzajavorek** [comment]
There is a pull request for this: https://github.com/twbs/icons/pull/986

**Comment by alex3025** [comment]
Oh, so when will become that available on the docs?
