### ISSUE TITLE
icons are not loading in prod build

### ISSUE THREAD

**Issue by Shyam268** [twbs/icons#996]
Getting error in prod build:
error 
Failed to load resource: the server responded with a status of 404 (Not Found)
my-app/:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: **https://my-app/static/media/bootstrap-icons.94eeade1.woff**

![image](https://user-images.githubusercontent.com/30112490/131482712-2a28fcc6-f3ea-4936-8348-3532467a150d.png)

Steps to reproduce:
Configuration:
Installed packages:
```
    "@types/node": "^12.20.19",
    "@types/react": "^17.0.16",
    "@types/react-dom": "^17.0.9",
    "bootstrap-icons": "^1.5.0",
    "font-awesome": "^4.7.0",
```

packages are imported in index.tsx
   ```
    import ReactDOM from 'react-dom';
    import 'bootstrap/dist/css/bootstrap.css';
    import "bootstrap-icons/font/bootstrap-icons.css";
    import 'font-awesome/css/font-awesome.min.css';
    import React from 'react';
    import App from './App';
```

1. whith `npm statrt` command app is running locally and all icon are loaded as expected
2. here is the problem I build project in production mode using `npm run build`
   the out put of the dist folder
  
 ![image](https://user-images.githubusercontent.com/30112490/131482162-ca5d5d0d-c461-4d4b-94aa-a9a2a089bd2f.png)

and dist/static/media folder is 

![image](https://user-images.githubusercontent.com/30112490/131482918-13c0a122-8c75-4ff9-917e-86f96f09dcfb.png)

and once i deployed to azure app service app is working but icons are not loading
 
![image](https://user-images.githubusercontent.com/30112490/131482503-4e0f9e8e-5e61-4691-b980-e48d4253b9cc.png)

the actual file path is **https://my-app/dev/wwwroot/static/media/bootstrap-icons.94eeade1.woff**

seems "wwwroot" is there how to solve this .?

**Comment by mdo** [comment]
Not seeing this as a bug, so closing out.
